version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  redis_storage:
    driver: local

services:
  redis:
    image: 'bitnami/redis:6.2'
    networks:
      - internal
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - 'redis_storage:/bitnami/redis/data'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  redis-commander:
    image: rediscommander/redis-commander:latest
    networks:
      - internal
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis
