version: "3.9"

networks:
  internal:
    driver: bridge

volumes:
  redis_storage:
    driver: local
  mysql_storage:
    driver: local
  minio_storage:
    driver: local

services:
  redis:
    image: 'bitnami/redis:6.2'
    networks:
      - internal
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - 'redis_storage:/bitnami/redis/data'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  redis-commander:
    image: rediscommander/redis-commander:latest
    networks:
      - internal
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - redis

  mysql:
    image: 'bitnami/mysql:8.0'
    networks:
      - internal
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - 'mysql_storage:/bitnami/mysql/data'
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  mysql-adminer:
    image: 'adminer:4'
    networks:
      - internal
    ports:
      - "${MYSQL_ADMINER_PORT}:8080"
    environment:
      - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  minio:
    image: 'bitnami/minio:2022-debian-10'
    networks:
      - internal
    ports:
      - "${MINIO_API_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=imageer
    volumes:
      - 'minio_storage:/data'
