// Code generated by MockGen. DO NOT EDIT.
// Source: jwt.go
//
// Generated by this command:
//
//	mockgen -package port -source=jwt.go -destination=jwt_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	reflect "reflect"

	domain "github.com/isutare412/imageer/internal/gateway/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockJWTSigner is a mock of JWTSigner interface.
type MockJWTSigner struct {
	ctrl     *gomock.Controller
	recorder *MockJWTSignerMockRecorder
	isgomock struct{}
}

// MockJWTSignerMockRecorder is the mock recorder for MockJWTSigner.
type MockJWTSignerMockRecorder struct {
	mock *MockJWTSigner
}

// NewMockJWTSigner creates a new mock instance.
func NewMockJWTSigner(ctrl *gomock.Controller) *MockJWTSigner {
	mock := &MockJWTSigner{ctrl: ctrl}
	mock.recorder = &MockJWTSignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTSigner) EXPECT() *MockJWTSignerMockRecorder {
	return m.recorder
}

// SignUserToken mocks base method.
func (m *MockJWTSigner) SignUserToken(payload domain.UserTokenPayload) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUserToken", payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignUserToken indicates an expected call of SignUserToken.
func (mr *MockJWTSignerMockRecorder) SignUserToken(payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUserToken", reflect.TypeOf((*MockJWTSigner)(nil).SignUserToken), payload)
}

// MockJWTVerifier is a mock of JWTVerifier interface.
type MockJWTVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockJWTVerifierMockRecorder
	isgomock struct{}
}

// MockJWTVerifierMockRecorder is the mock recorder for MockJWTVerifier.
type MockJWTVerifierMockRecorder struct {
	mock *MockJWTVerifier
}

// NewMockJWTVerifier creates a new mock instance.
func NewMockJWTVerifier(ctrl *gomock.Controller) *MockJWTVerifier {
	mock := &MockJWTVerifier{ctrl: ctrl}
	mock.recorder = &MockJWTVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTVerifier) EXPECT() *MockJWTVerifierMockRecorder {
	return m.recorder
}

// VerifyUserToken mocks base method.
func (m *MockJWTVerifier) VerifyUserToken(token string) (domain.UserTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserToken", token)
	ret0, _ := ret[0].(domain.UserTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUserToken indicates an expected call of VerifyUserToken.
func (mr *MockJWTVerifierMockRecorder) VerifyUserToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserToken", reflect.TypeOf((*MockJWTVerifier)(nil).VerifyUserToken), token)
}
