// Code generated by MockGen. DO NOT EDIT.
// Source: leader_election.go
//
// Generated by this command:
//
//	mockgen -package port -source=leader_election.go -destination=leader_election_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLeaderHandler is a mock of LeaderHandler interface.
type MockLeaderHandler struct {
	ctrl     *gomock.Controller
	recorder *MockLeaderHandlerMockRecorder
	isgomock struct{}
}

// MockLeaderHandlerMockRecorder is the mock recorder for MockLeaderHandler.
type MockLeaderHandlerMockRecorder struct {
	mock *MockLeaderHandler
}

// NewMockLeaderHandler creates a new mock instance.
func NewMockLeaderHandler(ctrl *gomock.Controller) *MockLeaderHandler {
	mock := &MockLeaderHandler{ctrl: ctrl}
	mock.recorder = &MockLeaderHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaderHandler) EXPECT() *MockLeaderHandlerMockRecorder {
	return m.recorder
}

// OnStartedLeading mocks base method.
func (m *MockLeaderHandler) OnStartedLeading(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStartedLeading", ctx)
}

// OnStartedLeading indicates an expected call of OnStartedLeading.
func (mr *MockLeaderHandlerMockRecorder) OnStartedLeading(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStartedLeading", reflect.TypeOf((*MockLeaderHandler)(nil).OnStartedLeading), ctx)
}

// OnStoppedLeading mocks base method.
func (m *MockLeaderHandler) OnStoppedLeading() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStoppedLeading")
}

// OnStoppedLeading indicates an expected call of OnStoppedLeading.
func (mr *MockLeaderHandlerMockRecorder) OnStoppedLeading() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStoppedLeading", reflect.TypeOf((*MockLeaderHandler)(nil).OnStoppedLeading))
}
