// Code generated by MockGen. DO NOT EDIT.
// Source: oidc.go
//
// Generated by this command:
//
//	mockgen -package port -source=oidc.go -destination=oidc_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	domain "github.com/isutare412/imageer/internal/gateway/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCProvider is a mock of OIDCProvider interface.
type MockOIDCProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCProviderMockRecorder
	isgomock struct{}
}

// MockOIDCProviderMockRecorder is the mock recorder for MockOIDCProvider.
type MockOIDCProviderMockRecorder struct {
	mock *MockOIDCProvider
}

// NewMockOIDCProvider creates a new mock instance.
func NewMockOIDCProvider(ctrl *gomock.Controller) *MockOIDCProvider {
	mock := &MockOIDCProvider{ctrl: ctrl}
	mock.recorder = &MockOIDCProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCProvider) EXPECT() *MockOIDCProviderMockRecorder {
	return m.recorder
}

// BuildAuthenticationURL mocks base method.
func (m *MockOIDCProvider) BuildAuthenticationURL(baseURL, state string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildAuthenticationURL", baseURL, state)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildAuthenticationURL indicates an expected call of BuildAuthenticationURL.
func (mr *MockOIDCProviderMockRecorder) BuildAuthenticationURL(baseURL, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildAuthenticationURL", reflect.TypeOf((*MockOIDCProvider)(nil).BuildAuthenticationURL), baseURL, state)
}

// ExchangeCode mocks base method.
func (m *MockOIDCProvider) ExchangeCode(ctx context.Context, baseURL, code string) (domain.IDTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeCode", ctx, baseURL, code)
	ret0, _ := ret[0].(domain.IDTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeCode indicates an expected call of ExchangeCode.
func (mr *MockOIDCProviderMockRecorder) ExchangeCode(ctx, baseURL, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeCode", reflect.TypeOf((*MockOIDCProvider)(nil).ExchangeCode), ctx, baseURL, code)
}
