// Code generated by MockGen. DO NOT EDIT.
// Source: pubsub.go
//
// Generated by this command:
//
//	mockgen -package port -source=pubsub.go -destination=pubsub_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImageProcessDonePublisher is a mock of ImageProcessDonePublisher interface.
type MockImageProcessDonePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessDonePublisherMockRecorder
	isgomock struct{}
}

// MockImageProcessDonePublisherMockRecorder is the mock recorder for MockImageProcessDonePublisher.
type MockImageProcessDonePublisherMockRecorder struct {
	mock *MockImageProcessDonePublisher
}

// NewMockImageProcessDonePublisher creates a new mock instance.
func NewMockImageProcessDonePublisher(ctrl *gomock.Controller) *MockImageProcessDonePublisher {
	mock := &MockImageProcessDonePublisher{ctrl: ctrl}
	mock.recorder = &MockImageProcessDonePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessDonePublisher) EXPECT() *MockImageProcessDonePublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockImageProcessDonePublisher) Publish(ctx context.Context, imageID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, imageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockImageProcessDonePublisherMockRecorder) Publish(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockImageProcessDonePublisher)(nil).Publish), ctx, imageID)
}

// MockImageProcessDoneSubscriber is a mock of ImageProcessDoneSubscriber interface.
type MockImageProcessDoneSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessDoneSubscriberMockRecorder
	isgomock struct{}
}

// MockImageProcessDoneSubscriberMockRecorder is the mock recorder for MockImageProcessDoneSubscriber.
type MockImageProcessDoneSubscriberMockRecorder struct {
	mock *MockImageProcessDoneSubscriber
}

// NewMockImageProcessDoneSubscriber creates a new mock instance.
func NewMockImageProcessDoneSubscriber(ctrl *gomock.Controller) *MockImageProcessDoneSubscriber {
	mock := &MockImageProcessDoneSubscriber{ctrl: ctrl}
	mock.recorder = &MockImageProcessDoneSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessDoneSubscriber) EXPECT() *MockImageProcessDoneSubscriberMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockImageProcessDoneSubscriber) Subscribe(ctx context.Context, imageID string) (<-chan struct{}, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, imageID)
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockImageProcessDoneSubscriberMockRecorder) Subscribe(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockImageProcessDoneSubscriber)(nil).Subscribe), ctx, imageID)
}
