// Code generated by MockGen. DO NOT EDIT.
// Source: pubsub.go
//
// Generated by this command:
//
//	mockgen -package port -source=pubsub.go -destination=pubsub_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImageNotificationPublisher is a mock of ImageNotificationPublisher interface.
type MockImageNotificationPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockImageNotificationPublisherMockRecorder
	isgomock struct{}
}

// MockImageNotificationPublisherMockRecorder is the mock recorder for MockImageNotificationPublisher.
type MockImageNotificationPublisherMockRecorder struct {
	mock *MockImageNotificationPublisher
}

// NewMockImageNotificationPublisher creates a new mock instance.
func NewMockImageNotificationPublisher(ctrl *gomock.Controller) *MockImageNotificationPublisher {
	mock := &MockImageNotificationPublisher{ctrl: ctrl}
	mock.recorder = &MockImageNotificationPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageNotificationPublisher) EXPECT() *MockImageNotificationPublisherMockRecorder {
	return m.recorder
}

// PublishProcessDone mocks base method.
func (m *MockImageNotificationPublisher) PublishProcessDone(ctx context.Context, imageID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishProcessDone", ctx, imageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishProcessDone indicates an expected call of PublishProcessDone.
func (mr *MockImageNotificationPublisherMockRecorder) PublishProcessDone(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishProcessDone", reflect.TypeOf((*MockImageNotificationPublisher)(nil).PublishProcessDone), ctx, imageID)
}

// PublishUploadDone mocks base method.
func (m *MockImageNotificationPublisher) PublishUploadDone(ctx context.Context, imageID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishUploadDone", ctx, imageID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishUploadDone indicates an expected call of PublishUploadDone.
func (mr *MockImageNotificationPublisherMockRecorder) PublishUploadDone(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishUploadDone", reflect.TypeOf((*MockImageNotificationPublisher)(nil).PublishUploadDone), ctx, imageID)
}

// MockImageUploadDoneSubscriber is a mock of ImageUploadDoneSubscriber interface.
type MockImageUploadDoneSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockImageUploadDoneSubscriberMockRecorder
	isgomock struct{}
}

// MockImageUploadDoneSubscriberMockRecorder is the mock recorder for MockImageUploadDoneSubscriber.
type MockImageUploadDoneSubscriberMockRecorder struct {
	mock *MockImageUploadDoneSubscriber
}

// NewMockImageUploadDoneSubscriber creates a new mock instance.
func NewMockImageUploadDoneSubscriber(ctrl *gomock.Controller) *MockImageUploadDoneSubscriber {
	mock := &MockImageUploadDoneSubscriber{ctrl: ctrl}
	mock.recorder = &MockImageUploadDoneSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageUploadDoneSubscriber) EXPECT() *MockImageUploadDoneSubscriberMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockImageUploadDoneSubscriber) Subscribe(ctx context.Context, imageID string) (<-chan struct{}, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, imageID)
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockImageUploadDoneSubscriberMockRecorder) Subscribe(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockImageUploadDoneSubscriber)(nil).Subscribe), ctx, imageID)
}

// MockImageProcessDoneSubscriber is a mock of ImageProcessDoneSubscriber interface.
type MockImageProcessDoneSubscriber struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessDoneSubscriberMockRecorder
	isgomock struct{}
}

// MockImageProcessDoneSubscriberMockRecorder is the mock recorder for MockImageProcessDoneSubscriber.
type MockImageProcessDoneSubscriberMockRecorder struct {
	mock *MockImageProcessDoneSubscriber
}

// NewMockImageProcessDoneSubscriber creates a new mock instance.
func NewMockImageProcessDoneSubscriber(ctrl *gomock.Controller) *MockImageProcessDoneSubscriber {
	mock := &MockImageProcessDoneSubscriber{ctrl: ctrl}
	mock.recorder = &MockImageProcessDoneSubscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessDoneSubscriber) EXPECT() *MockImageProcessDoneSubscriberMockRecorder {
	return m.recorder
}

// Subscribe mocks base method.
func (m *MockImageProcessDoneSubscriber) Subscribe(ctx context.Context, imageID string) (<-chan struct{}, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, imageID)
	ret0, _ := ret[0].(<-chan struct{})
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockImageProcessDoneSubscriberMockRecorder) Subscribe(ctx, imageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockImageProcessDoneSubscriber)(nil).Subscribe), ctx, imageID)
}
