// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go
//
// Generated by this command:
//
//	mockgen -package port -source=queue.go -destination=queue_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	imageerv1 "github.com/isutare412/imageer/pkg/protogen/imageer/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockImageEventQueue is a mock of ImageEventQueue interface.
type MockImageEventQueue struct {
	ctrl     *gomock.Controller
	recorder *MockImageEventQueueMockRecorder
	isgomock struct{}
}

// MockImageEventQueueMockRecorder is the mock recorder for MockImageEventQueue.
type MockImageEventQueueMockRecorder struct {
	mock *MockImageEventQueue
}

// NewMockImageEventQueue creates a new mock instance.
func NewMockImageEventQueue(ctrl *gomock.Controller) *MockImageEventQueue {
	mock := &MockImageEventQueue{ctrl: ctrl}
	mock.recorder = &MockImageEventQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageEventQueue) EXPECT() *MockImageEventQueueMockRecorder {
	return m.recorder
}

// PushImageProcessRequest mocks base method.
func (m *MockImageEventQueue) PushImageProcessRequest(arg0 context.Context, arg1 *imageerv1.ImageProcessRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushImageProcessRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushImageProcessRequest indicates an expected call of PushImageProcessRequest.
func (mr *MockImageEventQueueMockRecorder) PushImageProcessRequest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushImageProcessRequest", reflect.TypeOf((*MockImageEventQueue)(nil).PushImageProcessRequest), arg0, arg1)
}
