// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go
//
// Generated by this command:
//
//	mockgen -package port -source=queue.go -destination=queue_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	imageerv1 "github.com/isutare412/imageer/pkg/protogen/imageer/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockImageProcessRequestQueue is a mock of ImageProcessRequestQueue interface.
type MockImageProcessRequestQueue struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessRequestQueueMockRecorder
	isgomock struct{}
}

// MockImageProcessRequestQueueMockRecorder is the mock recorder for MockImageProcessRequestQueue.
type MockImageProcessRequestQueueMockRecorder struct {
	mock *MockImageProcessRequestQueue
}

// NewMockImageProcessRequestQueue creates a new mock instance.
func NewMockImageProcessRequestQueue(ctrl *gomock.Controller) *MockImageProcessRequestQueue {
	mock := &MockImageProcessRequestQueue{ctrl: ctrl}
	mock.recorder = &MockImageProcessRequestQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessRequestQueue) EXPECT() *MockImageProcessRequestQueueMockRecorder {
	return m.recorder
}

// Push mocks base method.
func (m *MockImageProcessRequestQueue) Push(arg0 context.Context, arg1 *imageerv1.ImageProcessRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockImageProcessRequestQueueMockRecorder) Push(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockImageProcessRequestQueue)(nil).Push), arg0, arg1)
}
