// Code generated by MockGen. DO NOT EDIT.
// Source: s3.go
//
// Generated by this command:
//
//	mockgen -package port -source=s3.go -destination=s3_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	domain "github.com/isutare412/imageer/internal/gateway/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockS3Presigner is a mock of S3Presigner interface.
type MockS3Presigner struct {
	ctrl     *gomock.Controller
	recorder *MockS3PresignerMockRecorder
	isgomock struct{}
}

// MockS3PresignerMockRecorder is the mock recorder for MockS3Presigner.
type MockS3PresignerMockRecorder struct {
	mock *MockS3Presigner
}

// NewMockS3Presigner creates a new mock instance.
func NewMockS3Presigner(ctrl *gomock.Controller) *MockS3Presigner {
	mock := &MockS3Presigner{ctrl: ctrl}
	mock.recorder = &MockS3PresignerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Presigner) EXPECT() *MockS3PresignerMockRecorder {
	return m.recorder
}

// PresignPutObject mocks base method.
func (m *MockS3Presigner) PresignPutObject(arg0 context.Context, arg1 domain.PresignPutObjectRequest) (domain.PresignPutObjectResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresignPutObject", arg0, arg1)
	ret0, _ := ret[0].(domain.PresignPutObjectResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresignPutObject indicates an expected call of PresignPutObject.
func (mr *MockS3PresignerMockRecorder) PresignPutObject(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresignPutObject", reflect.TypeOf((*MockS3Presigner)(nil).PresignPutObject), arg0, arg1)
}

// MockObjectStorage is a mock of ObjectStorage interface.
type MockObjectStorage struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageMockRecorder
	isgomock struct{}
}

// MockObjectStorageMockRecorder is the mock recorder for MockObjectStorage.
type MockObjectStorageMockRecorder struct {
	mock *MockObjectStorage
}

// NewMockObjectStorage creates a new mock instance.
func NewMockObjectStorage(ctrl *gomock.Controller) *MockObjectStorage {
	mock := &MockObjectStorage{ctrl: ctrl}
	mock.recorder = &MockObjectStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorage) EXPECT() *MockObjectStorageMockRecorder {
	return m.recorder
}

// DeleteObjects mocks base method.
func (m *MockObjectStorage) DeleteObjects(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjects", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjects indicates an expected call of DeleteObjects.
func (mr *MockObjectStorageMockRecorder) DeleteObjects(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjects", reflect.TypeOf((*MockObjectStorage)(nil).DeleteObjects), ctx, keys)
}
