// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -package port -source=service.go -destination=service_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	domain "github.com/isutare412/imageer/internal/gateway/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// FinishGoogleSignIn mocks base method.
func (m *MockAuthService) FinishGoogleSignIn(arg0 context.Context, arg1 domain.FinishGoogleSignInRequest) (domain.FinishGoogleSignInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishGoogleSignIn", arg0, arg1)
	ret0, _ := ret[0].(domain.FinishGoogleSignInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishGoogleSignIn indicates an expected call of FinishGoogleSignIn.
func (mr *MockAuthServiceMockRecorder) FinishGoogleSignIn(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishGoogleSignIn", reflect.TypeOf((*MockAuthService)(nil).FinishGoogleSignIn), arg0, arg1)
}

// StartGoogleSignIn mocks base method.
func (m *MockAuthService) StartGoogleSignIn(arg0 context.Context, arg1 domain.StartGoogleSignInRequest) (domain.StartGoogleSignInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartGoogleSignIn", arg0, arg1)
	ret0, _ := ret[0].(domain.StartGoogleSignInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartGoogleSignIn indicates an expected call of StartGoogleSignIn.
func (mr *MockAuthServiceMockRecorder) StartGoogleSignIn(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartGoogleSignIn", reflect.TypeOf((*MockAuthService)(nil).StartGoogleSignIn), arg0, arg1)
}

// VerifyUserToken mocks base method.
func (m *MockAuthService) VerifyUserToken(ctx context.Context, userToken string) (domain.UserTokenPayload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyUserToken", ctx, userToken)
	ret0, _ := ret[0].(domain.UserTokenPayload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyUserToken indicates an expected call of VerifyUserToken.
func (mr *MockAuthServiceMockRecorder) VerifyUserToken(ctx, userToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyUserToken", reflect.TypeOf((*MockAuthService)(nil).VerifyUserToken), ctx, userToken)
}

// MockServiceAccountService is a mock of ServiceAccountService interface.
type MockServiceAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceAccountServiceMockRecorder
	isgomock struct{}
}

// MockServiceAccountServiceMockRecorder is the mock recorder for MockServiceAccountService.
type MockServiceAccountServiceMockRecorder struct {
	mock *MockServiceAccountService
}

// NewMockServiceAccountService creates a new mock instance.
func NewMockServiceAccountService(ctrl *gomock.Controller) *MockServiceAccountService {
	mock := &MockServiceAccountService{ctrl: ctrl}
	mock.recorder = &MockServiceAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceAccountService) EXPECT() *MockServiceAccountServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockServiceAccountService) Create(ctx context.Context, req domain.CreateServiceAccountRequest) (domain.ServiceAccountWithAPIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(domain.ServiceAccountWithAPIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockServiceAccountServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockServiceAccountService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockServiceAccountService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceAccountServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockServiceAccountService)(nil).Delete), ctx, id)
}

// GetByAPIKey mocks base method.
func (m *MockServiceAccountService) GetByAPIKey(ctx context.Context, key string) (domain.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAPIKey", ctx, key)
	ret0, _ := ret[0].(domain.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAPIKey indicates an expected call of GetByAPIKey.
func (mr *MockServiceAccountServiceMockRecorder) GetByAPIKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAPIKey", reflect.TypeOf((*MockServiceAccountService)(nil).GetByAPIKey), ctx, key)
}

// GetByID mocks base method.
func (m *MockServiceAccountService) GetByID(ctx context.Context, id string) (domain.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceAccountServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockServiceAccountService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockServiceAccountService) List(ctx context.Context, params domain.ListServiceAccountsParams) (domain.ServiceAccounts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(domain.ServiceAccounts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceAccountServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockServiceAccountService)(nil).List), ctx, params)
}

// Update mocks base method.
func (m *MockServiceAccountService) Update(ctx context.Context, req domain.UpdateServiceAccountRequest) (domain.ServiceAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(domain.ServiceAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceAccountServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockServiceAccountService)(nil).Update), ctx, req)
}

// MockProjectService is a mock of ProjectService interface.
type MockProjectService struct {
	ctrl     *gomock.Controller
	recorder *MockProjectServiceMockRecorder
	isgomock struct{}
}

// MockProjectServiceMockRecorder is the mock recorder for MockProjectService.
type MockProjectServiceMockRecorder struct {
	mock *MockProjectService
}

// NewMockProjectService creates a new mock instance.
func NewMockProjectService(ctrl *gomock.Controller) *MockProjectService {
	mock := &MockProjectService{ctrl: ctrl}
	mock.recorder = &MockProjectServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectService) EXPECT() *MockProjectServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectService) Create(ctx context.Context, req domain.CreateProjectRequest) (domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectServiceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectService)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockProjectService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectService)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockProjectService) GetByID(ctx context.Context, id string) (domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockProjectServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockProjectService)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockProjectService) List(ctx context.Context, params domain.ListProjectsParams) (domain.Projects, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].(domain.Projects)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectServiceMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectService)(nil).List), ctx, params)
}

// Update mocks base method.
func (m *MockProjectService) Update(ctx context.Context, req domain.UpdateProjectRequest) (domain.Project, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(domain.Project)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProjectServiceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectService)(nil).Update), ctx, req)
}

// MockImageService is a mock of ImageService interface.
type MockImageService struct {
	ctrl     *gomock.Controller
	recorder *MockImageServiceMockRecorder
	isgomock struct{}
}

// MockImageServiceMockRecorder is the mock recorder for MockImageService.
type MockImageServiceMockRecorder struct {
	mock *MockImageService
}

// NewMockImageService creates a new mock instance.
func NewMockImageService(ctrl *gomock.Controller) *MockImageService {
	mock := &MockImageService{ctrl: ctrl}
	mock.recorder = &MockImageServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageService) EXPECT() *MockImageServiceMockRecorder {
	return m.recorder
}

// CreateUploadURL mocks base method.
func (m *MockImageService) CreateUploadURL(arg0 context.Context, arg1 domain.CreateUploadURLRequest) (domain.UploadURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUploadURL", arg0, arg1)
	ret0, _ := ret[0].(domain.UploadURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUploadURL indicates an expected call of CreateUploadURL.
func (mr *MockImageServiceMockRecorder) CreateUploadURL(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUploadURL", reflect.TypeOf((*MockImageService)(nil).CreateUploadURL), arg0, arg1)
}

// StartImageProcessingOnUpload mocks base method.
func (m *MockImageService) StartImageProcessingOnUpload(ctx context.Context, s3Key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartImageProcessingOnUpload", ctx, s3Key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartImageProcessingOnUpload indicates an expected call of StartImageProcessingOnUpload.
func (mr *MockImageServiceMockRecorder) StartImageProcessingOnUpload(ctx, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartImageProcessingOnUpload", reflect.TypeOf((*MockImageService)(nil).StartImageProcessingOnUpload), ctx, s3Key)
}
