// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -package port -source=service.go -destination=service_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	domain "github.com/isutare412/imageer/internal/gateway/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// FinishGoogleSignIn mocks base method.
func (m *MockAuthService) FinishGoogleSignIn(arg0 context.Context, arg1 domain.FinishGoogleSignInRequest) (domain.FinishGoogleSignInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishGoogleSignIn", arg0, arg1)
	ret0, _ := ret[0].(domain.FinishGoogleSignInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishGoogleSignIn indicates an expected call of FinishGoogleSignIn.
func (mr *MockAuthServiceMockRecorder) FinishGoogleSignIn(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishGoogleSignIn", reflect.TypeOf((*MockAuthService)(nil).FinishGoogleSignIn), arg0, arg1)
}

// StartGoogleSignIn mocks base method.
func (m *MockAuthService) StartGoogleSignIn(arg0 context.Context, arg1 domain.StartGoogleSignInRequest) (domain.StartGoogleSignInResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartGoogleSignIn", arg0, arg1)
	ret0, _ := ret[0].(domain.StartGoogleSignInResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartGoogleSignIn indicates an expected call of StartGoogleSignIn.
func (mr *MockAuthServiceMockRecorder) StartGoogleSignIn(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartGoogleSignIn", reflect.TypeOf((*MockAuthService)(nil).StartGoogleSignIn), arg0, arg1)
}
