@scheme=http
@url=localhost:8080
@apiPrefix=api/v1
@token={{signIn.response.body.token}}

################################################################################
# Check CORS
################################################################################
OPTIONS {{scheme}}://{{url}}/docs/index.html HTTP/1.1
Access-Control-Request-Method: GET
Access-Control-Request-Headers: origin, x-requested-with
Origin: http://localhost

################################################################################
# Get swagger UI
################################################################################
GET {{scheme}}://{{url}}/docs/index.html HTTP/1.1
Content-Type: application/json

################################################################################
# Sign in
################################################################################
# @name signIn
POST {{scheme}}://{{url}}/signIn HTTP/1.1
Content-Type: application/json

{
  "email": "isutare412@gmail.com",
  "password": "simplepass"
}

################################################################################
# Sign out
################################################################################
GET {{scheme}}://{{url}}/signOut HTTP/1.1

################################################################################
# Sign in test
################################################################################
GET {{scheme}}://{{url}}/signTest HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

################################################################################
# Greetings
################################################################################
GET {{scheme}}://{{url}}/{{apiPrefix}}/greetings/Suhyuk HTTP/1.1
Content-Type: application/json

################################################################################
# Get user by session
################################################################################
GET {{scheme}}://{{url}}/{{apiPrefix}}/users HTTP/1.1
Content-Type: application/json

################################################################################
# Get user by id
################################################################################
GET {{scheme}}://{{url}}/{{apiPrefix}}/users/6 HTTP/1.1
Content-Type: application/json

################################################################################
# Create user
################################################################################
POST {{scheme}}://{{url}}/{{apiPrefix}}/users HTTP/1.1
Content-Type: application/json

{
  "givenName": "Suhyuk",
  "familyName": "Lee",
  "email": "isutare412@gmail.com",
  "password": "simplepass"
}

################################################################################
# Archive file
################################################################################
POST {{scheme}}://{{url}}/{{apiPrefix}}/images/archives HTTP/1.1
Content-Type: multipart/form-data; boundary=ComplexBoundaryQ3qAfv5fD

--ComplexBoundaryQ3qAfv5fD
Content-Disposition: form-data; name="image"; filename="bus.png"
Content-Type: application/octet-stream

< ./test-data/bus.png
--ComplexBoundaryQ3qAfv5fD--
