@scheme=http
@url=localhost:8080
@apiPrefix=api/v1
@token={{signIn.response.body.token}}

GET {{scheme}}://{{url}}/docs/index.html HTTP/1.1
content-type: application/json

###

# @name signIn
POST {{scheme}}://{{url}}/signIn HTTP/1.1
content-type: application/json

{
  "email": "isutare412@gmail.com",
  "password": "simplepass"
}

###

GET {{scheme}}://{{url}}/signCheck HTTP/1.1
content-type: application/json

###

GET {{scheme}}://{{url}}/{{apiPrefix}}/greetings/Suhyuk HTTP/1.1
content-type: application/json

###

POST {{scheme}}://{{url}}/{{apiPrefix}}/users HTTP/1.1
content-type: application/json

{
  "givenName": "Suhyuk",
  "familyName": "Lee",
  "email": "isutare412@gmail.com",
  "password": "simplepass"
}

###

GET {{scheme}}://{{url}}/{{apiPrefix}}/users/6 HTTP/1.1
content-type: application/json
