// Code generated by MockGen. DO NOT EDIT.
// Source: image_processor.go
//
// Generated by this command:
//
//	mockgen -package port -source=image_processor.go -destination=image_processor_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	domain "github.com/isutare412/imageer/internal/processor/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockImageProcessor is a mock of ImageProcessor interface.
type MockImageProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessorMockRecorder
	isgomock struct{}
}

// MockImageProcessorMockRecorder is the mock recorder for MockImageProcessor.
type MockImageProcessorMockRecorder struct {
	mock *MockImageProcessor
}

// NewMockImageProcessor creates a new mock instance.
func NewMockImageProcessor(ctrl *gomock.Controller) *MockImageProcessor {
	mock := &MockImageProcessor{ctrl: ctrl}
	mock.recorder = &MockImageProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessor) EXPECT() *MockImageProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockImageProcessor) Process(arg0 context.Context, arg1 domain.RawImage, arg2 domain.Preset) (domain.RawImage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.RawImage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockImageProcessorMockRecorder) Process(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockImageProcessor)(nil).Process), arg0, arg1, arg2)
}
