// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go
//
// Generated by this command:
//
//	mockgen -package port -source=queue.go -destination=queue_mock.go
//

// Package port is a generated GoMock package.
package port

import (
	context "context"
	reflect "reflect"

	imageerv1 "github.com/isutare412/imageer/pkg/protogen/imageer/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockImageProcessResultQueue is a mock of ImageProcessResultQueue interface.
type MockImageProcessResultQueue struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessResultQueueMockRecorder
	isgomock struct{}
}

// MockImageProcessResultQueueMockRecorder is the mock recorder for MockImageProcessResultQueue.
type MockImageProcessResultQueueMockRecorder struct {
	mock *MockImageProcessResultQueue
}

// NewMockImageProcessResultQueue creates a new mock instance.
func NewMockImageProcessResultQueue(ctrl *gomock.Controller) *MockImageProcessResultQueue {
	mock := &MockImageProcessResultQueue{ctrl: ctrl}
	mock.recorder = &MockImageProcessResultQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessResultQueue) EXPECT() *MockImageProcessResultQueueMockRecorder {
	return m.recorder
}

// Push mocks base method.
func (m *MockImageProcessResultQueue) Push(arg0 context.Context, arg1 *imageerv1.ImageProcessResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockImageProcessResultQueueMockRecorder) Push(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockImageProcessResultQueue)(nil).Push), arg0, arg1)
}
