// Code generated by "enumer -type=SortDirection -trimprefix SortDirection -output sort_direction_enum.go -transform snake-upper -text -json -sql"; DO NOT EDIT.

package dbhelpers

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _SortDirectionName = "UNSPECIFIEDASCDESC"

var _SortDirectionIndex = [...]uint8{0, 11, 14, 18}

const _SortDirectionLowerName = "unspecifiedascdesc"

func (i SortDirection) String() string {
	if i < 0 || i >= SortDirection(len(_SortDirectionIndex)-1) {
		return fmt.Sprintf("SortDirection(%d)", i)
	}
	return _SortDirectionName[_SortDirectionIndex[i]:_SortDirectionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SortDirectionNoOp() {
	var x [1]struct{}
	_ = x[SortDirectionUnspecified-(0)]
	_ = x[SortDirectionAsc-(1)]
	_ = x[SortDirectionDesc-(2)]
}

var _SortDirectionValues = []SortDirection{SortDirectionUnspecified, SortDirectionAsc, SortDirectionDesc}

var _SortDirectionNameToValueMap = map[string]SortDirection{
	_SortDirectionName[0:11]:       SortDirectionUnspecified,
	_SortDirectionLowerName[0:11]:  SortDirectionUnspecified,
	_SortDirectionName[11:14]:      SortDirectionAsc,
	_SortDirectionLowerName[11:14]: SortDirectionAsc,
	_SortDirectionName[14:18]:      SortDirectionDesc,
	_SortDirectionLowerName[14:18]: SortDirectionDesc,
}

var _SortDirectionNames = []string{
	_SortDirectionName[0:11],
	_SortDirectionName[11:14],
	_SortDirectionName[14:18],
}

// SortDirectionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SortDirectionString(s string) (SortDirection, error) {
	if val, ok := _SortDirectionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SortDirectionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SortDirection values", s)
}

// SortDirectionValues returns all values of the enum
func SortDirectionValues() []SortDirection {
	return _SortDirectionValues
}

// SortDirectionStrings returns a slice of all String values of the enum
func SortDirectionStrings() []string {
	strs := make([]string, len(_SortDirectionNames))
	copy(strs, _SortDirectionNames)
	return strs
}

// IsASortDirection returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SortDirection) IsASortDirection() bool {
	for _, v := range _SortDirectionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for SortDirection
func (i SortDirection) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for SortDirection
func (i *SortDirection) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("SortDirection should be a string, got %s", data)
	}

	var err error
	*i, err = SortDirectionString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for SortDirection
func (i SortDirection) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for SortDirection
func (i *SortDirection) UnmarshalText(text []byte) error {
	var err error
	*i, err = SortDirectionString(string(text))
	return err
}

func (i SortDirection) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *SortDirection) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of SortDirection: %[1]T(%[1]v)", value)
	}

	val, err := SortDirectionString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
