mode: development # development/production

job:
  retryDelay: 5000 # ms
  queue:
    request: processor-job-request
    response: processor-job-response

redis:
  addrs:
    - localhost:6379
  password: imageer
  stream:
    groupName: processor-group
