definitions:
  http.createUserReq:
    properties:
      email:
        type: string
      familyName:
        type: string
      givenName:
        type: string
      password:
        type: string
    type: object
  http.createUserRes:
    properties:
      credit:
        type: integer
      email:
        type: string
      familyName:
        type: string
      givenName:
        type: string
      id:
        type: integer
    type: object
  http.errorRes:
    properties:
      code:
        example: 400
        type: integer
      msg:
        example: simple error message
        type: string
    type: object
  http.getGreetingRes:
    properties:
      msg:
        type: string
    type: object
  http.getUserRes:
    properties:
      credit:
        type: integer
      email:
        type: string
      familyName:
        type: string
      givenName:
        type: string
      id:
        type: integer
    type: object
  http.signInReq:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  http.signInRes:
    properties:
      token:
        type: string
    type: object
info:
  contact: {}
  description: Endpoint API for image processing service.
  title: Imageer Endpoint API
  version: "0.1"
paths:
  /api/v1/greetings/{name}:
    get:
      consumes:
      - application/json
      description: Greeting by given name
      parameters:
      - description: name for greeting
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/http.getGreetingRes'
        "400":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
        "500":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
      summary: Say greeting
      tags:
      - Greeting
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: Get an user by header or cookie
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/http.getUserRes'
        "400":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
        "500":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
      summary: Get an authenticated user
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Create a user with basic information
      parameters:
      - description: request to create a new user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.createUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/http.createUserRes'
        "400":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
        "500":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
      summary: Create a user
      tags:
      - User
  /api/v1/users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user with given id
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/http.getUserRes'
        "400":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
        "500":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
      summary: Get a user
      tags:
      - User
  /signIn:
    post:
      consumes:
      - application/json
      description: Sign in using email and password
      parameters:
      - description: request to sign in
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.signInReq'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/http.signInRes'
        "400":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
        "500":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
      summary: Sign in
      tags:
      - Authentication
  /signTest:
    get:
      consumes:
      - application/json
      description: Sign in test using authorization header or cookie
      parameters:
      - description: bearer authorization
        in: header
        name: Authorization
        type: string
        x-example: Bearer your_jwt_token
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
        "500":
          description: error
          schema:
            $ref: '#/definitions/http.errorRes'
      summary: Sign in test
      tags:
      - Authentication
swagger: "2.0"
