// Package gateway provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package gateway

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/isutare412/imageer/pkg/images"
	"github.com/isutare412/imageer/pkg/serviceaccounts"
	"github.com/isutare412/imageer/pkg/users"
	"github.com/oapi-codegen/runtime"
)

// AppError defines model for AppError.
type AppError struct {
	// CodeID Error code ID for programmatic handling
	CodeID int64 `json:"codeId"`

	// CodeName Error code name for programmatic handling
	CodeName string `json:"codeName"`

	// Message Error message
	Message string `json:"message"`
}

// CreatePresignedURLRequest defines model for CreatePresignedUrlRequest.
type CreatePresignedURLRequest struct {
	// ContentType The content type of the image.
	ContentType ImageContentType `json:"contentType"`

	// FileName The name of the file to be uploaded.
	FileName string `json:"fileName"`

	// TransformationNames List of transformation names to apply to the image. If not provided, default transformations will be applied.
	TransformationNames []string `json:"transformationNames,omitempty"`
}

// CreateProjectAdminRequest defines model for CreateProjectAdminRequest.
type CreateProjectAdminRequest struct {
	// Name The name of the project.
	Name string `json:"name"`
}

// CreateServiceAccountAdminRequest defines model for CreateServiceAccountAdminRequest.
type CreateServiceAccountAdminRequest struct {
	// AccessScope The access scope of the service account.
	AccessScope ServiceAccountAccessScope `json:"accessScope"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// Name The name of the service account.
	Name string `json:"name"`

	// ProjectIDs List of project IDs to associate with the service account.
	ProjectIDs []string `json:"projectIds,omitempty"`
}

// CreateTransformationRequest defines model for CreateTransformationRequest.
type CreateTransformationRequest struct {
	// Default Indicates if this transformation is the default one.
	Default bool `json:"default"`

	// Height The height of the image in pixels.
	Height int64 `json:"height"`

	// Name The name of the transformation.
	Name string `json:"name"`

	// Width The width of the image in pixels.
	Width int64 `json:"width"`
}

// DeleteTransformationRequest defines model for DeleteTransformationRequest.
type DeleteTransformationRequest struct {
	// ID The unique identifier of the transformation.
	ID string `json:"id"`
}

// Image defines model for Image.
type Image struct {
	// CreatedAt The creation time of the image.
	CreatedAt time.Time `json:"createdAt"`

	// ID The unique identifier of the image.
	ID string `json:"id"`

	// State The current state of the image.
	State ImageState `json:"state"`

	// UpdatedAt The last update time of the image.
	UpdatedAt time.Time `json:"updatedAt"`

	// URLSet URLs for accessing the image and its variants.
	URLSet ImageURLSet `json:"urlSet"`
}

// ImageContentType The content type of the image.
type ImageContentType = images.ContentType

// ImageState The current state of the image.
type ImageState = images.State

// ImageURLSet URLs for accessing the image and its variants.
type ImageURLSet struct {
	// OriginalURL The original URL of the image.
	OriginalURL string `json:"originalUrl"`

	// Transformations List of URLs for the image with applied transformations.
	Transformations []VariantURL `json:"transformations"`
}

// Images defines model for Images.
type Images struct {
	Items []Image `json:"items"`

	// Total The total number of images.
	Total int64 `json:"total"`
}

// PresignedURL defines model for PresignedUrl.
type PresignedURL struct {
	// ExpiresAt The expiration time of the presigned URL.
	ExpiresAt time.Time `json:"expiresAt"`

	// ImageID The unique identifier of the image.
	ImageID string `json:"imageId"`

	// UploadURL The presigned URL for uploading the image. Check https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html for more details.
	UploadURL string `json:"uploadUrl"`
}

// Project defines model for Project.
type Project struct {
	// CreatedAt The creation time of the project.
	CreatedAt time.Time `json:"createdAt"`

	// ID The unique identifier of the project.
	ID string `json:"id"`

	// Name The name of the project.
	Name string `json:"name"`

	// Transformations List of transformations to apply to the project.
	Transformations []Transformation `json:"transformations"`

	// UpdatedAt The last update time of the project.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ProjectReference defines model for ProjectReference.
type ProjectReference struct {
	// ID The unique identifier of the project.
	ID string `json:"id"`

	// Name The name of the project.
	Name string `json:"name"`
}

// Projects defines model for Projects.
type Projects struct {
	Items []Project `json:"items"`

	// Total The total number of projects.
	Total int64 `json:"total"`
}

// ReprocessImagesAdminRequest defines model for ReprocessImagesAdminRequest.
type ReprocessImagesAdminRequest struct {
	// ImageIDs List of image IDs to reprocess. If not provided and reprocessAll is true, all images in the project will be reprocessed.
	ImageIDs []string `json:"imageIds,omitempty"`

	// ReprocessAll If true, reprocess all images in the project. Takes precedence over imageIds.
	ReprocessAll bool `json:"reprocessAll,omitempty"`
}

// ServiceAccount defines model for ServiceAccount.
type ServiceAccount struct {
	// AccessScope The access scope of the service account.
	AccessScope ServiceAccountAccessScope `json:"accessScope"`

	// APIKey The API key for the service account.
	APIKey string `json:"apiKey"`

	// CreatedAt The creation time of the service account.
	CreatedAt time.Time `json:"createdAt"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// ID The unique identifier of the service account.
	ID string `json:"id"`

	// Name The name of the service account.
	Name string `json:"name"`

	// Projects List of projects associated with the service account.
	Projects []ProjectReference `json:"projects"`

	// UpdatedAt The last update time of the service account.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ServiceAccountAccessScope The access scope of the service account.
type ServiceAccountAccessScope = serviceaccounts.AccessScope

// ServiceAccounts defines model for ServiceAccounts.
type ServiceAccounts struct {
	Items []ServiceAccount `json:"items"`

	// Total The total number of service accounts.
	Total int64 `json:"total"`
}

// Transformation defines model for Transformation.
type Transformation struct {
	// CreatedAt The creation time of the transformation.
	CreatedAt time.Time `json:"createdAt"`

	// Default Indicates if this transformation is the default one.
	Default bool `json:"default"`

	// Height The height of the image in pixels.
	Height int64 `json:"height"`

	// ID The unique identifier of the transformation.
	ID string `json:"id"`

	// Name The name of the transformation.
	Name string `json:"name"`

	// UpdatedAt The last update time of the transformation.
	UpdatedAt time.Time `json:"updatedAt"`

	// Width The width of the image in pixels.
	Width int64 `json:"width"`
}

// UpdateProjectAdminRequest defines model for UpdateProjectAdminRequest.
type UpdateProjectAdminRequest struct {
	// Name The name of the project.
	Name            *string `json:"name,omitempty"`
	Transformations struct {
		// Add List of transformations to add to the project.
		Add []CreateTransformationRequest `json:"add,omitempty"`

		// Modify List of transformations to modify in the project.
		Modify []UpdateTransformationRequest `json:"modify,omitempty"`

		// Remove List of transformations to remove from the project.
		Remove []DeleteTransformationRequest `json:"remove,omitempty"`
	} `json:"transformations,omitempty"`
}

// UpdateServiceAccountAdminRequest defines model for UpdateServiceAccountAdminRequest.
type UpdateServiceAccountAdminRequest struct {
	// AccessScope The access scope of the service account.
	AccessScope *ServiceAccountAccessScope `json:"accessScope,omitempty"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// Name The name of the service account.
	Name *string `json:"name,omitempty"`

	// ProjectIDs List of project IDs to associate with the service account.
	ProjectIDs []string `json:"projectIds,omitempty"`
}

// UpdateTransformationRequest defines model for UpdateTransformationRequest.
type UpdateTransformationRequest struct {
	// Default Indicates if this transformation is the default one.
	Default *bool `json:"default,omitempty"`

	// Height The height of the image in pixels.
	Height *int64 `json:"height,omitempty"`

	// ID The unique identifier of the transformation.
	ID string `json:"id"`

	// Name The name of the transformation.
	Name *string `json:"name,omitempty"`

	// Width The width of the image in pixels.
	Width *int64 `json:"width,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt The creation time of the user.
	CreatedAt time.Time `json:"createdAt"`

	// Email The email address of the user.
	Email string `json:"email"`

	// ID The unique identifier of the user.
	ID string `json:"id"`

	// Nickname The nickname of the user.
	Nickname string `json:"nickname"`

	// PhotoURL The photo URL of the user.
	PhotoURL string `json:"photoUrl"`

	// Role The role of the user.
	Role UserRole `json:"role"`

	// UpdatedAt The last update time of the user.
	UpdatedAt time.Time `json:"updatedAt"`
}

// UserRole The role of the user.
type UserRole = users.Role

// VariantURL defines model for VariantUrl.
type VariantURL struct {
	// TransformationID The unique identifier of the transformation.
	TransformationID string `json:"transformationId"`

	// TransformationName The name of the transformation.
	TransformationName string `json:"transformationName"`

	// URL The URL of the image with the applied transformation.
	URL string `json:"url"`
}

// ImageIDPath defines model for ImageIdPath.
type ImageIDPath = string

// LimitQuery defines model for LimitQuery.
type LimitQuery = int64

// OffsetQuery defines model for OffsetQuery.
type OffsetQuery = int64

// ProjectIDPath defines model for ProjectIdPath.
type ProjectIDPath = string

// ServiceAccountIDPath defines model for ServiceAccountIdPath.
type ServiceAccountIDPath = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = AppError

// ListProjectsAdminParams defines parameters for ListProjectsAdmin.
type ListProjectsAdminParams struct {
	// Offset Offset for pagination
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Limit for pagination
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListServiceAccountsAdminParams defines parameters for ListServiceAccountsAdmin.
type ListServiceAccountsAdminParams struct {
	// Offset Offset for pagination
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Limit for pagination
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`
}

// FinishGoogleSignInParams defines parameters for FinishGoogleSignIn.
type FinishGoogleSignInParams struct {
	// Code The authorization code returned by Google after sign-in.
	Code string `form:"code" json:"code"`

	// State The state parameter to prevent CSRF attacks.
	State string `form:"state" json:"state"`
}

// CreateProjectAdminJSONRequestBody defines body for CreateProjectAdmin for application/json ContentType.
type CreateProjectAdminJSONRequestBody = CreateProjectAdminRequest

// UpdateProjectAdminJSONRequestBody defines body for UpdateProjectAdmin for application/json ContentType.
type UpdateProjectAdminJSONRequestBody = UpdateProjectAdminRequest

// ReprocessImagesAdminJSONRequestBody defines body for ReprocessImagesAdmin for application/json ContentType.
type ReprocessImagesAdminJSONRequestBody = ReprocessImagesAdminRequest

// CreateServiceAccountAdminJSONRequestBody defines body for CreateServiceAccountAdmin for application/json ContentType.
type CreateServiceAccountAdminJSONRequestBody = CreateServiceAccountAdminRequest

// UpdateServiceAccountAdminJSONRequestBody defines body for UpdateServiceAccountAdmin for application/json ContentType.
type UpdateServiceAccountAdminJSONRequestBody = UpdateServiceAccountAdminRequest

// CreateUploadURLJSONRequestBody defines body for CreateUploadURL for application/json ContentType.
type CreateUploadURLJSONRequestBody = CreatePresignedURLRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListProjectsAdmin request
	ListProjectsAdmin(ctx context.Context, params *ListProjectsAdminParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateProjectAdminWithBody request with any body
	CreateProjectAdminWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateProjectAdmin(ctx context.Context, body CreateProjectAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProjectAdmin request
	GetProjectAdmin(ctx context.Context, projectID ProjectIDPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateProjectAdminWithBody request with any body
	UpdateProjectAdminWithBody(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateProjectAdmin(ctx context.Context, projectID ProjectIDPath, body UpdateProjectAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReprocessImagesAdminWithBody request with any body
	ReprocessImagesAdminWithBody(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ReprocessImagesAdmin(ctx context.Context, projectID ProjectIDPath, body ReprocessImagesAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListServiceAccountsAdmin request
	ListServiceAccountsAdmin(ctx context.Context, params *ListServiceAccountsAdminParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateServiceAccountAdminWithBody request with any body
	CreateServiceAccountAdminWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateServiceAccountAdmin(ctx context.Context, body CreateServiceAccountAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteServiceAccountAdmin request
	DeleteServiceAccountAdmin(ctx context.Context, serviceAccountID ServiceAccountIDPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetServiceAccountAdmin request
	GetServiceAccountAdmin(ctx context.Context, serviceAccountID ServiceAccountIDPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateServiceAccountAdminWithBody request with any body
	UpdateServiceAccountAdminWithBody(ctx context.Context, serviceAccountID ServiceAccountIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateServiceAccountAdmin(ctx context.Context, serviceAccountID ServiceAccountIDPath, body UpdateServiceAccountAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartGoogleSignIn request
	StartGoogleSignIn(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// FinishGoogleSignIn request
	FinishGoogleSignIn(ctx context.Context, params *FinishGoogleSignInParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProject request
	GetProject(ctx context.Context, projectID ProjectIDPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateUploadURLWithBody request with any body
	CreateUploadURLWithBody(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateUploadURL(ctx context.Context, projectID ProjectIDPath, body CreateUploadURLJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetImage request
	GetImage(ctx context.Context, projectID ProjectIDPath, imageID ImageIDPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCurrentUser request
	GetCurrentUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListProjectsAdmin(ctx context.Context, params *ListProjectsAdminParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListProjectsAdminRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProjectAdminWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProjectAdminRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProjectAdmin(ctx context.Context, body CreateProjectAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProjectAdminRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProjectAdmin(ctx context.Context, projectID ProjectIDPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProjectAdminRequest(c.Server, projectID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProjectAdminWithBody(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProjectAdminRequestWithBody(c.Server, projectID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateProjectAdmin(ctx context.Context, projectID ProjectIDPath, body UpdateProjectAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateProjectAdminRequest(c.Server, projectID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReprocessImagesAdminWithBody(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReprocessImagesAdminRequestWithBody(c.Server, projectID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReprocessImagesAdmin(ctx context.Context, projectID ProjectIDPath, body ReprocessImagesAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReprocessImagesAdminRequest(c.Server, projectID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListServiceAccountsAdmin(ctx context.Context, params *ListServiceAccountsAdminParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListServiceAccountsAdminRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateServiceAccountAdminWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateServiceAccountAdminRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateServiceAccountAdmin(ctx context.Context, body CreateServiceAccountAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateServiceAccountAdminRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteServiceAccountAdmin(ctx context.Context, serviceAccountID ServiceAccountIDPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteServiceAccountAdminRequest(c.Server, serviceAccountID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetServiceAccountAdmin(ctx context.Context, serviceAccountID ServiceAccountIDPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetServiceAccountAdminRequest(c.Server, serviceAccountID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateServiceAccountAdminWithBody(ctx context.Context, serviceAccountID ServiceAccountIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateServiceAccountAdminRequestWithBody(c.Server, serviceAccountID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateServiceAccountAdmin(ctx context.Context, serviceAccountID ServiceAccountIDPath, body UpdateServiceAccountAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateServiceAccountAdminRequest(c.Server, serviceAccountID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartGoogleSignIn(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartGoogleSignInRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) FinishGoogleSignIn(ctx context.Context, params *FinishGoogleSignInParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewFinishGoogleSignInRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProject(ctx context.Context, projectID ProjectIDPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProjectRequest(c.Server, projectID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUploadURLWithBody(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUploadURLRequestWithBody(c.Server, projectID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateUploadURL(ctx context.Context, projectID ProjectIDPath, body CreateUploadURLJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateUploadURLRequest(c.Server, projectID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetImage(ctx context.Context, projectID ProjectIDPath, imageID ImageIDPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetImageRequest(c.Server, projectID, imageID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCurrentUser(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCurrentUserRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListProjectsAdminRequest generates requests for ListProjectsAdmin
func NewListProjectsAdminRequest(server string, params *ListProjectsAdminParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/projects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateProjectAdminRequest calls the generic CreateProjectAdmin builder with application/json body
func NewCreateProjectAdminRequest(server string, body CreateProjectAdminJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateProjectAdminRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateProjectAdminRequestWithBody generates requests for CreateProjectAdmin with any type of body
func NewCreateProjectAdminRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/projects")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetProjectAdminRequest generates requests for GetProjectAdmin
func NewGetProjectAdminRequest(server string, projectID ProjectIDPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/projects/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateProjectAdminRequest calls the generic UpdateProjectAdmin builder with application/json body
func NewUpdateProjectAdminRequest(server string, projectID ProjectIDPath, body UpdateProjectAdminJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateProjectAdminRequestWithBody(server, projectID, "application/json", bodyReader)
}

// NewUpdateProjectAdminRequestWithBody generates requests for UpdateProjectAdmin with any type of body
func NewUpdateProjectAdminRequestWithBody(server string, projectID ProjectIDPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/projects/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReprocessImagesAdminRequest calls the generic ReprocessImagesAdmin builder with application/json body
func NewReprocessImagesAdminRequest(server string, projectID ProjectIDPath, body ReprocessImagesAdminJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReprocessImagesAdminRequestWithBody(server, projectID, "application/json", bodyReader)
}

// NewReprocessImagesAdminRequestWithBody generates requests for ReprocessImagesAdmin with any type of body
func NewReprocessImagesAdminRequestWithBody(server string, projectID ProjectIDPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/projects/%s/images/reprocess", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListServiceAccountsAdminRequest generates requests for ListServiceAccountsAdmin
func NewListServiceAccountsAdminRequest(server string, params *ListServiceAccountsAdminParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/service-accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateServiceAccountAdminRequest calls the generic CreateServiceAccountAdmin builder with application/json body
func NewCreateServiceAccountAdminRequest(server string, body CreateServiceAccountAdminJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateServiceAccountAdminRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateServiceAccountAdminRequestWithBody generates requests for CreateServiceAccountAdmin with any type of body
func NewCreateServiceAccountAdminRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/service-accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteServiceAccountAdminRequest generates requests for DeleteServiceAccountAdmin
func NewDeleteServiceAccountAdminRequest(server string, serviceAccountID ServiceAccountIDPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "serviceAccountId", runtime.ParamLocationPath, serviceAccountID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/service-accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetServiceAccountAdminRequest generates requests for GetServiceAccountAdmin
func NewGetServiceAccountAdminRequest(server string, serviceAccountID ServiceAccountIDPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "serviceAccountId", runtime.ParamLocationPath, serviceAccountID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/service-accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateServiceAccountAdminRequest calls the generic UpdateServiceAccountAdmin builder with application/json body
func NewUpdateServiceAccountAdminRequest(server string, serviceAccountID ServiceAccountIDPath, body UpdateServiceAccountAdminJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateServiceAccountAdminRequestWithBody(server, serviceAccountID, "application/json", bodyReader)
}

// NewUpdateServiceAccountAdminRequestWithBody generates requests for UpdateServiceAccountAdmin with any type of body
func NewUpdateServiceAccountAdminRequestWithBody(server string, serviceAccountID ServiceAccountIDPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "serviceAccountId", runtime.ParamLocationPath, serviceAccountID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/admin/service-accounts/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStartGoogleSignInRequest generates requests for StartGoogleSignIn
func NewStartGoogleSignInRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/google/sign-in")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewFinishGoogleSignInRequest generates requests for FinishGoogleSignIn
func NewFinishGoogleSignInRequest(server string, params *FinishGoogleSignInParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/auth/google/sign-in/callback")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "code", runtime.ParamLocationQuery, params.Code); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "state", runtime.ParamLocationQuery, params.State); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProjectRequest generates requests for GetProject
func NewGetProjectRequest(server string, projectID ProjectIDPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/projects/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateUploadURLRequest calls the generic CreateUploadURL builder with application/json body
func NewCreateUploadURLRequest(server string, projectID ProjectIDPath, body CreateUploadURLJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateUploadURLRequestWithBody(server, projectID, "application/json", bodyReader)
}

// NewCreateUploadURLRequestWithBody generates requests for CreateUploadURL with any type of body
func NewCreateUploadURLRequestWithBody(server string, projectID ProjectIDPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/projects/%s/images/presigned-url", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetImageRequest generates requests for GetImage
func NewGetImageRequest(server string, projectID ProjectIDPath, imageID ImageIDPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectId", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "imageId", runtime.ParamLocationPath, imageID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/projects/%s/images/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCurrentUserRequest generates requests for GetCurrentUser
func NewGetCurrentUserRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/users/me")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListProjectsAdminWithResponse request
	ListProjectsAdminWithResponse(ctx context.Context, params *ListProjectsAdminParams, reqEditors ...RequestEditorFn) (*ListProjectsAdminResponse, error)

	// CreateProjectAdminWithBodyWithResponse request with any body
	CreateProjectAdminWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProjectAdminResponse, error)

	CreateProjectAdminWithResponse(ctx context.Context, body CreateProjectAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProjectAdminResponse, error)

	// GetProjectAdminWithResponse request
	GetProjectAdminWithResponse(ctx context.Context, projectID ProjectIDPath, reqEditors ...RequestEditorFn) (*GetProjectAdminResponse, error)

	// UpdateProjectAdminWithBodyWithResponse request with any body
	UpdateProjectAdminWithBodyWithResponse(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProjectAdminResponse, error)

	UpdateProjectAdminWithResponse(ctx context.Context, projectID ProjectIDPath, body UpdateProjectAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProjectAdminResponse, error)

	// ReprocessImagesAdminWithBodyWithResponse request with any body
	ReprocessImagesAdminWithBodyWithResponse(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReprocessImagesAdminResponse, error)

	ReprocessImagesAdminWithResponse(ctx context.Context, projectID ProjectIDPath, body ReprocessImagesAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*ReprocessImagesAdminResponse, error)

	// ListServiceAccountsAdminWithResponse request
	ListServiceAccountsAdminWithResponse(ctx context.Context, params *ListServiceAccountsAdminParams, reqEditors ...RequestEditorFn) (*ListServiceAccountsAdminResponse, error)

	// CreateServiceAccountAdminWithBodyWithResponse request with any body
	CreateServiceAccountAdminWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateServiceAccountAdminResponse, error)

	CreateServiceAccountAdminWithResponse(ctx context.Context, body CreateServiceAccountAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateServiceAccountAdminResponse, error)

	// DeleteServiceAccountAdminWithResponse request
	DeleteServiceAccountAdminWithResponse(ctx context.Context, serviceAccountID ServiceAccountIDPath, reqEditors ...RequestEditorFn) (*DeleteServiceAccountAdminResponse, error)

	// GetServiceAccountAdminWithResponse request
	GetServiceAccountAdminWithResponse(ctx context.Context, serviceAccountID ServiceAccountIDPath, reqEditors ...RequestEditorFn) (*GetServiceAccountAdminResponse, error)

	// UpdateServiceAccountAdminWithBodyWithResponse request with any body
	UpdateServiceAccountAdminWithBodyWithResponse(ctx context.Context, serviceAccountID ServiceAccountIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateServiceAccountAdminResponse, error)

	UpdateServiceAccountAdminWithResponse(ctx context.Context, serviceAccountID ServiceAccountIDPath, body UpdateServiceAccountAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateServiceAccountAdminResponse, error)

	// StartGoogleSignInWithResponse request
	StartGoogleSignInWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StartGoogleSignInResponse, error)

	// FinishGoogleSignInWithResponse request
	FinishGoogleSignInWithResponse(ctx context.Context, params *FinishGoogleSignInParams, reqEditors ...RequestEditorFn) (*FinishGoogleSignInResponse, error)

	// GetProjectWithResponse request
	GetProjectWithResponse(ctx context.Context, projectID ProjectIDPath, reqEditors ...RequestEditorFn) (*GetProjectResponse, error)

	// CreateUploadURLWithBodyWithResponse request with any body
	CreateUploadURLWithBodyWithResponse(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadURLResponse, error)

	CreateUploadURLWithResponse(ctx context.Context, projectID ProjectIDPath, body CreateUploadURLJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUploadURLResponse, error)

	// GetImageWithResponse request
	GetImageWithResponse(ctx context.Context, projectID ProjectIDPath, imageID ImageIDPath, reqEditors ...RequestEditorFn) (*GetImageResponse, error)

	// GetCurrentUserWithResponse request
	GetCurrentUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentUserResponse, error)
}

type ListProjectsAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Projects
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListProjectsAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListProjectsAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateProjectAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Project
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateProjectAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateProjectAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProjectAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Project
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetProjectAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProjectAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateProjectAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Project
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateProjectAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateProjectAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ReprocessImagesAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Images
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ReprocessImagesAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReprocessImagesAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListServiceAccountsAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ServiceAccounts
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListServiceAccountsAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListServiceAccountsAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateServiceAccountAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ServiceAccount
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateServiceAccountAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateServiceAccountAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteServiceAccountAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteServiceAccountAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteServiceAccountAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetServiceAccountAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ServiceAccount
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetServiceAccountAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetServiceAccountAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateServiceAccountAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ServiceAccount
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r UpdateServiceAccountAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateServiceAccountAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartGoogleSignInResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r StartGoogleSignInResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartGoogleSignInResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type FinishGoogleSignInResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r FinishGoogleSignInResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r FinishGoogleSignInResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Project
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetProjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateUploadURLResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PresignedURL
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreateUploadURLResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateUploadURLResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetImageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Image
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetImageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetImageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCurrentUserResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *User
	JSONDefault  *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetCurrentUserResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCurrentUserResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListProjectsAdminWithResponse request returning *ListProjectsAdminResponse
func (c *ClientWithResponses) ListProjectsAdminWithResponse(ctx context.Context, params *ListProjectsAdminParams, reqEditors ...RequestEditorFn) (*ListProjectsAdminResponse, error) {
	rsp, err := c.ListProjectsAdmin(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListProjectsAdminResponse(rsp)
}

// CreateProjectAdminWithBodyWithResponse request with arbitrary body returning *CreateProjectAdminResponse
func (c *ClientWithResponses) CreateProjectAdminWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProjectAdminResponse, error) {
	rsp, err := c.CreateProjectAdminWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProjectAdminResponse(rsp)
}

func (c *ClientWithResponses) CreateProjectAdminWithResponse(ctx context.Context, body CreateProjectAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProjectAdminResponse, error) {
	rsp, err := c.CreateProjectAdmin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProjectAdminResponse(rsp)
}

// GetProjectAdminWithResponse request returning *GetProjectAdminResponse
func (c *ClientWithResponses) GetProjectAdminWithResponse(ctx context.Context, projectID ProjectIDPath, reqEditors ...RequestEditorFn) (*GetProjectAdminResponse, error) {
	rsp, err := c.GetProjectAdmin(ctx, projectID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProjectAdminResponse(rsp)
}

// UpdateProjectAdminWithBodyWithResponse request with arbitrary body returning *UpdateProjectAdminResponse
func (c *ClientWithResponses) UpdateProjectAdminWithBodyWithResponse(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateProjectAdminResponse, error) {
	rsp, err := c.UpdateProjectAdminWithBody(ctx, projectID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProjectAdminResponse(rsp)
}

func (c *ClientWithResponses) UpdateProjectAdminWithResponse(ctx context.Context, projectID ProjectIDPath, body UpdateProjectAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateProjectAdminResponse, error) {
	rsp, err := c.UpdateProjectAdmin(ctx, projectID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateProjectAdminResponse(rsp)
}

// ReprocessImagesAdminWithBodyWithResponse request with arbitrary body returning *ReprocessImagesAdminResponse
func (c *ClientWithResponses) ReprocessImagesAdminWithBodyWithResponse(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ReprocessImagesAdminResponse, error) {
	rsp, err := c.ReprocessImagesAdminWithBody(ctx, projectID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReprocessImagesAdminResponse(rsp)
}

func (c *ClientWithResponses) ReprocessImagesAdminWithResponse(ctx context.Context, projectID ProjectIDPath, body ReprocessImagesAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*ReprocessImagesAdminResponse, error) {
	rsp, err := c.ReprocessImagesAdmin(ctx, projectID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReprocessImagesAdminResponse(rsp)
}

// ListServiceAccountsAdminWithResponse request returning *ListServiceAccountsAdminResponse
func (c *ClientWithResponses) ListServiceAccountsAdminWithResponse(ctx context.Context, params *ListServiceAccountsAdminParams, reqEditors ...RequestEditorFn) (*ListServiceAccountsAdminResponse, error) {
	rsp, err := c.ListServiceAccountsAdmin(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListServiceAccountsAdminResponse(rsp)
}

// CreateServiceAccountAdminWithBodyWithResponse request with arbitrary body returning *CreateServiceAccountAdminResponse
func (c *ClientWithResponses) CreateServiceAccountAdminWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateServiceAccountAdminResponse, error) {
	rsp, err := c.CreateServiceAccountAdminWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateServiceAccountAdminResponse(rsp)
}

func (c *ClientWithResponses) CreateServiceAccountAdminWithResponse(ctx context.Context, body CreateServiceAccountAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateServiceAccountAdminResponse, error) {
	rsp, err := c.CreateServiceAccountAdmin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateServiceAccountAdminResponse(rsp)
}

// DeleteServiceAccountAdminWithResponse request returning *DeleteServiceAccountAdminResponse
func (c *ClientWithResponses) DeleteServiceAccountAdminWithResponse(ctx context.Context, serviceAccountID ServiceAccountIDPath, reqEditors ...RequestEditorFn) (*DeleteServiceAccountAdminResponse, error) {
	rsp, err := c.DeleteServiceAccountAdmin(ctx, serviceAccountID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteServiceAccountAdminResponse(rsp)
}

// GetServiceAccountAdminWithResponse request returning *GetServiceAccountAdminResponse
func (c *ClientWithResponses) GetServiceAccountAdminWithResponse(ctx context.Context, serviceAccountID ServiceAccountIDPath, reqEditors ...RequestEditorFn) (*GetServiceAccountAdminResponse, error) {
	rsp, err := c.GetServiceAccountAdmin(ctx, serviceAccountID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetServiceAccountAdminResponse(rsp)
}

// UpdateServiceAccountAdminWithBodyWithResponse request with arbitrary body returning *UpdateServiceAccountAdminResponse
func (c *ClientWithResponses) UpdateServiceAccountAdminWithBodyWithResponse(ctx context.Context, serviceAccountID ServiceAccountIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateServiceAccountAdminResponse, error) {
	rsp, err := c.UpdateServiceAccountAdminWithBody(ctx, serviceAccountID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateServiceAccountAdminResponse(rsp)
}

func (c *ClientWithResponses) UpdateServiceAccountAdminWithResponse(ctx context.Context, serviceAccountID ServiceAccountIDPath, body UpdateServiceAccountAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateServiceAccountAdminResponse, error) {
	rsp, err := c.UpdateServiceAccountAdmin(ctx, serviceAccountID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateServiceAccountAdminResponse(rsp)
}

// StartGoogleSignInWithResponse request returning *StartGoogleSignInResponse
func (c *ClientWithResponses) StartGoogleSignInWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*StartGoogleSignInResponse, error) {
	rsp, err := c.StartGoogleSignIn(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartGoogleSignInResponse(rsp)
}

// FinishGoogleSignInWithResponse request returning *FinishGoogleSignInResponse
func (c *ClientWithResponses) FinishGoogleSignInWithResponse(ctx context.Context, params *FinishGoogleSignInParams, reqEditors ...RequestEditorFn) (*FinishGoogleSignInResponse, error) {
	rsp, err := c.FinishGoogleSignIn(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseFinishGoogleSignInResponse(rsp)
}

// GetProjectWithResponse request returning *GetProjectResponse
func (c *ClientWithResponses) GetProjectWithResponse(ctx context.Context, projectID ProjectIDPath, reqEditors ...RequestEditorFn) (*GetProjectResponse, error) {
	rsp, err := c.GetProject(ctx, projectID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProjectResponse(rsp)
}

// CreateUploadURLWithBodyWithResponse request with arbitrary body returning *CreateUploadURLResponse
func (c *ClientWithResponses) CreateUploadURLWithBodyWithResponse(ctx context.Context, projectID ProjectIDPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateUploadURLResponse, error) {
	rsp, err := c.CreateUploadURLWithBody(ctx, projectID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUploadURLResponse(rsp)
}

func (c *ClientWithResponses) CreateUploadURLWithResponse(ctx context.Context, projectID ProjectIDPath, body CreateUploadURLJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateUploadURLResponse, error) {
	rsp, err := c.CreateUploadURL(ctx, projectID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateUploadURLResponse(rsp)
}

// GetImageWithResponse request returning *GetImageResponse
func (c *ClientWithResponses) GetImageWithResponse(ctx context.Context, projectID ProjectIDPath, imageID ImageIDPath, reqEditors ...RequestEditorFn) (*GetImageResponse, error) {
	rsp, err := c.GetImage(ctx, projectID, imageID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetImageResponse(rsp)
}

// GetCurrentUserWithResponse request returning *GetCurrentUserResponse
func (c *ClientWithResponses) GetCurrentUserWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetCurrentUserResponse, error) {
	rsp, err := c.GetCurrentUser(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCurrentUserResponse(rsp)
}

// ParseListProjectsAdminResponse parses an HTTP response from a ListProjectsAdminWithResponse call
func ParseListProjectsAdminResponse(rsp *http.Response) (*ListProjectsAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListProjectsAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Projects
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateProjectAdminResponse parses an HTTP response from a CreateProjectAdminWithResponse call
func ParseCreateProjectAdminResponse(rsp *http.Response) (*CreateProjectAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateProjectAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Project
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetProjectAdminResponse parses an HTTP response from a GetProjectAdminWithResponse call
func ParseGetProjectAdminResponse(rsp *http.Response) (*GetProjectAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProjectAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Project
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateProjectAdminResponse parses an HTTP response from a UpdateProjectAdminWithResponse call
func ParseUpdateProjectAdminResponse(rsp *http.Response) (*UpdateProjectAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateProjectAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Project
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseReprocessImagesAdminResponse parses an HTTP response from a ReprocessImagesAdminWithResponse call
func ParseReprocessImagesAdminResponse(rsp *http.Response) (*ReprocessImagesAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReprocessImagesAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Images
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListServiceAccountsAdminResponse parses an HTTP response from a ListServiceAccountsAdminWithResponse call
func ParseListServiceAccountsAdminResponse(rsp *http.Response) (*ListServiceAccountsAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListServiceAccountsAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServiceAccounts
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateServiceAccountAdminResponse parses an HTTP response from a CreateServiceAccountAdminWithResponse call
func ParseCreateServiceAccountAdminResponse(rsp *http.Response) (*CreateServiceAccountAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateServiceAccountAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServiceAccount
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteServiceAccountAdminResponse parses an HTTP response from a DeleteServiceAccountAdminWithResponse call
func ParseDeleteServiceAccountAdminResponse(rsp *http.Response) (*DeleteServiceAccountAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteServiceAccountAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetServiceAccountAdminResponse parses an HTTP response from a GetServiceAccountAdminWithResponse call
func ParseGetServiceAccountAdminResponse(rsp *http.Response) (*GetServiceAccountAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetServiceAccountAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServiceAccount
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateServiceAccountAdminResponse parses an HTTP response from a UpdateServiceAccountAdminWithResponse call
func ParseUpdateServiceAccountAdminResponse(rsp *http.Response) (*UpdateServiceAccountAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateServiceAccountAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServiceAccount
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseStartGoogleSignInResponse parses an HTTP response from a StartGoogleSignInWithResponse call
func ParseStartGoogleSignInResponse(rsp *http.Response) (*StartGoogleSignInResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartGoogleSignInResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseFinishGoogleSignInResponse parses an HTTP response from a FinishGoogleSignInWithResponse call
func ParseFinishGoogleSignInResponse(rsp *http.Response) (*FinishGoogleSignInResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &FinishGoogleSignInResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetProjectResponse parses an HTTP response from a GetProjectWithResponse call
func ParseGetProjectResponse(rsp *http.Response) (*GetProjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Project
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateUploadURLResponse parses an HTTP response from a CreateUploadURLWithResponse call
func ParseCreateUploadURLResponse(rsp *http.Response) (*CreateUploadURLResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateUploadURLResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PresignedURL
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetImageResponse parses an HTTP response from a GetImageWithResponse call
func ParseGetImageResponse(rsp *http.Response) (*GetImageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetImageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Image
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetCurrentUserResponse parses an HTTP response from a GetCurrentUserWithResponse call
func ParseGetCurrentUserResponse(rsp *http.Response) (*GetCurrentUserResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCurrentUserResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest User
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
