// Code generated by "enumer -type=Code -trimprefix Code -output code_enum.go -transform snake-upper -text -json"; DO NOT EDIT.

package apperr

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _CodeName = "BAD_REQUESTUNAUTHORIZEDFORBIDDENNOT_FOUNDMETHOD_NOT_ALLOWEDNOT_ACCEPTABLECONFLICTGONEREQUEST_ENTITY_TOO_LARGETEAPOTUNPROCESSABLE_ENTITYTOO_MANY_REQUESTSINTERNAL_SERVER_ERRORNOT_IMPLEMENTEDSERVICE_UNAVAILABLE"
const _CodeLowerName = "bad_requestunauthorizedforbiddennot_foundmethod_not_allowednot_acceptableconflictgonerequest_entity_too_largeteapotunprocessable_entitytoo_many_requestsinternal_server_errornot_implementedservice_unavailable"

var _CodeMap = map[Code]string{
	1000:  _CodeName[0:11],
	2000:  _CodeName[11:23],
	3000:  _CodeName[23:32],
	4000:  _CodeName[32:41],
	5000:  _CodeName[41:59],
	6000:  _CodeName[59:73],
	7000:  _CodeName[73:81],
	8000:  _CodeName[81:85],
	9000:  _CodeName[85:109],
	10000: _CodeName[109:115],
	11000: _CodeName[115:135],
	12000: _CodeName[135:152],
	13000: _CodeName[152:173],
	14000: _CodeName[173:188],
	15000: _CodeName[188:207],
}

func (i Code) String() string {
	if str, ok := _CodeMap[i]; ok {
		return str
	}
	return fmt.Sprintf("Code(%d)", i)
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CodeNoOp() {
	var x [1]struct{}
	_ = x[CodeBadRequest-(1000)]
	_ = x[CodeUnauthorized-(2000)]
	_ = x[CodeForbidden-(3000)]
	_ = x[CodeNotFound-(4000)]
	_ = x[CodeMethodNotAllowed-(5000)]
	_ = x[CodeNotAcceptable-(6000)]
	_ = x[CodeConflict-(7000)]
	_ = x[CodeGone-(8000)]
	_ = x[CodeRequestEntityTooLarge-(9000)]
	_ = x[CodeTeapot-(10000)]
	_ = x[CodeUnprocessableEntity-(11000)]
	_ = x[CodeTooManyRequests-(12000)]
	_ = x[CodeInternalServerError-(13000)]
	_ = x[CodeNotImplemented-(14000)]
	_ = x[CodeServiceUnavailable-(15000)]
}

var _CodeValues = []Code{CodeBadRequest, CodeUnauthorized, CodeForbidden, CodeNotFound, CodeMethodNotAllowed, CodeNotAcceptable, CodeConflict, CodeGone, CodeRequestEntityTooLarge, CodeTeapot, CodeUnprocessableEntity, CodeTooManyRequests, CodeInternalServerError, CodeNotImplemented, CodeServiceUnavailable}

var _CodeNameToValueMap = map[string]Code{
	_CodeName[0:11]:         CodeBadRequest,
	_CodeLowerName[0:11]:    CodeBadRequest,
	_CodeName[11:23]:        CodeUnauthorized,
	_CodeLowerName[11:23]:   CodeUnauthorized,
	_CodeName[23:32]:        CodeForbidden,
	_CodeLowerName[23:32]:   CodeForbidden,
	_CodeName[32:41]:        CodeNotFound,
	_CodeLowerName[32:41]:   CodeNotFound,
	_CodeName[41:59]:        CodeMethodNotAllowed,
	_CodeLowerName[41:59]:   CodeMethodNotAllowed,
	_CodeName[59:73]:        CodeNotAcceptable,
	_CodeLowerName[59:73]:   CodeNotAcceptable,
	_CodeName[73:81]:        CodeConflict,
	_CodeLowerName[73:81]:   CodeConflict,
	_CodeName[81:85]:        CodeGone,
	_CodeLowerName[81:85]:   CodeGone,
	_CodeName[85:109]:       CodeRequestEntityTooLarge,
	_CodeLowerName[85:109]:  CodeRequestEntityTooLarge,
	_CodeName[109:115]:      CodeTeapot,
	_CodeLowerName[109:115]: CodeTeapot,
	_CodeName[115:135]:      CodeUnprocessableEntity,
	_CodeLowerName[115:135]: CodeUnprocessableEntity,
	_CodeName[135:152]:      CodeTooManyRequests,
	_CodeLowerName[135:152]: CodeTooManyRequests,
	_CodeName[152:173]:      CodeInternalServerError,
	_CodeLowerName[152:173]: CodeInternalServerError,
	_CodeName[173:188]:      CodeNotImplemented,
	_CodeLowerName[173:188]: CodeNotImplemented,
	_CodeName[188:207]:      CodeServiceUnavailable,
	_CodeLowerName[188:207]: CodeServiceUnavailable,
}

var _CodeNames = []string{
	_CodeName[0:11],
	_CodeName[11:23],
	_CodeName[23:32],
	_CodeName[32:41],
	_CodeName[41:59],
	_CodeName[59:73],
	_CodeName[73:81],
	_CodeName[81:85],
	_CodeName[85:109],
	_CodeName[109:115],
	_CodeName[115:135],
	_CodeName[135:152],
	_CodeName[152:173],
	_CodeName[173:188],
	_CodeName[188:207],
}

// CodeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CodeString(s string) (Code, error) {
	if val, ok := _CodeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CodeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Code values", s)
}

// CodeValues returns all values of the enum
func CodeValues() []Code {
	return _CodeValues
}

// CodeStrings returns a slice of all String values of the enum
func CodeStrings() []string {
	strs := make([]string, len(_CodeNames))
	copy(strs, _CodeNames)
	return strs
}

// IsACode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Code) IsACode() bool {
	_, ok := _CodeMap[i]
	return ok
}

// MarshalJSON implements the json.Marshaler interface for Code
func (i Code) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Code
func (i *Code) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Code should be a string, got %s", data)
	}

	var err error
	*i, err = CodeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Code
func (i Code) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Code
func (i *Code) UnmarshalText(text []byte) error {
	var err error
	*i, err = CodeString(string(text))
	return err
}
