// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: imageer/v1/image.proto

package imageerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageFormat int32

const (
	ImageFormat_IMAGE_FORMAT_UNSPECIFIED ImageFormat = 0
	ImageFormat_IMAGE_FORMAT_JPEG        ImageFormat = 1
	ImageFormat_IMAGE_FORMAT_PNG         ImageFormat = 2
	ImageFormat_IMAGE_FORMAT_WEBP        ImageFormat = 3
	ImageFormat_IMAGE_FORMAT_AVIF        ImageFormat = 4
	ImageFormat_IMAGE_FORMAT_HEIC        ImageFormat = 5
)

// Enum value maps for ImageFormat.
var (
	ImageFormat_name = map[int32]string{
		0: "IMAGE_FORMAT_UNSPECIFIED",
		1: "IMAGE_FORMAT_JPEG",
		2: "IMAGE_FORMAT_PNG",
		3: "IMAGE_FORMAT_WEBP",
		4: "IMAGE_FORMAT_AVIF",
		5: "IMAGE_FORMAT_HEIC",
	}
	ImageFormat_value = map[string]int32{
		"IMAGE_FORMAT_UNSPECIFIED": 0,
		"IMAGE_FORMAT_JPEG":        1,
		"IMAGE_FORMAT_PNG":         2,
		"IMAGE_FORMAT_WEBP":        3,
		"IMAGE_FORMAT_AVIF":        4,
		"IMAGE_FORMAT_HEIC":        5,
	}
)

func (x ImageFormat) Enum() *ImageFormat {
	p := new(ImageFormat)
	*p = x
	return p
}

func (x ImageFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_imageer_v1_image_proto_enumTypes[0].Descriptor()
}

func (ImageFormat) Type() protoreflect.EnumType {
	return &file_imageer_v1_image_proto_enumTypes[0]
}

func (x ImageFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageFormat.Descriptor instead.
func (ImageFormat) EnumDescriptor() ([]byte, []int) {
	return file_imageer_v1_image_proto_rawDescGZIP(), []int{0}
}

type ImageFit int32

const (
	ImageFit_IMAGE_FIT_UNSPECIFIED ImageFit = 0
	ImageFit_IMAGE_FIT_COVER       ImageFit = 1
	ImageFit_IMAGE_FIT_CONTAIN     ImageFit = 2
	ImageFit_IMAGE_FIT_FILL        ImageFit = 3
)

// Enum value maps for ImageFit.
var (
	ImageFit_name = map[int32]string{
		0: "IMAGE_FIT_UNSPECIFIED",
		1: "IMAGE_FIT_COVER",
		2: "IMAGE_FIT_CONTAIN",
		3: "IMAGE_FIT_FILL",
	}
	ImageFit_value = map[string]int32{
		"IMAGE_FIT_UNSPECIFIED": 0,
		"IMAGE_FIT_COVER":       1,
		"IMAGE_FIT_CONTAIN":     2,
		"IMAGE_FIT_FILL":        3,
	}
)

func (x ImageFit) Enum() *ImageFit {
	p := new(ImageFit)
	*p = x
	return p
}

func (x ImageFit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageFit) Descriptor() protoreflect.EnumDescriptor {
	return file_imageer_v1_image_proto_enumTypes[1].Descriptor()
}

func (ImageFit) Type() protoreflect.EnumType {
	return &file_imageer_v1_image_proto_enumTypes[1]
}

func (x ImageFit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageFit.Descriptor instead.
func (ImageFit) EnumDescriptor() ([]byte, []int) {
	return file_imageer_v1_image_proto_rawDescGZIP(), []int{1}
}

type ImageAnchor int32

const (
	ImageAnchor_IMAGE_ANCHOR_UNSPECIFIED ImageAnchor = 0
	ImageAnchor_IMAGE_ANCHOR_SMART       ImageAnchor = 1
	ImageAnchor_IMAGE_ANCHOR_CENTER      ImageAnchor = 2
	ImageAnchor_IMAGE_ANCHOR_NORTH       ImageAnchor = 3
	ImageAnchor_IMAGE_ANCHOR_SOUTH       ImageAnchor = 4
	ImageAnchor_IMAGE_ANCHOR_EAST        ImageAnchor = 5
	ImageAnchor_IMAGE_ANCHOR_WEST        ImageAnchor = 6
)

// Enum value maps for ImageAnchor.
var (
	ImageAnchor_name = map[int32]string{
		0: "IMAGE_ANCHOR_UNSPECIFIED",
		1: "IMAGE_ANCHOR_SMART",
		2: "IMAGE_ANCHOR_CENTER",
		3: "IMAGE_ANCHOR_NORTH",
		4: "IMAGE_ANCHOR_SOUTH",
		5: "IMAGE_ANCHOR_EAST",
		6: "IMAGE_ANCHOR_WEST",
	}
	ImageAnchor_value = map[string]int32{
		"IMAGE_ANCHOR_UNSPECIFIED": 0,
		"IMAGE_ANCHOR_SMART":       1,
		"IMAGE_ANCHOR_CENTER":      2,
		"IMAGE_ANCHOR_NORTH":       3,
		"IMAGE_ANCHOR_SOUTH":       4,
		"IMAGE_ANCHOR_EAST":        5,
		"IMAGE_ANCHOR_WEST":        6,
	}
)

func (x ImageAnchor) Enum() *ImageAnchor {
	p := new(ImageAnchor)
	*p = x
	return p
}

func (x ImageAnchor) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageAnchor) Descriptor() protoreflect.EnumDescriptor {
	return file_imageer_v1_image_proto_enumTypes[2].Descriptor()
}

func (ImageAnchor) Type() protoreflect.EnumType {
	return &file_imageer_v1_image_proto_enumTypes[2]
}

func (x ImageAnchor) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageAnchor.Descriptor instead.
func (ImageAnchor) EnumDescriptor() ([]byte, []int) {
	return file_imageer_v1_image_proto_rawDescGZIP(), []int{2}
}

type ImageState int32

const (
	ImageState_IMAGE_STATE_UNSPECIFIED    ImageState = 0
	ImageState_IMAGE_STATE_WAITING_UPLOAD ImageState = 1
	ImageState_IMAGE_STATE_FAILED         ImageState = 2
	ImageState_IMAGE_STATE_READY          ImageState = 3
)

// Enum value maps for ImageState.
var (
	ImageState_name = map[int32]string{
		0: "IMAGE_STATE_UNSPECIFIED",
		1: "IMAGE_STATE_WAITING_UPLOAD",
		2: "IMAGE_STATE_FAILED",
		3: "IMAGE_STATE_READY",
	}
	ImageState_value = map[string]int32{
		"IMAGE_STATE_UNSPECIFIED":    0,
		"IMAGE_STATE_WAITING_UPLOAD": 1,
		"IMAGE_STATE_FAILED":         2,
		"IMAGE_STATE_READY":          3,
	}
)

func (x ImageState) Enum() *ImageState {
	p := new(ImageState)
	*p = x
	return p
}

func (x ImageState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageState) Descriptor() protoreflect.EnumDescriptor {
	return file_imageer_v1_image_proto_enumTypes[3].Descriptor()
}

func (ImageState) Type() protoreflect.EnumType {
	return &file_imageer_v1_image_proto_enumTypes[3]
}

func (x ImageState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageState.Descriptor instead.
func (ImageState) EnumDescriptor() ([]byte, []int) {
	return file_imageer_v1_image_proto_rawDescGZIP(), []int{3}
}

type ImageVariantState int32

const (
	ImageVariantState_IMAGE_VARIANT_STATE_UNSPECIFIED    ImageVariantState = 0
	ImageVariantState_IMAGE_VARIANT_STATE_WAITING_UPLOAD ImageVariantState = 1
	ImageVariantState_IMAGE_VARIANT_STATE_PROCESSING     ImageVariantState = 2
	ImageVariantState_IMAGE_VARIANT_STATE_FAILED         ImageVariantState = 3
	ImageVariantState_IMAGE_VARIANT_STATE_READY          ImageVariantState = 4
)

// Enum value maps for ImageVariantState.
var (
	ImageVariantState_name = map[int32]string{
		0: "IMAGE_VARIANT_STATE_UNSPECIFIED",
		1: "IMAGE_VARIANT_STATE_WAITING_UPLOAD",
		2: "IMAGE_VARIANT_STATE_PROCESSING",
		3: "IMAGE_VARIANT_STATE_FAILED",
		4: "IMAGE_VARIANT_STATE_READY",
	}
	ImageVariantState_value = map[string]int32{
		"IMAGE_VARIANT_STATE_UNSPECIFIED":    0,
		"IMAGE_VARIANT_STATE_WAITING_UPLOAD": 1,
		"IMAGE_VARIANT_STATE_PROCESSING":     2,
		"IMAGE_VARIANT_STATE_FAILED":         3,
		"IMAGE_VARIANT_STATE_READY":          4,
	}
)

func (x ImageVariantState) Enum() *ImageVariantState {
	p := new(ImageVariantState)
	*p = x
	return p
}

func (x ImageVariantState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageVariantState) Descriptor() protoreflect.EnumDescriptor {
	return file_imageer_v1_image_proto_enumTypes[4].Descriptor()
}

func (ImageVariantState) Type() protoreflect.EnumType {
	return &file_imageer_v1_image_proto_enumTypes[4]
}

func (x ImageVariantState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageVariantState.Descriptor instead.
func (ImageVariantState) EnumDescriptor() ([]byte, []int) {
	return file_imageer_v1_image_proto_rawDescGZIP(), []int{4}
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Format        ImageFormat            `protobuf:"varint,5,opt,name=format,proto3,enum=imageer.v1.ImageFormat" json:"format,omitempty"`
	State         ImageState             `protobuf:"varint,6,opt,name=state,proto3,enum=imageer.v1.ImageState" json:"state,omitempty"`
	S3Key         string                 `protobuf:"bytes,7,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	ProjectId     string                 `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_imageer_v1_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_imageer_v1_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_imageer_v1_image_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Image) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Image) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Image) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Image) GetFormat() ImageFormat {
	if x != nil {
		return x.Format
	}
	return ImageFormat_IMAGE_FORMAT_UNSPECIFIED
}

func (x *Image) GetState() ImageState {
	if x != nil {
		return x.State
	}
	return ImageState_IMAGE_STATE_UNSPECIFIED
}

func (x *Image) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ImageVariant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Format        ImageFormat            `protobuf:"varint,4,opt,name=format,proto3,enum=imageer.v1.ImageFormat" json:"format,omitempty"`
	State         ImageVariantState      `protobuf:"varint,5,opt,name=state,proto3,enum=imageer.v1.ImageVariantState" json:"state,omitempty"`
	S3Key         string                 `protobuf:"bytes,6,opt,name=s3_key,json=s3Key,proto3" json:"s3_key,omitempty"`
	Url           string                 `protobuf:"bytes,7,opt,name=url,proto3" json:"url,omitempty"`
	ImageId       string                 `protobuf:"bytes,8,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageVariant) Reset() {
	*x = ImageVariant{}
	mi := &file_imageer_v1_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageVariant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageVariant) ProtoMessage() {}

func (x *ImageVariant) ProtoReflect() protoreflect.Message {
	mi := &file_imageer_v1_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageVariant.ProtoReflect.Descriptor instead.
func (*ImageVariant) Descriptor() ([]byte, []int) {
	return file_imageer_v1_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageVariant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ImageVariant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ImageVariant) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ImageVariant) GetFormat() ImageFormat {
	if x != nil {
		return x.Format
	}
	return ImageFormat_IMAGE_FORMAT_UNSPECIFIED
}

func (x *ImageVariant) GetState() ImageVariantState {
	if x != nil {
		return x.State
	}
	return ImageVariantState_IMAGE_VARIANT_STATE_UNSPECIFIED
}

func (x *ImageVariant) GetS3Key() string {
	if x != nil {
		return x.S3Key
	}
	return ""
}

func (x *ImageVariant) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageVariant) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

var File_imageer_v1_image_proto protoreflect.FileDescriptor

const file_imageer_v1_image_proto_rawDesc = "" +
	"\n" +
	"\x16imageer/v1/image.proto\x12\n" +
	"imageer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd1\x02\n" +
	"\x05Image\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12/\n" +
	"\x06format\x18\x05 \x01(\x0e2\x17.imageer.v1.ImageFormatR\x06format\x12,\n" +
	"\x05state\x18\x06 \x01(\x0e2\x16.imageer.v1.ImageStateR\x05state\x12\x15\n" +
	"\x06s3_key\x18\a \x01(\tR\x05s3Key\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\tR\tprojectId\"\xbe\x02\n" +
	"\fImageVariant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12/\n" +
	"\x06format\x18\x04 \x01(\x0e2\x17.imageer.v1.ImageFormatR\x06format\x123\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1d.imageer.v1.ImageVariantStateR\x05state\x12\x15\n" +
	"\x06s3_key\x18\x06 \x01(\tR\x05s3Key\x12\x10\n" +
	"\x03url\x18\a \x01(\tR\x03url\x12\x19\n" +
	"\bimage_id\x18\b \x01(\tR\aimageId*\x9d\x01\n" +
	"\vImageFormat\x12\x1c\n" +
	"\x18IMAGE_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11IMAGE_FORMAT_JPEG\x10\x01\x12\x14\n" +
	"\x10IMAGE_FORMAT_PNG\x10\x02\x12\x15\n" +
	"\x11IMAGE_FORMAT_WEBP\x10\x03\x12\x15\n" +
	"\x11IMAGE_FORMAT_AVIF\x10\x04\x12\x15\n" +
	"\x11IMAGE_FORMAT_HEIC\x10\x05*e\n" +
	"\bImageFit\x12\x19\n" +
	"\x15IMAGE_FIT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fIMAGE_FIT_COVER\x10\x01\x12\x15\n" +
	"\x11IMAGE_FIT_CONTAIN\x10\x02\x12\x12\n" +
	"\x0eIMAGE_FIT_FILL\x10\x03*\xba\x01\n" +
	"\vImageAnchor\x12\x1c\n" +
	"\x18IMAGE_ANCHOR_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12IMAGE_ANCHOR_SMART\x10\x01\x12\x17\n" +
	"\x13IMAGE_ANCHOR_CENTER\x10\x02\x12\x16\n" +
	"\x12IMAGE_ANCHOR_NORTH\x10\x03\x12\x16\n" +
	"\x12IMAGE_ANCHOR_SOUTH\x10\x04\x12\x15\n" +
	"\x11IMAGE_ANCHOR_EAST\x10\x05\x12\x15\n" +
	"\x11IMAGE_ANCHOR_WEST\x10\x06*x\n" +
	"\n" +
	"ImageState\x12\x1b\n" +
	"\x17IMAGE_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aIMAGE_STATE_WAITING_UPLOAD\x10\x01\x12\x16\n" +
	"\x12IMAGE_STATE_FAILED\x10\x02\x12\x15\n" +
	"\x11IMAGE_STATE_READY\x10\x03*\xc3\x01\n" +
	"\x11ImageVariantState\x12#\n" +
	"\x1fIMAGE_VARIANT_STATE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"IMAGE_VARIANT_STATE_WAITING_UPLOAD\x10\x01\x12\"\n" +
	"\x1eIMAGE_VARIANT_STATE_PROCESSING\x10\x02\x12\x1e\n" +
	"\x1aIMAGE_VARIANT_STATE_FAILED\x10\x03\x12\x1d\n" +
	"\x19IMAGE_VARIANT_STATE_READY\x10\x04B\x9d\x01\n" +
	"\x0ecom.imageer.v1B\n" +
	"ImageProtoP\x01Z6github.com/isutare412/imageer/gen/imageer/v1;imageerv1\xa2\x02\x03IXX\xaa\x02\n" +
	"Imageer.V1\xca\x02\n" +
	"Imageer\\V1\xe2\x02\x16Imageer\\V1\\GPBMetadata\xea\x02\vImageer::V1b\x06proto3"

var (
	file_imageer_v1_image_proto_rawDescOnce sync.Once
	file_imageer_v1_image_proto_rawDescData []byte
)

func file_imageer_v1_image_proto_rawDescGZIP() []byte {
	file_imageer_v1_image_proto_rawDescOnce.Do(func() {
		file_imageer_v1_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imageer_v1_image_proto_rawDesc), len(file_imageer_v1_image_proto_rawDesc)))
	})
	return file_imageer_v1_image_proto_rawDescData
}

var file_imageer_v1_image_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_imageer_v1_image_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_imageer_v1_image_proto_goTypes = []any{
	(ImageFormat)(0),              // 0: imageer.v1.ImageFormat
	(ImageFit)(0),                 // 1: imageer.v1.ImageFit
	(ImageAnchor)(0),              // 2: imageer.v1.ImageAnchor
	(ImageState)(0),               // 3: imageer.v1.ImageState
	(ImageVariantState)(0),        // 4: imageer.v1.ImageVariantState
	(*Image)(nil),                 // 5: imageer.v1.Image
	(*ImageVariant)(nil),          // 6: imageer.v1.ImageVariant
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_imageer_v1_image_proto_depIdxs = []int32{
	7, // 0: imageer.v1.Image.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: imageer.v1.Image.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: imageer.v1.Image.format:type_name -> imageer.v1.ImageFormat
	3, // 3: imageer.v1.Image.state:type_name -> imageer.v1.ImageState
	7, // 4: imageer.v1.ImageVariant.created_at:type_name -> google.protobuf.Timestamp
	7, // 5: imageer.v1.ImageVariant.updated_at:type_name -> google.protobuf.Timestamp
	0, // 6: imageer.v1.ImageVariant.format:type_name -> imageer.v1.ImageFormat
	4, // 7: imageer.v1.ImageVariant.state:type_name -> imageer.v1.ImageVariantState
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_imageer_v1_image_proto_init() }
func file_imageer_v1_image_proto_init() {
	if File_imageer_v1_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imageer_v1_image_proto_rawDesc), len(file_imageer_v1_image_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_imageer_v1_image_proto_goTypes,
		DependencyIndexes: file_imageer_v1_image_proto_depIdxs,
		EnumInfos:         file_imageer_v1_image_proto_enumTypes,
		MessageInfos:      file_imageer_v1_image_proto_msgTypes,
	}.Build()
	File_imageer_v1_image_proto = out.File
	file_imageer_v1_image_proto_goTypes = nil
	file_imageer_v1_image_proto_depIdxs = nil
}
