// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: imageer/v1/preset.proto

package imageerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Preset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Default       bool                   `protobuf:"varint,5,opt,name=default,proto3" json:"default,omitempty"`
	Format        ImageFormat            `protobuf:"varint,6,opt,name=format,proto3,enum=imageer.v1.ImageFormat" json:"format,omitempty"`
	Quality       int32                  `protobuf:"varint,7,opt,name=quality,proto3" json:"quality,omitempty"`
	Fit           ImageFit               `protobuf:"varint,8,opt,name=fit,proto3,enum=imageer.v1.ImageFit" json:"fit,omitempty"`
	Anchor        ImageAnchor            `protobuf:"varint,9,opt,name=anchor,proto3,enum=imageer.v1.ImageAnchor" json:"anchor,omitempty"`
	Width         *int32                 `protobuf:"varint,10,opt,name=width,proto3,oneof" json:"width,omitempty"`
	Height        *int32                 `protobuf:"varint,11,opt,name=height,proto3,oneof" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Preset) Reset() {
	*x = Preset{}
	mi := &file_imageer_v1_preset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Preset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Preset) ProtoMessage() {}

func (x *Preset) ProtoReflect() protoreflect.Message {
	mi := &file_imageer_v1_preset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Preset.ProtoReflect.Descriptor instead.
func (*Preset) Descriptor() ([]byte, []int) {
	return file_imageer_v1_preset_proto_rawDescGZIP(), []int{0}
}

func (x *Preset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Preset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Preset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Preset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Preset) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *Preset) GetFormat() ImageFormat {
	if x != nil {
		return x.Format
	}
	return ImageFormat_IMAGE_FORMAT_UNSPECIFIED
}

func (x *Preset) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *Preset) GetFit() ImageFit {
	if x != nil {
		return x.Fit
	}
	return ImageFit_IMAGE_FIT_UNSPECIFIED
}

func (x *Preset) GetAnchor() ImageAnchor {
	if x != nil {
		return x.Anchor
	}
	return ImageAnchor_IMAGE_ANCHOR_UNSPECIFIED
}

func (x *Preset) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Preset) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

var File_imageer_v1_preset_proto protoreflect.FileDescriptor

const file_imageer_v1_preset_proto_rawDesc = "" +
	"\n" +
	"\x17imageer/v1/preset.proto\x12\n" +
	"imageer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16imageer/v1/image.proto\"\xad\x03\n" +
	"\x06Preset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\adefault\x18\x05 \x01(\bR\adefault\x12/\n" +
	"\x06format\x18\x06 \x01(\x0e2\x17.imageer.v1.ImageFormatR\x06format\x12\x18\n" +
	"\aquality\x18\a \x01(\x05R\aquality\x12&\n" +
	"\x03fit\x18\b \x01(\x0e2\x14.imageer.v1.ImageFitR\x03fit\x12/\n" +
	"\x06anchor\x18\t \x01(\x0e2\x17.imageer.v1.ImageAnchorR\x06anchor\x12\x19\n" +
	"\x05width\x18\n" +
	" \x01(\x05H\x00R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\v \x01(\x05H\x01R\x06height\x88\x01\x01B\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\x9e\x01\n" +
	"\x0ecom.imageer.v1B\vPresetProtoP\x01Z6github.com/isutare412/imageer/gen/imageer/v1;imageerv1\xa2\x02\x03IXX\xaa\x02\n" +
	"Imageer.V1\xca\x02\n" +
	"Imageer\\V1\xe2\x02\x16Imageer\\V1\\GPBMetadata\xea\x02\vImageer::V1b\x06proto3"

var (
	file_imageer_v1_preset_proto_rawDescOnce sync.Once
	file_imageer_v1_preset_proto_rawDescData []byte
)

func file_imageer_v1_preset_proto_rawDescGZIP() []byte {
	file_imageer_v1_preset_proto_rawDescOnce.Do(func() {
		file_imageer_v1_preset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imageer_v1_preset_proto_rawDesc), len(file_imageer_v1_preset_proto_rawDesc)))
	})
	return file_imageer_v1_preset_proto_rawDescData
}

var file_imageer_v1_preset_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_imageer_v1_preset_proto_goTypes = []any{
	(*Preset)(nil),                // 0: imageer.v1.Preset
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(ImageFormat)(0),              // 2: imageer.v1.ImageFormat
	(ImageFit)(0),                 // 3: imageer.v1.ImageFit
	(ImageAnchor)(0),              // 4: imageer.v1.ImageAnchor
}
var file_imageer_v1_preset_proto_depIdxs = []int32{
	1, // 0: imageer.v1.Preset.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: imageer.v1.Preset.updated_at:type_name -> google.protobuf.Timestamp
	2, // 2: imageer.v1.Preset.format:type_name -> imageer.v1.ImageFormat
	3, // 3: imageer.v1.Preset.fit:type_name -> imageer.v1.ImageFit
	4, // 4: imageer.v1.Preset.anchor:type_name -> imageer.v1.ImageAnchor
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_imageer_v1_preset_proto_init() }
func file_imageer_v1_preset_proto_init() {
	if File_imageer_v1_preset_proto != nil {
		return
	}
	file_imageer_v1_image_proto_init()
	file_imageer_v1_preset_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imageer_v1_preset_proto_rawDesc), len(file_imageer_v1_preset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_imageer_v1_preset_proto_goTypes,
		DependencyIndexes: file_imageer_v1_preset_proto_depIdxs,
		MessageInfos:      file_imageer_v1_preset_proto_msgTypes,
	}.Build()
	File_imageer_v1_preset_proto = out.File
	file_imageer_v1_preset_proto_goTypes = nil
	file_imageer_v1_preset_proto_depIdxs = nil
}
