// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: imageer/v1/storage.proto

package imageerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageS3DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	S3Keys        []string               `protobuf:"bytes,3,rep,name=s3_keys,json=s3Keys,proto3" json:"s3_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageS3DeleteRequest) Reset() {
	*x = ImageS3DeleteRequest{}
	mi := &file_imageer_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageS3DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageS3DeleteRequest) ProtoMessage() {}

func (x *ImageS3DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_imageer_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageS3DeleteRequest.ProtoReflect.Descriptor instead.
func (*ImageS3DeleteRequest) Descriptor() ([]byte, []int) {
	return file_imageer_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ImageS3DeleteRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageS3DeleteRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ImageS3DeleteRequest) GetS3Keys() []string {
	if x != nil {
		return x.S3Keys
	}
	return nil
}

var File_imageer_v1_storage_proto protoreflect.FileDescriptor

const file_imageer_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x18imageer/v1/storage.proto\x12\n" +
	"imageer.v1\"i\n" +
	"\x14ImageS3DeleteRequest\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x17\n" +
	"\as3_keys\x18\x03 \x03(\tR\x06s3KeysB\x9f\x01\n" +
	"\x0ecom.imageer.v1B\fStorageProtoP\x01Z6github.com/isutare412/imageer/gen/imageer/v1;imageerv1\xa2\x02\x03IXX\xaa\x02\n" +
	"Imageer.V1\xca\x02\n" +
	"Imageer\\V1\xe2\x02\x16Imageer\\V1\\GPBMetadata\xea\x02\vImageer::V1b\x06proto3"

var (
	file_imageer_v1_storage_proto_rawDescOnce sync.Once
	file_imageer_v1_storage_proto_rawDescData []byte
)

func file_imageer_v1_storage_proto_rawDescGZIP() []byte {
	file_imageer_v1_storage_proto_rawDescOnce.Do(func() {
		file_imageer_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_imageer_v1_storage_proto_rawDesc), len(file_imageer_v1_storage_proto_rawDesc)))
	})
	return file_imageer_v1_storage_proto_rawDescData
}

var file_imageer_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_imageer_v1_storage_proto_goTypes = []any{
	(*ImageS3DeleteRequest)(nil), // 0: imageer.v1.ImageS3DeleteRequest
}
var file_imageer_v1_storage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_imageer_v1_storage_proto_init() }
func file_imageer_v1_storage_proto_init() {
	if File_imageer_v1_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_imageer_v1_storage_proto_rawDesc), len(file_imageer_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_imageer_v1_storage_proto_goTypes,
		DependencyIndexes: file_imageer_v1_storage_proto_depIdxs,
		MessageInfos:      file_imageer_v1_storage_proto_msgTypes,
	}.Build()
	File_imageer_v1_storage_proto = out.File
	file_imageer_v1_storage_proto_goTypes = nil
	file_imageer_v1_storage_proto_depIdxs = nil
}
