// Code generated by "enumer -type=Role -trimprefix Role -output role_enum.go -transform snake-upper -text -json -sql"; DO NOT EDIT.

package users

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _RoleName = "ADMINGUEST"

var _RoleIndex = [...]uint8{0, 5, 10}

const _RoleLowerName = "adminguest"

func (i Role) String() string {
	if i < 0 || i >= Role(len(_RoleIndex)-1) {
		return fmt.Sprintf("Role(%d)", i)
	}
	return _RoleName[_RoleIndex[i]:_RoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RoleNoOp() {
	var x [1]struct{}
	_ = x[RoleAdmin-(0)]
	_ = x[RoleGuest-(1)]
}

var _RoleValues = []Role{RoleAdmin, RoleGuest}

var _RoleNameToValueMap = map[string]Role{
	_RoleName[0:5]:       RoleAdmin,
	_RoleLowerName[0:5]:  RoleAdmin,
	_RoleName[5:10]:      RoleGuest,
	_RoleLowerName[5:10]: RoleGuest,
}

var _RoleNames = []string{
	_RoleName[0:5],
	_RoleName[5:10],
}

// RoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RoleString(s string) (Role, error) {
	if val, ok := _RoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Role values", s)
}

// RoleValues returns all values of the enum
func RoleValues() []Role {
	return _RoleValues
}

// RoleStrings returns a slice of all String values of the enum
func RoleStrings() []string {
	strs := make([]string, len(_RoleNames))
	copy(strs, _RoleNames)
	return strs
}

// IsARole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Role) IsARole() bool {
	for _, v := range _RoleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Role
func (i Role) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Role
func (i *Role) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Role should be a string, got %s", data)
	}

	var err error
	*i, err = RoleString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for Role
func (i Role) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Role
func (i *Role) UnmarshalText(text []byte) error {
	var err error
	*i, err = RoleString(string(text))
	return err
}

func (i Role) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Role) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Role: %[1]T(%[1]v)", value)
	}

	val, err := RoleString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
