basePath: /api/v1
definitions:
  http.getGreetingResp:
    properties:
      msg:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Endpoint API for image processing service.
  title: Imageer Endpoint API
  version: "0.1"
paths:
  /greeting/{name}:
    get:
      consumes:
      - application/json
      description: Greeting by given name
      parameters:
      - description: name for greeting
        in: path
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/http.getGreetingResp'
        "400":
          description: error
          schema:
            type: string
        "500":
          description: error
          schema:
            type: string
      summary: Say greeting
      tags:
      - Greeting
swagger: "2.0"
