// Code generated by "enumer -type=AccessScope -trimprefix AccessScope -output access_scope_enum.go -transform snake-upper -text -json -sql"; DO NOT EDIT.

package serviceaccounts

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _AccessScopeName = "FULLPROJECT"

var _AccessScopeIndex = [...]uint8{0, 4, 11}

const _AccessScopeLowerName = "fullproject"

func (i AccessScope) String() string {
	if i < 0 || i >= AccessScope(len(_AccessScopeIndex)-1) {
		return fmt.Sprintf("AccessScope(%d)", i)
	}
	return _AccessScopeName[_AccessScopeIndex[i]:_AccessScopeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AccessScopeNoOp() {
	var x [1]struct{}
	_ = x[AccessScopeFull-(0)]
	_ = x[AccessScopeProject-(1)]
}

var _AccessScopeValues = []AccessScope{AccessScopeFull, AccessScopeProject}

var _AccessScopeNameToValueMap = map[string]AccessScope{
	_AccessScopeName[0:4]:       AccessScopeFull,
	_AccessScopeLowerName[0:4]:  AccessScopeFull,
	_AccessScopeName[4:11]:      AccessScopeProject,
	_AccessScopeLowerName[4:11]: AccessScopeProject,
}

var _AccessScopeNames = []string{
	_AccessScopeName[0:4],
	_AccessScopeName[4:11],
}

// AccessScopeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AccessScopeString(s string) (AccessScope, error) {
	if val, ok := _AccessScopeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AccessScopeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AccessScope values", s)
}

// AccessScopeValues returns all values of the enum
func AccessScopeValues() []AccessScope {
	return _AccessScopeValues
}

// AccessScopeStrings returns a slice of all String values of the enum
func AccessScopeStrings() []string {
	strs := make([]string, len(_AccessScopeNames))
	copy(strs, _AccessScopeNames)
	return strs
}

// IsAAccessScope returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AccessScope) IsAAccessScope() bool {
	for _, v := range _AccessScopeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AccessScope
func (i AccessScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AccessScope
func (i *AccessScope) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AccessScope should be a string, got %s", data)
	}

	var err error
	*i, err = AccessScopeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for AccessScope
func (i AccessScope) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for AccessScope
func (i *AccessScope) UnmarshalText(text []byte) error {
	var err error
	*i, err = AccessScopeString(string(text))
	return err
}

func (i AccessScope) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *AccessScope) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of AccessScope: %[1]T(%[1]v)", value)
	}

	val, err := AccessScopeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
