server:
  mode: "development" # development/production
  http:
    host: "localhost"
    port: "8080"
redis:
  addrs:
    - "localhost:6379"
  password: "imageer"
mysql:
  username: "imageer"
  password: "imageer"
  address: "localhost:3306"
  database: "imageer_api"