// Package web provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package web

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/isutare412/imageer/pkg/images"
	"github.com/isutare412/imageer/pkg/serviceaccounts"
	"github.com/isutare412/imageer/pkg/users"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// AppError defines model for AppError.
type AppError struct {
	// CodeID Error code ID for programmatic handling
	CodeID int64 `json:"codeId"`

	// CodeName Error code name for programmatic handling
	CodeName string `json:"codeName"`

	// Message Error message
	Message string `json:"message"`
}

// CreatePresetRequest defines model for CreatePresetRequest.
type CreatePresetRequest struct {
	// Anchor The anchor position for image cropping.
	Anchor *ImageAnchor `json:"anchor,omitempty"`

	// Default Indicates if this preset is the default one.
	Default bool `json:"default"`

	// Fit The fit mode for image conversion:
	//   - COVER: Scale the image to cover the target dimensions. Some parts may be cropped.
	//   - CONTAIN: Scale the image to fit within the target dimensions. No cropping occurs. Empty areas may be filled with background color.
	//   - FILL: Scale the image to fill the target dimensions. The image may be distorted.
	Fit *ImageFit `json:"fit,omitempty"`

	// Format The content type of the image.
	Format *ImageFormat `json:"format,omitempty"`

	// Height The height of the image in pixels.
	Height *int64 `json:"height,omitempty"`

	// Name The name of the preset.
	Name string `json:"name"`

	// Quality The quality of the image (1-100). Default is 80.
	Quality *int64 `json:"quality,omitempty"`

	// Width The width of the image in pixels.
	Width *int64 `json:"width,omitempty"`
}

// CreateProjectAdminRequest defines model for CreateProjectAdminRequest.
type CreateProjectAdminRequest struct {
	// Name The name of the project.
	Name    string                `json:"name"`
	Presets []CreatePresetRequest `json:"presets,omitempty"`
}

// CreateServiceAccountAdminRequest defines model for CreateServiceAccountAdminRequest.
type CreateServiceAccountAdminRequest struct {
	// AccessScope The access scope of the service account.
	AccessScope ServiceAccountAccessScope `json:"accessScope"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// Name The name of the service account.
	Name string `json:"name"`

	// ProjectIDs List of project IDs to associate with the service account.
	ProjectIDs []string `json:"projectIds,omitempty"`
}

// CreateUploadURLRequest defines model for CreateUploadUrlRequest.
type CreateUploadURLRequest struct {
	// FileName The name of the file to be uploaded.
	FileName string `json:"fileName"`

	// Format The content type of the image.
	Format ImageFormat `json:"format"`

	// PresetNames List of preset names to apply to the image. If not provided, default presets will be applied.
	PresetNames []string `json:"presetNames,omitempty"`
}

// Image defines model for Image.
type Image struct {
	// CreatedAt The creation time of the image.
	CreatedAt time.Time `json:"createdAt"`

	// Format The content type of the image.
	Format ImageFormat `json:"format"`

	// ID The unique identifier of the image.
	ID string `json:"id"`

	// State The current state of the image.
	State ImageState `json:"state"`

	// UpdatedAt The last update time of the image.
	UpdatedAt time.Time `json:"updatedAt"`

	// URL The URL of the original image.
	URL string `json:"url"`

	// Variants List of image variants with applied presets.
	Variants []ImageVariant `json:"variants,omitempty"`
}

// ImageAnchor The anchor position for image cropping.
type ImageAnchor = images.Anchor

// ImageFit The fit mode for image conversion:
//   - COVER: Scale the image to cover the target dimensions. Some parts may be cropped.
//   - CONTAIN: Scale the image to fit within the target dimensions. No cropping occurs. Empty areas may be filled with background color.
//   - FILL: Scale the image to fill the target dimensions. The image may be distorted.
type ImageFit = images.Fit

// ImageFormat The content type of the image.
type ImageFormat = images.Format

// ImageState The current state of the image.
type ImageState = images.State

// ImageVariant defines model for ImageVariant.
type ImageVariant struct {
	// CreatedAt The creation time of the image variant.
	CreatedAt time.Time `json:"createdAt"`

	// Format The content type of the image.
	Format ImageFormat `json:"format"`

	// ID The unique identifier of the image variant.
	ID string `json:"id"`

	// PresetID The unique identifier of the preset.
	PresetID string `json:"presetId"`

	// PresetName The name of the preset.
	PresetName string `json:"presetName"`

	// State The current state of the image variant.
	State ImageVariantState `json:"state"`

	// UpdatedAt The time when the image variant was updated.
	UpdatedAt time.Time `json:"updatedAt"`

	// URL The URL of the image with the applied preset.
	URL string `json:"url"`
}

// ImageVariantState The current state of the image variant.
type ImageVariantState = images.VariantState

// Images defines model for Images.
type Images struct {
	Items []Image `json:"items"`

	// Total The total number of images.
	Total int64 `json:"total"`
}

// Preset defines model for Preset.
type Preset struct {
	// Anchor The anchor position for image cropping.
	Anchor *ImageAnchor `json:"anchor,omitempty"`

	// CreatedAt The creation time of the preset.
	CreatedAt time.Time `json:"createdAt"`

	// Default Indicates if this preset is the default one.
	Default bool `json:"default"`

	// Fit The fit mode for image conversion:
	//   - COVER: Scale the image to cover the target dimensions. Some parts may be cropped.
	//   - CONTAIN: Scale the image to fit within the target dimensions. No cropping occurs. Empty areas may be filled with background color.
	//   - FILL: Scale the image to fill the target dimensions. The image may be distorted.
	Fit *ImageFit `json:"fit,omitempty"`

	// Format The content type of the image.
	Format ImageFormat `json:"format"`

	// Height The height of the image in pixels.
	Height *int64 `json:"height,omitempty"`

	// ID The unique identifier of the preset.
	ID string `json:"id"`

	// Name The name of the preset.
	Name string `json:"name"`

	// Quality The quality of the image (1-100).
	Quality int64 `json:"quality"`

	// UpdatedAt The last update time of the preset.
	UpdatedAt time.Time `json:"updatedAt"`

	// Width The width of the image in pixels.
	Width *int64 `json:"width,omitempty"`
}

// Project defines model for Project.
type Project struct {
	// CreatedAt The creation time of the project.
	CreatedAt time.Time `json:"createdAt"`

	// ID The unique identifier of the project.
	ID string `json:"id"`

	// Name The name of the project.
	Name string `json:"name"`

	// Presets List of presets to apply to images of the project.
	Presets []Preset `json:"presets"`

	// UpdatedAt The last update time of the project.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ProjectReference defines model for ProjectReference.
type ProjectReference struct {
	// ID The unique identifier of the project.
	ID string `json:"id"`

	// Name The name of the project.
	Name string `json:"name"`
}

// Projects defines model for Projects.
type Projects struct {
	Items []Project `json:"items"`

	// Total The total number of projects.
	Total int64 `json:"total"`
}

// ReprocessImagesAdminRequest defines model for ReprocessImagesAdminRequest.
type ReprocessImagesAdminRequest struct {
	// ImageIDs List of image IDs to reprocess. If not provided and reprocessAll is true, all images in the project will be reprocessed.
	ImageIDs []string `json:"imageIds,omitempty"`

	// ReprocessAll If true, reprocess all images in the project. Takes precedence over imageIds.
	ReprocessAll bool `json:"reprocessAll,omitempty"`
}

// ServiceAccount defines model for ServiceAccount.
type ServiceAccount struct {
	// AccessScope The access scope of the service account.
	AccessScope ServiceAccountAccessScope `json:"accessScope"`

	// CreatedAt The creation time of the service account.
	CreatedAt time.Time `json:"createdAt"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// ID The unique identifier of the service account.
	ID string `json:"id"`

	// Name The name of the service account.
	Name string `json:"name"`

	// Projects List of projects associated with the service account.
	Projects []ProjectReference `json:"projects"`

	// UpdatedAt The last update time of the service account.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ServiceAccountAccessScope The access scope of the service account.
type ServiceAccountAccessScope = serviceaccounts.AccessScope

// ServiceAccountWithAPIKey defines model for ServiceAccountWithApiKey.
type ServiceAccountWithAPIKey struct {
	// AccessScope The access scope of the service account.
	AccessScope ServiceAccountAccessScope `json:"accessScope"`

	// APIKey The API key for the service account.
	APIKey string `json:"apiKey"`

	// CreatedAt The creation time of the service account.
	CreatedAt time.Time `json:"createdAt"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// ID The unique identifier of the service account.
	ID string `json:"id"`

	// Name The name of the service account.
	Name string `json:"name"`

	// Projects List of projects associated with the service account.
	Projects []ProjectReference `json:"projects"`

	// UpdatedAt The last update time of the service account.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ServiceAccounts defines model for ServiceAccounts.
type ServiceAccounts struct {
	Items []ServiceAccount `json:"items"`

	// Total The total number of service accounts.
	Total int64 `json:"total"`
}

// UpdateProjectAdminRequest defines model for UpdateProjectAdminRequest.
type UpdateProjectAdminRequest struct {
	// Name The name of the project.
	Name    *string               `json:"name,omitempty"`
	Presets []UpsertPresetRequest `json:"presets,omitempty"`
}

// UpdateServiceAccountAdminRequest defines model for UpdateServiceAccountAdminRequest.
type UpdateServiceAccountAdminRequest struct {
	// AccessScope The access scope of the service account.
	AccessScope *ServiceAccountAccessScope `json:"accessScope,omitempty"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// Name The name of the service account.
	Name *string `json:"name,omitempty"`

	// ProjectIDs List of project IDs to associate with the service account.
	ProjectIDs []string `json:"projectIds,omitempty"`
}

// UploadURL defines model for UploadUrl.
type UploadURL struct {
	// ExpiresAt The expiration time of the presigned URL.
	ExpiresAt time.Time `json:"expiresAt"`

	// Header Additional headers required for the upload request.
	Header map[string]string `json:"header"`

	// ImageID The unique identifier of the image.
	ImageID string `json:"imageId"`

	// URL The presigned URL for uploading the image. It must be called with PUT method. Check https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html for more details.
	URL string `json:"url"`
}

// UpsertPresetRequest If id is provided, the preset will be updated; otherwise, a new preset
// will be created. All existing presets not included in the upsert list
// will be deleted.
type UpsertPresetRequest struct {
	// Anchor The anchor position for image cropping.
	Anchor *ImageAnchor `json:"anchor,omitempty"`

	// Default Indicates if this preset is the default one.
	Default *bool `json:"default,omitempty"`

	// Fit The fit mode for image conversion:
	//   - COVER: Scale the image to cover the target dimensions. Some parts may be cropped.
	//   - CONTAIN: Scale the image to fit within the target dimensions. No cropping occurs. Empty areas may be filled with background color.
	//   - FILL: Scale the image to fill the target dimensions. The image may be distorted.
	Fit *ImageFit `json:"fit,omitempty"`

	// Format The content type of the image.
	Format *ImageFormat `json:"format,omitempty"`

	// Height The height of the image in pixels.
	Height *int64 `json:"height,omitempty"`

	// ID The unique identifier of the preset.
	ID *string `json:"id,omitempty"`

	// Name The name of the preset.
	Name *string `json:"name,omitempty"`

	// Quality The quality of the image (1-100). Default is 80.
	Quality *int64 `json:"quality,omitempty"`

	// Width The width of the image in pixels.
	Width *int64 `json:"width,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt The creation time of the user.
	CreatedAt time.Time `json:"createdAt"`

	// Email The email address of the user.
	Email string `json:"email"`

	// ID The unique identifier of the user.
	ID string `json:"id"`

	// Nickname The nickname of the user.
	Nickname string `json:"nickname"`

	// PhotoURL The photo URL of the user.
	PhotoURL string `json:"photoUrl"`

	// Role The role of the user.
	Role UserRole `json:"role"`

	// UpdatedAt The last update time of the user.
	UpdatedAt time.Time `json:"updatedAt"`
}

// UserRole The role of the user.
type UserRole = users.Role

// ImageIDPath defines model for ImageIdPath.
type ImageIDPath = string

// LimitQuery defines model for LimitQuery.
type LimitQuery = int64

// OffsetQuery defines model for OffsetQuery.
type OffsetQuery = int64

// ProjectIDPath defines model for ProjectIdPath.
type ProjectIDPath = string

// RedirectQuery defines model for RedirectQuery.
type RedirectQuery = string

// ServiceAccountIDPath defines model for ServiceAccountIdPath.
type ServiceAccountIDPath = string

// WaitUntilProcessedQuery defines model for WaitUntilProcessedQuery.
type WaitUntilProcessedQuery = bool

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = AppError

// ListProjectsAdminParams defines parameters for ListProjectsAdmin.
type ListProjectsAdminParams struct {
	// Offset Offset for pagination
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Limit for pagination
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListServiceAccountsAdminParams defines parameters for ListServiceAccountsAdmin.
type ListServiceAccountsAdminParams struct {
	// Offset Offset for pagination
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Limit for pagination
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`
}

// StartGoogleSignInParams defines parameters for StartGoogleSignIn.
type StartGoogleSignInParams struct {
	// Redirect The path to redirect to after successful sign-in. Defaults to root path if not provided.
	Redirect *RedirectQuery `form:"redirect,omitempty" json:"redirect,omitempty"`
}

// FinishGoogleSignInParams defines parameters for FinishGoogleSignIn.
type FinishGoogleSignInParams struct {
	// Code The authorization code returned by Google after sign-in.
	Code string `form:"code" json:"code"`

	// State The state parameter to prevent CSRF attacks.
	State string `form:"state" json:"state"`
}

// GetImageParams defines parameters for GetImage.
type GetImageParams struct {
	// WaitUntilProcessed Wait until the image processing is completed
	WaitUntilProcessed *WaitUntilProcessedQuery `form:"waitUntilProcessed,omitempty" json:"waitUntilProcessed,omitempty"`
}

// CreateProjectAdminJSONRequestBody defines body for CreateProjectAdmin for application/json ContentType.
type CreateProjectAdminJSONRequestBody = CreateProjectAdminRequest

// UpdateProjectAdminJSONRequestBody defines body for UpdateProjectAdmin for application/json ContentType.
type UpdateProjectAdminJSONRequestBody = UpdateProjectAdminRequest

// ReprocessImagesAdminJSONRequestBody defines body for ReprocessImagesAdmin for application/json ContentType.
type ReprocessImagesAdminJSONRequestBody = ReprocessImagesAdminRequest

// CreateServiceAccountAdminJSONRequestBody defines body for CreateServiceAccountAdmin for application/json ContentType.
type CreateServiceAccountAdminJSONRequestBody = CreateServiceAccountAdminRequest

// UpdateServiceAccountAdminJSONRequestBody defines body for UpdateServiceAccountAdmin for application/json ContentType.
type UpdateServiceAccountAdminJSONRequestBody = UpdateServiceAccountAdminRequest

// CreateUploadURLJSONRequestBody defines body for CreateUploadURL for application/json ContentType.
type CreateUploadURLJSONRequestBody = CreateUploadURLRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all projects
	// (GET /api/v1/admin/projects)
	ListProjectsAdmin(ctx echo.Context, params ListProjectsAdminParams) error
	// Create a new project
	// (POST /api/v1/admin/projects)
	CreateProjectAdmin(ctx echo.Context) error
	// Delete a project
	// (DELETE /api/v1/admin/projects/{projectId})
	DeleteProjectAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Get project details
	// (GET /api/v1/admin/projects/{projectId})
	GetProjectAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Update project details
	// (PUT /api/v1/admin/projects/{projectId})
	UpdateProjectAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Reprocess multiple images in a project
	// (POST /api/v1/admin/projects/{projectId}/images/reprocess)
	ReprocessImagesAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// List service accounts
	// (GET /api/v1/admin/service-accounts)
	ListServiceAccountsAdmin(ctx echo.Context, params ListServiceAccountsAdminParams) error
	// Create a new service account
	// (POST /api/v1/admin/service-accounts)
	CreateServiceAccountAdmin(ctx echo.Context) error
	// Delete a service account
	// (DELETE /api/v1/admin/service-accounts/{serviceAccountId})
	DeleteServiceAccountAdmin(ctx echo.Context, serviceAccountID ServiceAccountIDPath) error
	// Get service account details
	// (GET /api/v1/admin/service-accounts/{serviceAccountId})
	GetServiceAccountAdmin(ctx echo.Context, serviceAccountID ServiceAccountIDPath) error
	// Update a service account
	// (PUT /api/v1/admin/service-accounts/{serviceAccountId})
	UpdateServiceAccountAdmin(ctx echo.Context, serviceAccountID ServiceAccountIDPath) error
	// Start Google Sign-In
	// (GET /api/v1/auth/google/sign-in)
	StartGoogleSignIn(ctx echo.Context, params StartGoogleSignInParams) error
	// Finish Google Sign-In
	// (GET /api/v1/auth/google/sign-in/callback)
	FinishGoogleSignIn(ctx echo.Context, params FinishGoogleSignInParams) error
	// Sign out the current user
	// (POST /api/v1/auth/sign-out)
	SignOut(ctx echo.Context) error
	// Get project details
	// (GET /api/v1/projects/{projectId})
	GetProject(ctx echo.Context, projectID ProjectIDPath) error
	// Issue a presigned URL for uploading an image
	// (POST /api/v1/projects/{projectId}/images/upload-url)
	CreateUploadURL(ctx echo.Context, projectID ProjectIDPath) error
	// Get image details
	// (GET /api/v1/projects/{projectId}/images/{imageId})
	GetImage(ctx echo.Context, projectID ProjectIDPath, imageID ImageIDPath, params GetImageParams) error
	// Get current user details
	// (GET /api/v1/users/me)
	GetCurrentUser(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListProjectsAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) ListProjectsAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsAdminParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProjectsAdmin(ctx, params)
	return err
}

// CreateProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProjectAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProjectAdmin(ctx)
	return err
}

// DeleteProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProjectAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProjectAdmin(ctx, projectID)
	return err
}

// GetProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) GetProjectAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProjectAdmin(ctx, projectID)
	return err
}

// UpdateProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProjectAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProjectAdmin(ctx, projectID)
	return err
}

// ReprocessImagesAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) ReprocessImagesAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReprocessImagesAdmin(ctx, projectID)
	return err
}

// ListServiceAccountsAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) ListServiceAccountsAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServiceAccountsAdminParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListServiceAccountsAdmin(ctx, params)
	return err
}

// CreateServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) CreateServiceAccountAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateServiceAccountAdmin(ctx)
	return err
}

// DeleteServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "serviceAccountId" -------------
	var serviceAccountID ServiceAccountIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceAccountId", ctx.Param("serviceAccountId"), &serviceAccountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceAccountId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteServiceAccountAdmin(ctx, serviceAccountID)
	return err
}

// GetServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) GetServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "serviceAccountId" -------------
	var serviceAccountID ServiceAccountIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceAccountId", ctx.Param("serviceAccountId"), &serviceAccountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceAccountId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServiceAccountAdmin(ctx, serviceAccountID)
	return err
}

// UpdateServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "serviceAccountId" -------------
	var serviceAccountID ServiceAccountIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceAccountId", ctx.Param("serviceAccountId"), &serviceAccountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceAccountId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateServiceAccountAdmin(ctx, serviceAccountID)
	return err
}

// StartGoogleSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) StartGoogleSignIn(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params StartGoogleSignInParams
	// ------------- Optional query parameter "redirect" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect", ctx.QueryParams(), &params.Redirect)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter redirect: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StartGoogleSignIn(ctx, params)
	return err
}

// FinishGoogleSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) FinishGoogleSignIn(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FinishGoogleSignInParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, true, "code", ctx.QueryParams(), &params.Code)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, true, "state", ctx.QueryParams(), &params.State)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FinishGoogleSignIn(ctx, params)
	return err
}

// SignOut converts echo context to params.
func (w *ServerInterfaceWrapper) SignOut(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignOut(ctx)
	return err
}

// GetProject converts echo context to params.
func (w *ServerInterfaceWrapper) GetProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProject(ctx, projectID)
	return err
}

// CreateUploadURL converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUploadURL(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUploadURL(ctx, projectID)
	return err
}

// GetImage converts echo context to params.
func (w *ServerInterfaceWrapper) GetImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// ------------- Path parameter "imageId" -------------
	var imageID ImageIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "imageId", ctx.Param("imageId"), &imageID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter imageId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetImageParams
	// ------------- Optional query parameter "waitUntilProcessed" -------------

	err = runtime.BindQueryParameter("form", true, false, "waitUntilProcessed", ctx.QueryParams(), &params.WaitUntilProcessed)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter waitUntilProcessed: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetImage(ctx, projectID, imageID, params)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/v1/admin/projects", wrapper.ListProjectsAdmin)
	router.POST(baseURL+"/api/v1/admin/projects", wrapper.CreateProjectAdmin)
	router.DELETE(baseURL+"/api/v1/admin/projects/:projectId", wrapper.DeleteProjectAdmin)
	router.GET(baseURL+"/api/v1/admin/projects/:projectId", wrapper.GetProjectAdmin)
	router.PUT(baseURL+"/api/v1/admin/projects/:projectId", wrapper.UpdateProjectAdmin)
	router.POST(baseURL+"/api/v1/admin/projects/:projectId/images/reprocess", wrapper.ReprocessImagesAdmin)
	router.GET(baseURL+"/api/v1/admin/service-accounts", wrapper.ListServiceAccountsAdmin)
	router.POST(baseURL+"/api/v1/admin/service-accounts", wrapper.CreateServiceAccountAdmin)
	router.DELETE(baseURL+"/api/v1/admin/service-accounts/:serviceAccountId", wrapper.DeleteServiceAccountAdmin)
	router.GET(baseURL+"/api/v1/admin/service-accounts/:serviceAccountId", wrapper.GetServiceAccountAdmin)
	router.PUT(baseURL+"/api/v1/admin/service-accounts/:serviceAccountId", wrapper.UpdateServiceAccountAdmin)
	router.GET(baseURL+"/api/v1/auth/google/sign-in", wrapper.StartGoogleSignIn)
	router.GET(baseURL+"/api/v1/auth/google/sign-in/callback", wrapper.FinishGoogleSignIn)
	router.POST(baseURL+"/api/v1/auth/sign-out", wrapper.SignOut)
	router.GET(baseURL+"/api/v1/projects/:projectId", wrapper.GetProject)
	router.POST(baseURL+"/api/v1/projects/:projectId/images/upload-url", wrapper.CreateUploadURL)
	router.GET(baseURL+"/api/v1/projects/:projectId/images/:imageId", wrapper.GetImage)
	router.GET(baseURL+"/api/v1/users/me", wrapper.GetCurrentUser)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8aXPbOJZ/BYXdD7tV1GU77kRbW7tqW3HU7bYVyUoyk3F1QSQkISYJBgDtqF3671M4",
	"SJEiKFGXk5nKN4m4Ht6N9x7wDF0aRDTEoeCw/QwjxFCABWbqXy9AU9zz+kjM5F8Pc5eRSBAawja8m2HQ",
	"uwR0AsQMAyK71qEDiWyL5AgHhijAsA2JngY6kOGvMWHYg23BYuxA7s5wgOTc+BsKIl/2Pjs5x+enZ5Pa",
	"q6bn1c5aqFl7/bo1rrlv3rTOzlrjU9d7BR0o5pHszQUj4RQuFg68JgER72PM5kVgVRuYUAYiNCUhUp8N",
	"sF/VkBRaX3aFVthaTQdOKAuQkLsKxfnZEhASCjzFTEFyO5lwXAaKbqwGC1V97cBUhKXP6BfsimpUjHRn",
	"ICh4mhF3tiQtGGOfhlNeQuIoWeXYRB5gjzDsliFXbkdCJnfATFf5G00EZoDHros5n8Q+4GQa1khYB5d4",
	"gmJfcDWCUqGHkwkI5W9GH4mHvXoJfZIl7BSCDYMWbt3KELNH4uKO69I4rEggrscApAeVUIOvzHxsonxE",
	"RIxCQfw+oxLB2Cshj+wIYtkzw1mRHkTCKSAcSH3kY4G9EpQ/FdbKId/T5ITtCfI5dpa7M/8N8GNKfYxC",
	"uJDgM8wjGnKsdF6XMcoG5ov84NJQ4FDInyiKfOIqgW184XJHz5ml/5PhCWzD/2gsVWpDt/JGJ4rUxHrB",
	"PFJUA6CuGzOGPeDFEq8KP5JomAuFYzOTXCidTCpsRiPMBNHAu9STiraAd72EbJW8pFQPo1OGggAJ4oIZ",
	"Cj1fEtPJ6rpmFQ3jqDVvFG3WrCqJV21d+Gvn8s9B9/2oO7wrMpsDA8w5mpauljRnZxzSABu++gbwSrci",
	"Ny9F5TNc9jOozez3Ph1Mx1LKJXQXDCOB+wxzLAaGegUqodCdaeqtYxllfDu6q+IZw9ir++6FnuRJzKXS",
	"EjPCQaSWl8IkmcgMBDRU9nmTQDhwQkQl2N4SteWERaqM0F0XDpxhMp0Ju7bTbTnHApAQROQb9nluC68r",
	"smhoZU+5luLL1PhJtOUWgE/nzebsdbNp48SvMfKJKDFCpjG/i/9q1VrN5n+nRkeS6HUzt+Kbajt6Il6Z",
	"sVBNVbB33qzoQmQFQqFyyY3rZECZvo4XkLBUEqoSRk2Vp4zAXNRMi406mppqFSJwwDcxqE1yF+m8iDEk",
	"jdC32pTW5LcafyBRjSqQkV+LqEQY09bVirNyTOX9gPUIQ8qBGbo0wps2tDJtZuBC4jEiDHdKJFC1KjMH",
	"BFnSYcX5AII+4DBPlZPmyWmt1aw1W3etk3az2W42/w4zXOYhgWtyThvJqnGDxQVa4QrTo2Z62LnD+Kvc",
	"dlbgSvskznDvUjmHiHPqEiSkhIlZqTeW8Nq+bpWd9YwTlDj1l3wvnnRy/FTOoaPIp8gbMb+ULyfEL3EC",
	"Vskne0p0jjGI1bTau16iS58kv0RTG052MjZaFUjw1lJbGU0JqiZ3FPlz+WN5ugW9/KnASW2rUTbgifi+",
	"3JlyFM2xocgQ64zKIfRNSowUXzbSKiRZXEhFca9MNajmVcWQHv4PpAh2ojLx7BDHIfkaY0A8HAoyIZit",
	"gXpXUeUCCVwJ3qHquXBgHHnr8OwjLoDuc1RUx8y3AzAaXCdrUkamJES+bfGZEBFvNxrmS92lQSPp39D9",
	"n/A4si39iBhBJu5kl0ntvST9tN41opWIXE7ENmL/g57qUIJG1HkgFZgsUROe0BjeLIid9ExQJIU+L4CI",
	"cqJET56jNGpcRqOIhFNFkzAOJFDDPzoDeXK66N7cdQfQgTe3g7t30IHdjjpRDW9H6u9HecC6z52TzMg8",
	"pQxuSBBRpjW/ilPAKRGzeKwITngsEMNnrRNNcswa0cNU/+Zyiyl2E/3O68uTTXqYsG5+QgQI5BEys2sa",
	"PmLGCQ3b/wgBqIGL2w/dQRsMXSRtS+r2Cgpc+oiZ+iQQm2IBPBLgUA7ldaDOhRFigoMAzaXeVvjEXj2Z",
	"9uau07uxTizBkvxIwrLZb2hKHn2453XQDSIxB4hhlC45Ib6PPc3bY+Q+TBmNQw+41KfMwPG2d31dAoTv",
	"ly1/l3Y0C3mEC8qE2l2GXRTuJLvozUIHyuXyjLFsexHWMAfLrH632yIdmQFydFE/mv391u9eQQf2b64U",
	"z//ahw7sfOi9hQ581+1d5Ddq2l9ml6nlyhgG+z5jxuQ+lUYp3eiof33bufyz37257KnNmg/dT/3eoHsJ",
	"HTjodi7/Jgnc6V13L/M7T9peZOupEcwp5cO5IonJ+Nd0SezQ7+qaaDvZ2xYSWzBkPxBujhKEqe55GTar",
	"6oAppnqa4bBIGPCEuPHNvBd2xTQc6QE07wxt9syM09RIMLrWQ9vG2Um5LEftbZ2gHIm2VIU5qamsEvuD",
	"24vucKhbfxj9uMqqPd25oCBTx7e6B1xwfeV/KlAJ66kmEMbBWKsGA+BKomD7MKIGOFnaxhA6Eneg4Pku",
	"lsQmU3vJ988I/u4RfPI97dePlj7YIV+wY7Th4DLw3fIWa63XSlIjnX1JJLuG0smHg/it1hzHXqjeQWQs",
	"IBxbZvbL7KwL5eajuNpwWdatZDqNMbLYzp0F67Dk3oHbEzSuYe0BnmCGQ9cSJv435S4bHkvTd/2kumdP",
	"xyxRJPu5Zkmt0Us4ZwNsina0Z7o+Z2nK/zbGeU2ejSVzF/ItAIXesrnj+8pBYjF2APL9RMRNRC7J3iUp",
	"mXTcypntc1UmbJ2c4rNX57/U8Os341rrxDutobNX57Wzk/Pz1lnrl7NmsymR9TIZQF2auUX+T5J4iTlb",
	"qdSKUzoxqE2HlSO5Du7QA1Zuq4s9qTCAirsmlK/gtW4RgS9wYz7Tfbyk+S52fW22ei/7/kOm8Lc2C2vx",
	"c1zzcMhCgs1lBHxZQOBVqyCoYDKWBvpwrsmxOHYHFyUruBlU32/UAZ28xFtSaqoD4LLHuo2bQNLb0fW1",
	"jhb91r1YyZolH0tiQ8lHPbmZm9c7ua0tdd8OoaSVqS21xR+JmHUi8jtWp03k+7cT2P68jSaEC6egVdMJ",
	"i+jt9HvgAc9Vzm4jT6GHP4e33U93f78+/fj0y6+f5l//+Ohdvnof9Sfz/ttX4ae7eeus/xB9ePPp/HE+",
	"vP0reO9FX9797dPvJ+eP49nl9PLLRm4zwBY5576ArL3duQLm9vHqVjD3It7dSEniv1oB3yjimImDFfCV",
	"YOVnsd7PYr0XKdaz8J8pwisymmYQviWHSAEj0xB7YDS4PiBnzDDysIrQI88jen/9HLyW0HgW5k46DOi5",
	"OEgUWGpRdO1gckMiB/0zfEelOMIJpXV+WkcB+ouG6IlLIwptqE0uqH23+rHS1F+ORmrzeuPJDZGkMFGA",
	"IOZClbCgZT1Jf3QHAixm1KuDixl2H0CSFPSoy+sSJRo5yr3oqJ/D04aPpGQ2Yo7ZNCYeVuEvBcWI+ZoN",
	"bxXu6jMR+AqqgDIMPCwQWQnWpmlIg/+Ghv//HvD8f9HYbZ2cbvYU0+uDOoto+MvJsL3dihXtQTH1MgHE",
	"AyrjktR0LuPeaezAuKb/A6iYYfZEOHYAAiF+Mh3/ESY9jUNbBx3fB/gb4UJSKglIhlQAErp+7GEvOULH",
	"CkzgE56ZxsPqCpSu1Pl5eeRn6unnzZWdMkBFpcAxO0zCRmrHQ0ZzAkRKbIBqAsjzmDyyli4vv/x/ptjj",
	"IOGZ4jI7czJxH9Zws2ktX/cLnYUeteIumlFBR6UmVLZma2iKc1tLZeQwroxgUh+TUjJmxAYHo/5GR18y",
	"4ED22z1Ac1DOsyY8ElKZLSXcmcF0WejmvkTmBgY1xV3KFQo7M2GXzuUfqur0alSoVb6y3g/Nx1zkdLw+",
	"0FvYK8SiZtJ3dzl2Y0bEfCgJmo2EdGKt19Sl5dRHMWeAT7VOv1f7vZspITIhiYUDxxgxzJLx+l9S9wp/",
	"+3iXXHBWpla1LmeRrKtv4dIHgnMw6E9LGEZDVei7srzcEwkn1OIbaASAKyTwE5qroI7y9VCIpuq2tlLR",
	"DHMaM1dXBQkifFwcCx1oKrZhGzbrLQkxjXCIIgLb8LTerEsFLsmhENpAEWk8thpIHq8b2RDrVJcESeWt",
	"VLJ02tUZMMnFqRO5mmv5kEVJpGvZpZF9sGHhbOyeeWlicb9yf/yk2TzYrfE0wWi5NT5M3zLw54BhwQh+",
	"VJWAyZCc12dbJQW7kb/zrrg8DgLE5skBG/k+yL5lgKZcyadC9r1UwZRbCFO8CWpeIsBc/Eq9+cEQVX7l",
	"dFG84X8ECm0kkNGWCRIPRh298fQwkgbTVgi0cEpkqvGcBlcWWgPIg0eRkpfq+wolt5Ox/EMkZXKzBofm",
	"UHRwHOq9AbQGf45d8Vxh8QIoeVFGLWiS5FR/MHRfYVGY26pSYgvGi6HpgyD98BqpPIb+g2gk47Mdjcwa",
	"ARUoXUk3mXrpRlqMoNw3q9Gx1ab8oEyyrozmyGxiSso3cYlgZDrFDHtgjIQ7S12+5Zs9B2OYFBkgiH1B",
	"Ih9nik3QNsZtJaWw3nFcSf79W/mPq4nN6sp/Ne14WHeyMPu2LqUlC3dUz3JN1u/IclqayK/qca7g+jie",
	"5+oiOwhp43n11bIKDqmdD7aTXeszbHu4p8dCeOqmbkZ2ubv64gg7ghDsrsaO4suWrbGlT3tkyhzLw/1R",
	"NGNlf/dY4mn8XbSlLozFrDGldOrjhnmSstRbGQrExJXqOyTTsLc9f+QfzyyI7GnzpKjjkjEq40yBXh9I",
	"AGoKApOhlwOvqSZk+S3W3KucJuCrHjKgrDjzkg1WY9aLPYlmQriw/fk+S0KF4CIcKfliMcOhMNy6kY4N",
	"F/n+GLkPpQR9S0LCZ+spaildjMWMMvKXTkmp1xUZFjELpZM+T8A3D56aV05L3tKUg9e+DVpIFtgA0ndx",
	"U7glPSOGH3EowMVw8BYgIZD7wMuASK4IV4eiEt/mhN/UUJBQ10VoHB2KeZeoVkHx78K6mpX24F3FKVSb",
	"J7vnLSe9jQXc2jEyyJeTH0rZSljkhIoOyZ1wSY+KWy4Lf26I8v0M8O0f4Evg3EiPJOSjC4ZqpkRq3anQ",
	"VMgNrn/QcE/JY3pH9pOWdYObWINwHmOvWBt4MM7oyQVULKe8qg2FOuyTYRn9cEFlhnk2BWNrJbpn1tiL",
	"TzZHerIv6FfoXvaQ9lE1h3kXorLe0DHAY2iN/MxrGUBl5Bu6nKSMxhfaMIy0XTiegHHMtkBf1lwdBYvW",
	"BdbZxbxf8ZyrR/h8L9k2W+Ggv2TrDT7fS/6U5x6713qRPNqiepg6zjZsKLY2YCVXCVbBk2vl66izn5In",
	"TZaj1RFrcb/4ZwAAAP//1r5o+9liAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
