// Package web provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package web

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/google/uuid"
	"github.com/isutare412/imageer/pkg/images"
	"github.com/isutare412/imageer/pkg/serviceaccounts"
	"github.com/isutare412/imageer/pkg/users"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// AppError defines model for AppError.
type AppError struct {
	// CodeID Error code ID for programmatic handling
	CodeID int64 `json:"codeId"`

	// CodeName Error code name for programmatic handling
	CodeName string `json:"codeName"`

	// Message Error message
	Message string `json:"message"`
}

// CreatePresignedURLRequest defines model for CreatePresignedUrlRequest.
type CreatePresignedURLRequest struct {
	// ContentType The content type of the image.
	ContentType ImageContentType `json:"contentType"`

	// FileName The name of the file to be uploaded.
	FileName string `json:"fileName"`

	// TransformationNames List of transformation names to apply to the image. If not provided, default transformations will be applied.
	TransformationNames []string `json:"transformationNames,omitempty"`
}

// CreateProjectAdminRequest defines model for CreateProjectAdminRequest.
type CreateProjectAdminRequest struct {
	// Name The name of the project.
	Name string `json:"name"`
}

// CreateServiceAccountAdminRequest defines model for CreateServiceAccountAdminRequest.
type CreateServiceAccountAdminRequest struct {
	// Authority The authority level of the service account.
	Authority ServiceAccountAuthority `json:"authority"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// Name The name of the service account.
	Name string `json:"name"`
}

// CreateTransformationRequest defines model for CreateTransformationRequest.
type CreateTransformationRequest struct {
	// Default Indicates if this transformation is the default one.
	Default bool `json:"default"`

	// Height The height of the image in pixels.
	Height int64 `json:"height"`

	// Name The name of the transformation.
	Name string `json:"name"`

	// Width The width of the image in pixels.
	Width int64 `json:"width"`
}

// DeleteTransformationRequest defines model for DeleteTransformationRequest.
type DeleteTransformationRequest struct {
	// ID The unique identifier of the transformation.
	ID uuid.UUID `json:"id"`
}

// Image defines model for Image.
type Image struct {
	// CreatedAt The creation time of the image.
	CreatedAt time.Time `json:"createdAt"`

	// ID The unique identifier of the image.
	ID uuid.UUID `json:"id"`

	// State The current state of the image.
	State ImageState `json:"state"`

	// UpdatedAt The last update time of the image.
	UpdatedAt time.Time `json:"updatedAt"`

	// URLSet URLs for accessing the image and its variants.
	URLSet ImageURLSet `json:"urlSet"`
}

// ImageContentType The content type of the image.
type ImageContentType = images.ContentType

// ImageState The current state of the image.
type ImageState = images.State

// ImageURLSet URLs for accessing the image and its variants.
type ImageURLSet struct {
	// OriginalURL The original URL of the image.
	OriginalURL string `json:"originalUrl"`

	// Transformations List of URLs for the image with applied transformations.
	Transformations []VariantURL `json:"transformations"`
}

// Images defines model for Images.
type Images struct {
	Items []Image `json:"items"`

	// Total The total number of images.
	Total int64 `json:"total"`
}

// PresignedURL defines model for PresignedUrl.
type PresignedURL struct {
	// ExpiresAt The expiration time of the presigned URL.
	ExpiresAt time.Time `json:"expiresAt"`

	// ImageID The unique identifier of the image.
	ImageID uuid.UUID `json:"imageId"`

	// UploadURL The presigned URL for uploading the image. Check https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html for more details.
	UploadURL string `json:"uploadUrl"`
}

// Project defines model for Project.
type Project struct {
	// CreatedAt The creation time of the project.
	CreatedAt time.Time `json:"createdAt"`

	// ID The unique identifier of the project.
	ID uuid.UUID `json:"id"`

	// Name The name of the project.
	Name string `json:"name"`

	// Transformations List of transformations to apply to the project.
	Transformations []Transformation `json:"transformations"`

	// UpdatedAt The last update time of the project.
	UpdatedAt time.Time `json:"updatedAt"`
}

// Projects defines model for Projects.
type Projects struct {
	Items []Project `json:"items"`

	// Total The total number of projects.
	Total int64 `json:"total"`
}

// ReprocessImagesAdminRequest defines model for ReprocessImagesAdminRequest.
type ReprocessImagesAdminRequest struct {
	// ImageIDs List of image IDs to reprocess. If not provided and reprocessAll is true, all images in the project will be reprocessed.
	ImageIDs []uuid.UUID `json:"imageIds,omitempty"`

	// ReprocessAll If true, reprocess all images in the project. Takes precedence over imageIds.
	ReprocessAll bool `json:"reprocessAll,omitempty"`
}

// ServiceAccount defines model for ServiceAccount.
type ServiceAccount struct {
	// APIKey The API key for the service account.
	APIKey string `json:"apiKey"`

	// Authority The authority level of the service account.
	Authority ServiceAccountAuthority `json:"authority"`

	// CreatedAt The creation time of the service account.
	CreatedAt time.Time `json:"createdAt"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// ID The unique identifier of the service account.
	ID uuid.UUID `json:"id"`

	// Name The name of the service account.
	Name string `json:"name"`

	// UpdatedAt The last update time of the service account.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ServiceAccountAuthority The authority level of the service account.
type ServiceAccountAuthority = serviceaccounts.Authority

// ServiceAccounts defines model for ServiceAccounts.
type ServiceAccounts struct {
	Items []ServiceAccount `json:"items"`
}

// Transformation defines model for Transformation.
type Transformation struct {
	// CreatedAt The creation time of the transformation.
	CreatedAt time.Time `json:"createdAt"`

	// Default Indicates if this transformation is the default one.
	Default bool `json:"default"`

	// Height The height of the image in pixels.
	Height int64 `json:"height"`

	// ID The unique identifier of the transformation.
	ID uuid.UUID `json:"id"`

	// Name The name of the transformation.
	Name string `json:"name"`

	// UpdatedAt The last update time of the transformation.
	UpdatedAt time.Time `json:"updatedAt"`

	// Width The width of the image in pixels.
	Width int64 `json:"width"`
}

// UpdateProjectAdminRequest defines model for UpdateProjectAdminRequest.
type UpdateProjectAdminRequest struct {
	// Name The name of the project.
	Name            *string `json:"name,omitempty"`
	Transformations struct {
		// Add List of transformations to add to the project.
		Add []CreateTransformationRequest `json:"add,omitempty"`

		// Modify List of transformations to modify in the project.
		Modify []UpdateTransformationRequest `json:"modify,omitempty"`

		// Remove List of transformations to remove from the project.
		Remove []DeleteTransformationRequest `json:"remove,omitempty"`
	} `json:"transformations,omitempty"`
}

// UpdateServiceAccountAdminRequest defines model for UpdateServiceAccountAdminRequest.
type UpdateServiceAccountAdminRequest struct {
	// Authority The authority level of the service account.
	Authority *ServiceAccountAuthority `json:"authority,omitempty"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// Name The name of the service account.
	Name *string `json:"name,omitempty"`
}

// UpdateTransformationRequest defines model for UpdateTransformationRequest.
type UpdateTransformationRequest struct {
	// Default Indicates if this transformation is the default one.
	Default *bool `json:"default,omitempty"`

	// Height The height of the image in pixels.
	Height *int64 `json:"height,omitempty"`

	// ID The unique identifier of the transformation.
	ID uuid.UUID `json:"id"`

	// Name The name of the transformation.
	Name *string `json:"name,omitempty"`

	// Width The width of the image in pixels.
	Width *int64 `json:"width,omitempty"`
}

// User defines model for User.
type User struct {
	// Authority The authority level of the user.
	Authority UserAuthority `json:"authority"`

	// CreatedAt The creation time of the user.
	CreatedAt time.Time `json:"createdAt"`

	// Email The email address of the user.
	Email string `json:"email"`

	// ID The unique identifier of the user.
	ID uuid.UUID `json:"id"`

	// Nickname The nickname of the user.
	Nickname string `json:"nickname"`

	// PhotoURL The photo URL of the user.
	PhotoURL string `json:"photoUrl"`

	// UpdatedAt The last update time of the user.
	UpdatedAt time.Time `json:"updatedAt"`
}

// UserAuthority The authority level of the user.
type UserAuthority = users.Authority

// VariantURL defines model for VariantUrl.
type VariantURL struct {
	// TransformationID The unique identifier of the transformation.
	TransformationID uuid.UUID `json:"transformationId"`

	// TransformationName The name of the transformation.
	TransformationName string `json:"transformationName"`

	// URL The URL of the image with the applied transformation.
	URL string `json:"url"`
}

// ImageIDPath defines model for ImageIdPath.
type ImageIDPath = uuid.UUID

// LimitQuery defines model for LimitQuery.
type LimitQuery = int64

// OffsetQuery defines model for OffsetQuery.
type OffsetQuery = int64

// ProjectIDPath defines model for ProjectIdPath.
type ProjectIDPath = uuid.UUID

// ServiceAccountIDPath defines model for ServiceAccountIdPath.
type ServiceAccountIDPath = uuid.UUID

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = AppError

// ListProjectsAdminParams defines parameters for ListProjectsAdmin.
type ListProjectsAdminParams struct {
	// Offset Offset for pagination
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Limit for pagination
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`
}

// FinishGoogleSignInParams defines parameters for FinishGoogleSignIn.
type FinishGoogleSignInParams struct {
	// Code The authorization code returned by Google after sign-in.
	Code string `form:"code" json:"code"`
}

// CreateProjectAdminJSONRequestBody defines body for CreateProjectAdmin for application/json ContentType.
type CreateProjectAdminJSONRequestBody = CreateProjectAdminRequest

// UpdateProjectAdminJSONRequestBody defines body for UpdateProjectAdmin for application/json ContentType.
type UpdateProjectAdminJSONRequestBody = UpdateProjectAdminRequest

// ReprocessImagesAdminJSONRequestBody defines body for ReprocessImagesAdmin for application/json ContentType.
type ReprocessImagesAdminJSONRequestBody = ReprocessImagesAdminRequest

// CreateServiceAccountAdminJSONRequestBody defines body for CreateServiceAccountAdmin for application/json ContentType.
type CreateServiceAccountAdminJSONRequestBody = CreateServiceAccountAdminRequest

// UpdateServiceAccountAdminJSONRequestBody defines body for UpdateServiceAccountAdmin for application/json ContentType.
type UpdateServiceAccountAdminJSONRequestBody = UpdateServiceAccountAdminRequest

// CreateUploadURLJSONRequestBody defines body for CreateUploadURL for application/json ContentType.
type CreateUploadURLJSONRequestBody = CreatePresignedURLRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all projects
	// (GET /api/v1/admin/projects)
	ListProjectsAdmin(ctx echo.Context, params ListProjectsAdminParams) error
	// Create a new project
	// (POST /api/v1/admin/projects)
	CreateProjectAdmin(ctx echo.Context) error
	// Get project details
	// (GET /api/v1/admin/projects/{projectId})
	GetProjectAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Update project details
	// (PUT /api/v1/admin/projects/{projectId})
	UpdateProjectAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Reprocess multiple images in a project
	// (POST /api/v1/admin/projects/{projectId}/images/reprocess)
	ReprocessImagesAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// List service accounts of a project
	// (GET /api/v1/admin/projects/{projectId}/service-accounts)
	ListServiceAccountsAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Create a new service account for a project
	// (POST /api/v1/admin/projects/{projectId}/service-accounts)
	CreateServiceAccountAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Delete a service account
	// (DELETE /api/v1/admin/projects/{projectId}/service-accounts/{serviceAccountId})
	DeleteServiceAccountAdmin(ctx echo.Context, projectID ProjectIDPath, serviceAccountID ServiceAccountIDPath) error
	// Get service account details
	// (GET /api/v1/admin/projects/{projectId}/service-accounts/{serviceAccountId})
	GetServiceAccountAdmin(ctx echo.Context, projectID ProjectIDPath, serviceAccountID ServiceAccountIDPath) error
	// Update a service account
	// (PUT /api/v1/admin/projects/{projectId}/service-accounts/{serviceAccountId})
	UpdateServiceAccountAdmin(ctx echo.Context, projectID ProjectIDPath, serviceAccountID ServiceAccountIDPath) error
	// Start Google Sign-In
	// (GET /api/v1/auth/google/sign-in)
	StartGoogleSignIn(ctx echo.Context) error
	// Finish Google Sign-In
	// (GET /api/v1/auth/google/sign-in/callback)
	FinishGoogleSignIn(ctx echo.Context, params FinishGoogleSignInParams) error
	// Get project details
	// (GET /api/v1/projects/{projectId})
	GetProject(ctx echo.Context, projectID ProjectIDPath) error
	// Issue a presigned URL for uploading an image
	// (POST /api/v1/projects/{projectId}/images/presigned-url)
	CreateUploadURL(ctx echo.Context, projectID ProjectIDPath) error
	// Get image details
	// (GET /api/v1/projects/{projectId}/images/{imageId})
	GetImage(ctx echo.Context, projectID ProjectIDPath, imageID ImageIDPath) error
	// Get current user details
	// (GET /api/v1/users/me)
	GetCurrentUser(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListProjectsAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) ListProjectsAdmin(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsAdminParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProjectsAdmin(ctx, params)
	return err
}

// CreateProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProjectAdmin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProjectAdmin(ctx)
	return err
}

// GetProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) GetProjectAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProjectAdmin(ctx, projectID)
	return err
}

// UpdateProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProjectAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProjectAdmin(ctx, projectID)
	return err
}

// ReprocessImagesAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) ReprocessImagesAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReprocessImagesAdmin(ctx, projectID)
	return err
}

// ListServiceAccountsAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) ListServiceAccountsAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListServiceAccountsAdmin(ctx, projectID)
	return err
}

// CreateServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) CreateServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateServiceAccountAdmin(ctx, projectID)
	return err
}

// DeleteServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// ------------- Path parameter "serviceAccountId" -------------
	var serviceAccountID ServiceAccountIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceAccountId", ctx.Param("serviceAccountId"), &serviceAccountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceAccountId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteServiceAccountAdmin(ctx, projectID, serviceAccountID)
	return err
}

// GetServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) GetServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// ------------- Path parameter "serviceAccountId" -------------
	var serviceAccountID ServiceAccountIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceAccountId", ctx.Param("serviceAccountId"), &serviceAccountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceAccountId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServiceAccountAdmin(ctx, projectID, serviceAccountID)
	return err
}

// UpdateServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// ------------- Path parameter "serviceAccountId" -------------
	var serviceAccountID ServiceAccountIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceAccountId", ctx.Param("serviceAccountId"), &serviceAccountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceAccountId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateServiceAccountAdmin(ctx, projectID, serviceAccountID)
	return err
}

// StartGoogleSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) StartGoogleSignIn(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StartGoogleSignIn(ctx)
	return err
}

// FinishGoogleSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) FinishGoogleSignIn(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FinishGoogleSignInParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, true, "code", ctx.QueryParams(), &params.Code)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FinishGoogleSignIn(ctx, params)
	return err
}

// GetProject converts echo context to params.
func (w *ServerInterfaceWrapper) GetProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProject(ctx, projectID)
	return err
}

// CreateUploadURL converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUploadURL(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUploadURL(ctx, projectID)
	return err
}

// GetImage converts echo context to params.
func (w *ServerInterfaceWrapper) GetImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// ------------- Path parameter "imageId" -------------
	var imageID ImageIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "imageId", ctx.Param("imageId"), &imageID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter imageId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetImage(ctx, projectID, imageID)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/v1/admin/projects", wrapper.ListProjectsAdmin)
	router.POST(baseURL+"/api/v1/admin/projects", wrapper.CreateProjectAdmin)
	router.GET(baseURL+"/api/v1/admin/projects/:projectId", wrapper.GetProjectAdmin)
	router.PUT(baseURL+"/api/v1/admin/projects/:projectId", wrapper.UpdateProjectAdmin)
	router.POST(baseURL+"/api/v1/admin/projects/:projectId/images/reprocess", wrapper.ReprocessImagesAdmin)
	router.GET(baseURL+"/api/v1/admin/projects/:projectId/service-accounts", wrapper.ListServiceAccountsAdmin)
	router.POST(baseURL+"/api/v1/admin/projects/:projectId/service-accounts", wrapper.CreateServiceAccountAdmin)
	router.DELETE(baseURL+"/api/v1/admin/projects/:projectId/service-accounts/:serviceAccountId", wrapper.DeleteServiceAccountAdmin)
	router.GET(baseURL+"/api/v1/admin/projects/:projectId/service-accounts/:serviceAccountId", wrapper.GetServiceAccountAdmin)
	router.PUT(baseURL+"/api/v1/admin/projects/:projectId/service-accounts/:serviceAccountId", wrapper.UpdateServiceAccountAdmin)
	router.GET(baseURL+"/api/v1/auth/google/sign-in", wrapper.StartGoogleSignIn)
	router.GET(baseURL+"/api/v1/auth/google/sign-in/callback", wrapper.FinishGoogleSignIn)
	router.GET(baseURL+"/api/v1/projects/:projectId", wrapper.GetProject)
	router.POST(baseURL+"/api/v1/projects/:projectId/images/presigned-url", wrapper.CreateUploadURL)
	router.GET(baseURL+"/api/v1/projects/:projectId/images/:imageId", wrapper.GetImage)
	router.GET(baseURL+"/api/v1/users/me", wrapper.GetCurrentUser)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce2/juBH/KoTaP2XLedxiL0DR+pJc4Da3uxfHLdrD4sBIY4sbidSSVLK+wN+9ICnJ",
	"elCynNg572L/syW+ZuY3T5J6cnwWJ4wClcI5e3ISzHEMErj+N4nxAibBByxD9TcA4XOSSMKoc+bchoAm",
	"F4jNkQwBEdV06LgOUe8S1cN1KI7BOXOIGcZxHQ6fU8IhcM4kT8F1hB9CjNXY8AXHSaRanx6/gTcnp/PB",
	"D6MgGJwe4dHg7duju4H/449Hp6dHdyd+8IPjOnPGYyydMydNiRpaLhPVW0hO6MJxnS+DBRtkD1WT4Ww2",
	"uSg/H5A4YVwaqhWBzoLIML0b+iz2FowtIvD02KvVynWuSUzkrynwZZMT+h2aM44SvCAU68cZJz7rLgUr",
	"ItXUsRJ+NCoRRah8c7qmilAJC+COWsn7+VxA21LMy35rYbqtfTE91/KBs0/gy34QSUxjJBl6DIkfrnGD",
	"7iBidCFa8JPks3zVCJoCfyA+jH2fpbQny4Tpg7Dp1MIfURv5K2bTSi1dJIwK0BboknPGb7In6oHPqASq",
	"B8NJEhFfI9z7JBT3nkp0/pXD3Dlz/uKtDZxn3gpvnCR6YCOYqgD0C8R8P+UcAhSkikwtDMVTEFIDPxtJ",
	"TVQMpujjLAEuiVm8zwJl9hoyNlOot0rUWlc5W3Acx1gSH4WYBpHhbck4jPqopKvnfKdh0TGrwk2/eZ2f",
	"xhe/31z+Oruc3jZkv3KdGITAi9bZ8tflEacsBqSEEsEXBLVmtQlWZST/5qzbZawt0fux6MzulLVQqzvn",
	"gCV84CDIgkIw49FNJkOLrDSubvUQ3ejRXvG81H7lOnMStbBdKbTmd6bSqqUygXeA0iRiOIBgWOGP8aSJ",
	"lkOD35JjKgwMCKNqRmHzR0Lq6SqN9SqEmlopzlL9WDtuNJkjyqQCxAMJIHBRAHOcRrI2iECPJIrU4rX2",
	"mbUTCbGo2pbHN6NR+HY0stJgHmDO8bJiJ8Q9SQZMU4GjQcIUrLmxYHUkFPx2K5LrAoH2IeMgJrQVBLSX",
	"BDN3VJXaL0uUTbERxbQbrlU/0b1gnMqQcSKXmzBbG7TotlI0JITDWNoJ128NfiRZ86DmmJBk90CrHDke",
	"HZ8MjkaD0dHt0fHZaHQ2Gv2v7E4CLGGgxrRhpJ8kLO5xPX+8HGTvB9n7fpJxS1xtl9JtRS1aBZRpUZOU",
	"CQ2U7wKBiKKFiLq2qichFGrIKFTIm+NIQLG6O8YiwFQtLwSyCFuEad5VQnZEKErIF4hEZfi3Pd1NPzlV",
	"SauKqctSPJKgLUbSr/pQ8mbUM5a1ACGXXr6Sgrs2XFxABL1xQQI7WSkln1NAJAAqyZwA78PCw4x3y/wk",
	"gZVl2pNafLHWsKDNJOnXdYNU5J87MkBbC8iygAOUi+sIiWW/EGeqW65cJ02CLnlEWEhk2uxVJCmPpiB7",
	"LX1mmlpg6JbQVaYsZ0wxTStez6uRogWfpgFS3Zu8oGmsl6IeeJ8SUBI2f0zIZ34/wl2illALCz1bWJgh",
	"oQsEHAIRMg6eHgW4l9wvzG+h6CojzDwd1uLbEiDsNKtsiUqkmdhK9H/Gk9vJu6vfZx+u348VhD/cvD+/",
	"nE4n764c17m5HF/8t0q0efQqBBdoLwOoQevs5lrozAn7PgiRp4bGAWEaICIFesCcYCq1H6paNsbJglAc",
	"zXhk52PeAM1urjv0KJQyEWeelz3RJOddvS0SiI7koaB0Td8jkWEe99fzgkoe0KWf/zbMURyo5wJ1dS1z",
	"q7nyVgUVFnebr6zXEo1baqzOdSSTuEVw+hWiaXxnXEKGqloOv30kYhacT22juZzeNik30b3YMrxP8jEV",
	"DHbpVbNK8LfpWk0+36rbFaZq1TIdKkZkiM5D8O9RruEB88UQP4ohjvEfjOp5x/rn9MSLVAIhvVQAX6Qk",
	"AK+MhZke/L3GyTCUcaSnjBlXSYXEpBYnFzZFTaZmMYv7+z0s/4bv/KPjk43p07rOv+aEW0KgHb0mad5J",
	"EGjNzF83DLQu4SDRuqdixxYupl5aqpemSnP3stvV3MtmwJ8Zye4aV9uEpVkq2sf7ZTJ5sf/LZfsyD5gx",
	"7VV84A0knKmAzAQA3UWzzEx1ANOEO5MLDUmej90okuqAr3g9jiJdtOEpuAirP3otiNDK7ldePy36tdZQ",
	"D9Jq2Iq32TaU2S2+EL1rukrKa+ZVymVZeatWM5tn3C26tfN5iG7xPQjldH0IgPqA2ANwlAu/RzFti9J0",
	"A5DVequlcJuQf8HSrkjjDxN0D8si+O6scra5ZncnteHnOOHO5b7IGR9kpXrrCKGTP19xpPDiYvyz3fO+",
	"EPcMN71WOjfX8Y8bzcO4rKlNsosxUQQPEHVRndVZfp5dX/8+Pj+/nE5NkeWfl+e3+YNKgaX2rhtJ2YzZ",
	"hGI4LhHbD1lEpBJzOD06rhRmagM7zeMSL45pagZ5U+nBjGkTXS3I3Ene0lXcf5Fx+ta3n771bZR9b7A9",
	"0+DuDa9/2oZfH9u+1W7gTPf/M08dWBPxWhQaBNtl50Hw3Ny8a9f8uWdCXCdmAZkvt6LBdKlnC33JMGLd",
	"NRkcYvYAW5FhuqA5Z/GzCOnarX7BGZ2qHrwkgzKc/n4Y5lUPw7RI4fthl+/Rxtd8nKfl+MlMAH+BGVHd",
	"X1wtSQXwXZZIYkxa6rP6lXLhHIRon149+UdpX3knNY/mNIcJf+Lfd6hA9radqE8spAGzCiYJmWTtW4Pq",
	"bXnPvzm2bctfdxN6/y/b71/zi5MdBvw7Rakt9C44Xy2hGDiXuNcWpLep9/NKKwW5WT1lfPHL5J3jOlf6",
	"GHylgHJlPRlfA6YAvsNqiR5Os7F0lqJhxqpGevLNu67myfg9ps1telw/tWOOzKi/9mMzPVScgwApvHw5",
	"Xad7aorVQICVSYaapv6o0QidM0s0Z7CIrrCER7zU+xX6aAGmeEHoIiOdg2Ap980hGElkBM2+jus8ABdm",
	"3NHwSDGXJUBxQpwz52Q4GirvroSvMe3hhHgPRx5WeYCXlLY7F+awllKAAu86fcr3RHXqoMdaX3D8ze7f",
	"10288l27lbuxeemS4Opj7SbT8Wi0s/tLxUav5f7SNNUn0+ZpFC0RB8kJPEBQ7MbWqoK2WYple9XbV/r0",
	"aBrHmC/z3BRH0Xpk15F4IbS91Mz+qNweExbBNK9kZFfWQMifWLDcGaPa735Y7prtQUIbBZR5s5yJO5OO",
	"IRxhROGxGLwpoJXbolPeU3HpctWqX1cgazLcTruqt0dfQ2O2V5j8rNTOJHMFsjG2VXNSC8ebVcWdMH33",
	"itde/jwQxctCx72J2TCgh6R7qWB2dNkrDj7omMhqW21HYQ4UJF2ndvYMk+yg8CaUSE4WC+AQoDss/bCI",
	"bLJ1N3fZng+YghkoTiNJkghKB1vwS224V6v+dQdNtb3Xg7fu9b3i/la+VjTdcXhUH13lBl2i7I6XLLXw",
	"A1XsjRdZ96zd9c3+nkFYTVz7CcbqmwX6MsnO1dt7qn8UYmUSuQjMFZ4qwMxu0B4Atjlnsn4W4xWtxUZ0",
	"GJ7tDx2G9wg3JrDZh7Y4/LvotrLze4nq2+bYMro/NFHuKzn4atxDnirsywBkqUIfA1B2BqkM8yKoIAs6",
	"ILQ1pptKzOWVbjslCzox5ZYSd09Gx8063w0EhIMv9f0khkx/pAYY6BFCwEH2obBr5hfH4exVUX1kwYxX",
	"lNjVQ+X+GiOvxVivcK52xXTNkubMOcP11uAmfns+jqI77N+3Mv5nQokIa5yvqXLrrsQfZrdQf7GHg0w5",
	"VXnIMl80nkvgKFvKsOUbX6pz5+eg6gz+2AcZFfXI7rQRaordZnW7gseaSF1YfiVwGLFtg45n1s2+l8xe",
	"XjLL17lRHnkRpbiHOcj2cbqSLnOLcnZzfdCplu0TV3svtJWuHW/CCBEihaB5tXhnEJmoCXQe1X7HFlNT",
	"USlhx9z07o2cp+z2UKdqT7I59hyxlb/NuVc7kN2G720FTI1sHzagOnKnFPUeuWf2gNsEdW6+WaGN+R75",
	"p8fvz778SxraA+6Di9YJmr5N9QP+YI9SzvPPfegW2R7ymeNpJGYj5QebnfV10uJR/oWF4oFh0vq/CXhX",
	"H1f/DwAA//+h5akZoVYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
