// Package web provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package web

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/isutare412/imageer/pkg/images"
	"github.com/isutare412/imageer/pkg/serviceaccounts"
	"github.com/isutare412/imageer/pkg/users"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// AppError defines model for AppError.
type AppError struct {
	// CodeID Error code ID for programmatic handling
	CodeID int64 `json:"codeId"`

	// CodeName Error code name for programmatic handling
	CodeName string `json:"codeName"`

	// Message Error message
	Message string `json:"message"`
}

// CreatePresetRequest defines model for CreatePresetRequest.
type CreatePresetRequest struct {
	// Anchor The anchor position for image cropping.
	Anchor *ImageAnchor `json:"anchor,omitempty"`

	// Default Indicates if this preset is the default one.
	Default bool `json:"default"`

	// Fit The fit mode for image conversion:
	//   - COVER: Scale the image to cover the target dimensions. Some parts may be cropped.
	//   - CONTAIN: Scale the image to fit within the target dimensions. No cropping occurs. Empty areas may be filled with background color.
	//   - FILL: Scale the image to fill the target dimensions. The image may be distorted.
	Fit *ImageFit `json:"fit,omitempty"`

	// Format The content type of the image.
	Format *ImageFormat `json:"format,omitempty"`

	// Height The height of the image in pixels.
	Height *int64 `json:"height,omitempty"`

	// Name The name of the preset.
	Name string `json:"name"`

	// Quality The quality of the image (1-100). Default is 80.
	Quality *int64 `json:"quality,omitempty"`

	// Width The width of the image in pixels.
	Width *int64 `json:"width,omitempty"`
}

// CreateProjectAdminRequest defines model for CreateProjectAdminRequest.
type CreateProjectAdminRequest struct {
	// Name The name of the project.
	Name    string                `json:"name"`
	Presets []CreatePresetRequest `json:"presets,omitempty"`
}

// CreateServiceAccountAdminRequest defines model for CreateServiceAccountAdminRequest.
type CreateServiceAccountAdminRequest struct {
	// AccessScope The access scope of the service account.
	AccessScope ServiceAccountAccessScope `json:"accessScope"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// Name The name of the service account.
	Name string `json:"name"`

	// ProjectIDs List of project IDs to associate with the service account.
	ProjectIDs []string `json:"projectIds,omitempty"`
}

// CreateUploadURLRequest defines model for CreateUploadUrlRequest.
type CreateUploadURLRequest struct {
	// FileName The name of the file to be uploaded.
	FileName string `json:"fileName"`

	// Format The content type of the image.
	Format ImageFormat `json:"format"`

	// PresetNames List of preset names to apply to the image. If not provided, default presets will be applied.
	PresetNames []string `json:"presetNames,omitempty"`
}

// Image defines model for Image.
type Image struct {
	// CreatedAt The creation time of the image.
	CreatedAt time.Time `json:"createdAt"`

	// Format The content type of the image.
	Format ImageFormat `json:"format"`

	// ID The unique identifier of the image.
	ID string `json:"id"`

	// State The current state of the image.
	State ImageState `json:"state"`

	// UpdatedAt The last update time of the image.
	UpdatedAt time.Time `json:"updatedAt"`

	// URL The URL of the original image.
	URL string `json:"url"`

	// Variants List of image variants with applied presets.
	Variants []ImageVariant `json:"variants,omitempty"`
}

// ImageAnchor The anchor position for image cropping.
type ImageAnchor = images.Anchor

// ImageFit The fit mode for image conversion:
//   - COVER: Scale the image to cover the target dimensions. Some parts may be cropped.
//   - CONTAIN: Scale the image to fit within the target dimensions. No cropping occurs. Empty areas may be filled with background color.
//   - FILL: Scale the image to fill the target dimensions. The image may be distorted.
type ImageFit = images.Fit

// ImageFormat The content type of the image.
type ImageFormat = images.Format

// ImageState The current state of the image.
type ImageState = images.State

// ImageVariant defines model for ImageVariant.
type ImageVariant struct {
	// CreatedAt The creation time of the image variant.
	CreatedAt time.Time `json:"createdAt"`

	// Format The content type of the image.
	Format ImageFormat `json:"format"`

	// ID The unique identifier of the image variant.
	ID string `json:"id"`

	// PresetID The unique identifier of the preset.
	PresetID string `json:"presetId"`

	// PresetName The name of the preset.
	PresetName string `json:"presetName"`

	// State The current state of the image variant.
	State ImageVariantState `json:"state"`

	// UpdatedAt The time when the image variant was updated.
	UpdatedAt time.Time `json:"updatedAt"`

	// URL The URL of the image with the applied preset.
	URL string `json:"url"`
}

// ImageVariantState The current state of the image variant.
type ImageVariantState = images.VariantState

// Images defines model for Images.
type Images struct {
	Items []Image `json:"items"`

	// Total The total number of images.
	Total int64 `json:"total"`
}

// Preset defines model for Preset.
type Preset struct {
	// Anchor The anchor position for image cropping.
	Anchor *ImageAnchor `json:"anchor,omitempty"`

	// CreatedAt The creation time of the preset.
	CreatedAt time.Time `json:"createdAt"`

	// Default Indicates if this preset is the default one.
	Default bool `json:"default"`

	// Fit The fit mode for image conversion:
	//   - COVER: Scale the image to cover the target dimensions. Some parts may be cropped.
	//   - CONTAIN: Scale the image to fit within the target dimensions. No cropping occurs. Empty areas may be filled with background color.
	//   - FILL: Scale the image to fill the target dimensions. The image may be distorted.
	Fit *ImageFit `json:"fit,omitempty"`

	// Format The content type of the image.
	Format ImageFormat `json:"format"`

	// Height The height of the image in pixels.
	Height *int64 `json:"height,omitempty"`

	// ID The unique identifier of the preset.
	ID string `json:"id"`

	// Name The name of the preset.
	Name string `json:"name"`

	// Quality The quality of the image (1-100).
	Quality int64 `json:"quality"`

	// UpdatedAt The last update time of the preset.
	UpdatedAt time.Time `json:"updatedAt"`

	// Width The width of the image in pixels.
	Width *int64 `json:"width,omitempty"`
}

// Project defines model for Project.
type Project struct {
	// CreatedAt The creation time of the project.
	CreatedAt time.Time `json:"createdAt"`

	// ID The unique identifier of the project.
	ID string `json:"id"`

	// ImageCount The total number of images in the project.
	ImageCount int64 `json:"imageCount"`

	// Name The name of the project.
	Name string `json:"name"`

	// Presets List of presets to apply to images of the project.
	Presets []Preset `json:"presets"`

	// UpdatedAt The last update time of the project.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ProjectReference defines model for ProjectReference.
type ProjectReference struct {
	// ID The unique identifier of the project.
	ID string `json:"id"`

	// Name The name of the project.
	Name string `json:"name"`
}

// Projects defines model for Projects.
type Projects struct {
	Items []Project `json:"items"`

	// Total The total number of projects.
	Total int64 `json:"total"`
}

// ReprocessImagesAdminRequest defines model for ReprocessImagesAdminRequest.
type ReprocessImagesAdminRequest struct {
	// ImageIDs List of image IDs to reprocess. If not provided and reprocessAll is true, all images in the project will be reprocessed.
	ImageIDs []string `json:"imageIds,omitempty"`

	// ReprocessAll If true, reprocess all images in the project. Takes precedence over imageIds.
	ReprocessAll bool `json:"reprocessAll,omitempty"`
}

// ServiceAccount defines model for ServiceAccount.
type ServiceAccount struct {
	// AccessScope The access scope of the service account.
	AccessScope ServiceAccountAccessScope `json:"accessScope"`

	// CreatedAt The creation time of the service account.
	CreatedAt time.Time `json:"createdAt"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// ID The unique identifier of the service account.
	ID string `json:"id"`

	// Name The name of the service account.
	Name string `json:"name"`

	// Projects List of projects associated with the service account.
	Projects []ProjectReference `json:"projects"`

	// UpdatedAt The last update time of the service account.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ServiceAccountAccessScope The access scope of the service account.
type ServiceAccountAccessScope = serviceaccounts.AccessScope

// ServiceAccountWithAPIKey defines model for ServiceAccountWithApiKey.
type ServiceAccountWithAPIKey struct {
	// AccessScope The access scope of the service account.
	AccessScope ServiceAccountAccessScope `json:"accessScope"`

	// APIKey The API key for the service account.
	APIKey string `json:"apiKey"`

	// CreatedAt The creation time of the service account.
	CreatedAt time.Time `json:"createdAt"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// ID The unique identifier of the service account.
	ID string `json:"id"`

	// Name The name of the service account.
	Name string `json:"name"`

	// Projects List of projects associated with the service account.
	Projects []ProjectReference `json:"projects"`

	// UpdatedAt The last update time of the service account.
	UpdatedAt time.Time `json:"updatedAt"`
}

// ServiceAccounts defines model for ServiceAccounts.
type ServiceAccounts struct {
	Items []ServiceAccount `json:"items"`

	// Total The total number of service accounts.
	Total int64 `json:"total"`
}

// UpdateProjectAdminRequest defines model for UpdateProjectAdminRequest.
type UpdateProjectAdminRequest struct {
	// Name The name of the project.
	Name    *string               `json:"name,omitempty"`
	Presets []UpsertPresetRequest `json:"presets,omitempty"`
}

// UpdateServiceAccountAdminRequest defines model for UpdateServiceAccountAdminRequest.
type UpdateServiceAccountAdminRequest struct {
	// AccessScope The access scope of the service account.
	AccessScope *ServiceAccountAccessScope `json:"accessScope,omitempty"`

	// ExpireAt The expiration time of the service account token.
	ExpireAt *time.Time `json:"expireAt,omitempty"`

	// Name The name of the service account.
	Name *string `json:"name,omitempty"`

	// ProjectIDs List of project IDs to associate with the service account.
	ProjectIDs []string `json:"projectIds,omitempty"`
}

// UploadURL defines model for UploadUrl.
type UploadURL struct {
	// ExpiresAt The expiration time of the presigned URL.
	ExpiresAt time.Time `json:"expiresAt"`

	// Header Additional headers required for the upload request.
	Header map[string]string `json:"header"`

	// ImageID The unique identifier of the image.
	ImageID string `json:"imageId"`

	// URL The presigned URL for uploading the image. It must be called with PUT method. Check https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html for more details.
	URL string `json:"url"`
}

// UpsertPresetRequest If id is provided, the preset will be updated; otherwise, a new preset
// will be created. All existing presets not included in the upsert list
// will be deleted.
type UpsertPresetRequest struct {
	// Anchor The anchor position for image cropping.
	Anchor *ImageAnchor `json:"anchor,omitempty"`

	// Default Indicates if this preset is the default one.
	Default *bool `json:"default,omitempty"`

	// Fit The fit mode for image conversion:
	//   - COVER: Scale the image to cover the target dimensions. Some parts may be cropped.
	//   - CONTAIN: Scale the image to fit within the target dimensions. No cropping occurs. Empty areas may be filled with background color.
	//   - FILL: Scale the image to fill the target dimensions. The image may be distorted.
	Fit *ImageFit `json:"fit,omitempty"`

	// Format The content type of the image.
	Format *ImageFormat `json:"format,omitempty"`

	// Height The height of the image in pixels.
	Height *int64 `json:"height,omitempty"`

	// ID The unique identifier of the preset.
	ID *string `json:"id,omitempty"`

	// Name The name of the preset.
	Name *string `json:"name,omitempty"`

	// Quality The quality of the image (1-100). Default is 80.
	Quality *int64 `json:"quality,omitempty"`

	// Width The width of the image in pixels.
	Width *int64 `json:"width,omitempty"`
}

// User defines model for User.
type User struct {
	// CreatedAt The creation time of the user.
	CreatedAt time.Time `json:"createdAt"`

	// Email The email address of the user.
	Email string `json:"email"`

	// ID The unique identifier of the user.
	ID string `json:"id"`

	// Nickname The nickname of the user.
	Nickname string `json:"nickname"`

	// PhotoURL The photo URL of the user.
	PhotoURL string `json:"photoUrl"`

	// Role The role of the user.
	Role UserRole `json:"role"`

	// UpdatedAt The last update time of the user.
	UpdatedAt time.Time `json:"updatedAt"`
}

// UserRole The role of the user.
type UserRole = users.Role

// ImageIDPath defines model for ImageIdPath.
type ImageIDPath = string

// LimitQuery defines model for LimitQuery.
type LimitQuery = int64

// OffsetQuery defines model for OffsetQuery.
type OffsetQuery = int64

// ProjectIDPath defines model for ProjectIdPath.
type ProjectIDPath = string

// RedirectQuery defines model for RedirectQuery.
type RedirectQuery = string

// ServiceAccountIDPath defines model for ServiceAccountIdPath.
type ServiceAccountIDPath = string

// WaitUntilProcessedQuery defines model for WaitUntilProcessedQuery.
type WaitUntilProcessedQuery = bool

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = AppError

// ListProjectsAdminParams defines parameters for ListProjectsAdmin.
type ListProjectsAdminParams struct {
	// Offset Offset for pagination
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Limit for pagination
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListServiceAccountsAdminParams defines parameters for ListServiceAccountsAdmin.
type ListServiceAccountsAdminParams struct {
	// Offset Offset for pagination
	Offset *OffsetQuery `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Limit for pagination
	Limit *LimitQuery `form:"limit,omitempty" json:"limit,omitempty"`
}

// StartGoogleSignInParams defines parameters for StartGoogleSignIn.
type StartGoogleSignInParams struct {
	// Redirect The path to redirect to after successful sign-in. Defaults to root path if not provided.
	Redirect *RedirectQuery `form:"redirect,omitempty" json:"redirect,omitempty"`
}

// FinishGoogleSignInParams defines parameters for FinishGoogleSignIn.
type FinishGoogleSignInParams struct {
	// Code The authorization code returned by Google after sign-in.
	Code string `form:"code" json:"code"`

	// State The state parameter to prevent CSRF attacks.
	State string `form:"state" json:"state"`
}

// GetImageParams defines parameters for GetImage.
type GetImageParams struct {
	// WaitUntilProcessed Wait until the image processing is completed
	WaitUntilProcessed *WaitUntilProcessedQuery `form:"waitUntilProcessed,omitempty" json:"waitUntilProcessed,omitempty"`
}

// CreateProjectAdminJSONRequestBody defines body for CreateProjectAdmin for application/json ContentType.
type CreateProjectAdminJSONRequestBody = CreateProjectAdminRequest

// UpdateProjectAdminJSONRequestBody defines body for UpdateProjectAdmin for application/json ContentType.
type UpdateProjectAdminJSONRequestBody = UpdateProjectAdminRequest

// ReprocessImagesAdminJSONRequestBody defines body for ReprocessImagesAdmin for application/json ContentType.
type ReprocessImagesAdminJSONRequestBody = ReprocessImagesAdminRequest

// CreateServiceAccountAdminJSONRequestBody defines body for CreateServiceAccountAdmin for application/json ContentType.
type CreateServiceAccountAdminJSONRequestBody = CreateServiceAccountAdminRequest

// UpdateServiceAccountAdminJSONRequestBody defines body for UpdateServiceAccountAdmin for application/json ContentType.
type UpdateServiceAccountAdminJSONRequestBody = UpdateServiceAccountAdminRequest

// CreateUploadURLJSONRequestBody defines body for CreateUploadURL for application/json ContentType.
type CreateUploadURLJSONRequestBody = CreateUploadURLRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all projects
	// (GET /api/v1/admin/projects)
	ListProjectsAdmin(ctx echo.Context, params ListProjectsAdminParams) error
	// Create a new project
	// (POST /api/v1/admin/projects)
	CreateProjectAdmin(ctx echo.Context) error
	// Delete a project
	// (DELETE /api/v1/admin/projects/{projectId})
	DeleteProjectAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Get project details
	// (GET /api/v1/admin/projects/{projectId})
	GetProjectAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Update project details
	// (PUT /api/v1/admin/projects/{projectId})
	UpdateProjectAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// Reprocess multiple images in a project
	// (POST /api/v1/admin/projects/{projectId}/images/reprocess)
	ReprocessImagesAdmin(ctx echo.Context, projectID ProjectIDPath) error
	// List service accounts
	// (GET /api/v1/admin/service-accounts)
	ListServiceAccountsAdmin(ctx echo.Context, params ListServiceAccountsAdminParams) error
	// Create a new service account
	// (POST /api/v1/admin/service-accounts)
	CreateServiceAccountAdmin(ctx echo.Context) error
	// Delete a service account
	// (DELETE /api/v1/admin/service-accounts/{serviceAccountId})
	DeleteServiceAccountAdmin(ctx echo.Context, serviceAccountID ServiceAccountIDPath) error
	// Get service account details
	// (GET /api/v1/admin/service-accounts/{serviceAccountId})
	GetServiceAccountAdmin(ctx echo.Context, serviceAccountID ServiceAccountIDPath) error
	// Update a service account
	// (PUT /api/v1/admin/service-accounts/{serviceAccountId})
	UpdateServiceAccountAdmin(ctx echo.Context, serviceAccountID ServiceAccountIDPath) error
	// Start Google Sign-In
	// (GET /api/v1/auth/google/sign-in)
	StartGoogleSignIn(ctx echo.Context, params StartGoogleSignInParams) error
	// Finish Google Sign-In
	// (GET /api/v1/auth/google/sign-in/callback)
	FinishGoogleSignIn(ctx echo.Context, params FinishGoogleSignInParams) error
	// Sign out the current user
	// (POST /api/v1/auth/sign-out)
	SignOut(ctx echo.Context) error
	// Get project details
	// (GET /api/v1/projects/{projectId})
	GetProject(ctx echo.Context, projectID ProjectIDPath) error
	// Issue a presigned URL for uploading an image
	// (POST /api/v1/projects/{projectId}/images/upload-url)
	CreateUploadURL(ctx echo.Context, projectID ProjectIDPath) error
	// Get image details
	// (GET /api/v1/projects/{projectId}/images/{imageId})
	GetImage(ctx echo.Context, projectID ProjectIDPath, imageID ImageIDPath, params GetImageParams) error
	// Get current user details
	// (GET /api/v1/users/me)
	GetCurrentUser(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListProjectsAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) ListProjectsAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProjectsAdminParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListProjectsAdmin(ctx, params)
	return err
}

// CreateProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) CreateProjectAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateProjectAdmin(ctx)
	return err
}

// DeleteProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteProjectAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteProjectAdmin(ctx, projectID)
	return err
}

// GetProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) GetProjectAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProjectAdmin(ctx, projectID)
	return err
}

// UpdateProjectAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateProjectAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateProjectAdmin(ctx, projectID)
	return err
}

// ReprocessImagesAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) ReprocessImagesAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReprocessImagesAdmin(ctx, projectID)
	return err
}

// ListServiceAccountsAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) ListServiceAccountsAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListServiceAccountsAdminParams
	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", ctx.QueryParams(), &params.Offset)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListServiceAccountsAdmin(ctx, params)
	return err
}

// CreateServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) CreateServiceAccountAdmin(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateServiceAccountAdmin(ctx)
	return err
}

// DeleteServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "serviceAccountId" -------------
	var serviceAccountID ServiceAccountIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceAccountId", ctx.Param("serviceAccountId"), &serviceAccountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceAccountId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteServiceAccountAdmin(ctx, serviceAccountID)
	return err
}

// GetServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) GetServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "serviceAccountId" -------------
	var serviceAccountID ServiceAccountIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceAccountId", ctx.Param("serviceAccountId"), &serviceAccountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceAccountId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetServiceAccountAdmin(ctx, serviceAccountID)
	return err
}

// UpdateServiceAccountAdmin converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateServiceAccountAdmin(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "serviceAccountId" -------------
	var serviceAccountID ServiceAccountIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "serviceAccountId", ctx.Param("serviceAccountId"), &serviceAccountID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter serviceAccountId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateServiceAccountAdmin(ctx, serviceAccountID)
	return err
}

// StartGoogleSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) StartGoogleSignIn(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params StartGoogleSignInParams
	// ------------- Optional query parameter "redirect" -------------

	err = runtime.BindQueryParameter("form", true, false, "redirect", ctx.QueryParams(), &params.Redirect)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter redirect: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StartGoogleSignIn(ctx, params)
	return err
}

// FinishGoogleSignIn converts echo context to params.
func (w *ServerInterfaceWrapper) FinishGoogleSignIn(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params FinishGoogleSignInParams
	// ------------- Required query parameter "code" -------------

	err = runtime.BindQueryParameter("form", true, true, "code", ctx.QueryParams(), &params.Code)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter code: %s", err))
	}

	// ------------- Required query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, true, "state", ctx.QueryParams(), &params.State)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.FinishGoogleSignIn(ctx, params)
	return err
}

// SignOut converts echo context to params.
func (w *ServerInterfaceWrapper) SignOut(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SignOut(ctx)
	return err
}

// GetProject converts echo context to params.
func (w *ServerInterfaceWrapper) GetProject(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetProject(ctx, projectID)
	return err
}

// CreateUploadURL converts echo context to params.
func (w *ServerInterfaceWrapper) CreateUploadURL(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateUploadURL(ctx, projectID)
	return err
}

// GetImage converts echo context to params.
func (w *ServerInterfaceWrapper) GetImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "projectId" -------------
	var projectID ProjectIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", ctx.Param("projectId"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter projectId: %s", err))
	}

	// ------------- Path parameter "imageId" -------------
	var imageID ImageIDPath

	err = runtime.BindStyledParameterWithOptions("simple", "imageId", ctx.Param("imageId"), &imageID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter imageId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetImageParams
	// ------------- Optional query parameter "waitUntilProcessed" -------------

	err = runtime.BindQueryParameter("form", true, false, "waitUntilProcessed", ctx.QueryParams(), &params.WaitUntilProcessed)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter waitUntilProcessed: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetImage(ctx, projectID, imageID, params)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(CookieAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/v1/admin/projects", wrapper.ListProjectsAdmin)
	router.POST(baseURL+"/api/v1/admin/projects", wrapper.CreateProjectAdmin)
	router.DELETE(baseURL+"/api/v1/admin/projects/:projectId", wrapper.DeleteProjectAdmin)
	router.GET(baseURL+"/api/v1/admin/projects/:projectId", wrapper.GetProjectAdmin)
	router.PUT(baseURL+"/api/v1/admin/projects/:projectId", wrapper.UpdateProjectAdmin)
	router.POST(baseURL+"/api/v1/admin/projects/:projectId/images/reprocess", wrapper.ReprocessImagesAdmin)
	router.GET(baseURL+"/api/v1/admin/service-accounts", wrapper.ListServiceAccountsAdmin)
	router.POST(baseURL+"/api/v1/admin/service-accounts", wrapper.CreateServiceAccountAdmin)
	router.DELETE(baseURL+"/api/v1/admin/service-accounts/:serviceAccountId", wrapper.DeleteServiceAccountAdmin)
	router.GET(baseURL+"/api/v1/admin/service-accounts/:serviceAccountId", wrapper.GetServiceAccountAdmin)
	router.PUT(baseURL+"/api/v1/admin/service-accounts/:serviceAccountId", wrapper.UpdateServiceAccountAdmin)
	router.GET(baseURL+"/api/v1/auth/google/sign-in", wrapper.StartGoogleSignIn)
	router.GET(baseURL+"/api/v1/auth/google/sign-in/callback", wrapper.FinishGoogleSignIn)
	router.POST(baseURL+"/api/v1/auth/sign-out", wrapper.SignOut)
	router.GET(baseURL+"/api/v1/projects/:projectId", wrapper.GetProject)
	router.POST(baseURL+"/api/v1/projects/:projectId/images/upload-url", wrapper.CreateUploadURL)
	router.GET(baseURL+"/api/v1/projects/:projectId/images/:imageId", wrapper.GetImage)
	router.GET(baseURL+"/api/v1/users/me", wrapper.GetCurrentUser)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8a3PbuHZ/BYP2QztDvWzHm6jTabW24mjXayuSleTeXM8OREISYpJgANCO1qP/3sGD",
	"FCmCEvVysp18k4jXwXnjnAM8Q5cGEQ1xKDhsP8MIMRRggZn61wvQFPe8PhIz+dfD3GUkEoSGsA3vZhj0",
	"LgGdADHDgMiudehAItsiOcKBIQowbEOip4EOZPhrTBj2YFuwGDuQuzMcIDk3/oaCyJe9z07O8fnp2aT2",
	"qul5tbMWatZev26Na+6bN62zs9b41PVeQQeKeSR7c8FIOIWLhQOvSUDE+xizeRFY1QYmlIEITUmI1GcD",
	"7Fc1JIXWl12hFbZW04ETygIk5K5CcX62BISEAk8xU5DcTiYcl4GiG6vBQlVfOzAVYekz+gW7ohoVI90Z",
	"CAqeZsSdLUkLxtin4ZSXkDhKVjk2kQfYIwy7ZciV25GQyR0w01X+RhOBGeCx62LOJ7EPOJmGNRLWwSWe",
	"oNgXXI2gVOjhZAJC+ZvRR+Jhr15Cn2QJO4Vgw6CFW7cyxOyRuLjjujQOKxKI6zEA6UEl1OArMx+bKB8R",
	"EaNQEL/PqEQw9krIIzuCWPbMcFakB5FwCggHUh/5WGCvBOVPhbVyyPc0OWF7gnyOneXuzH8D/JhSH6MQ",
	"LiT4DPOIhhwrnddljLKB+SI/uDQUOBTyJ4oin7hKYBtfuNzRc2bpf2d4Atvw3xpLldrQrbzRiSI1sV4w",
	"jxTVAKjrxoxhD3ixxKvCjyQa5kLh2MwkF0onkwqb0QgzQTTwLvWkoi3gXS8hWyUvKdXD6JShIECCuGCG",
	"Qs+XxHSyuq5ZRcM4as0bRZs1q0riVVsX/tq5/HPQfT/qDu+KzObAAHOOpqWrJc3ZGYc0wIavvgG80q3I",
	"zUtR+QyX/QxqM/u9TwfTsZRyCd0Fw0jgPsMci4GhXoFKKHRnmnrrWEYZ347uqnjGMPbqvnuhJ3kSc6m0",
	"xIxwEKnlpTBJJjIDAQ2Vfd4kEA6cEFEJtrdEbTlhkSojdNeFA2eYTGfCru10W86xACQEEfmGfZ7bwuuK",
	"LBpa2VOupfgyNX4SbbkF4NN5szl73WzaOPFrjHwiSoyQaczv4j9atVaz+Z+p0ZEket3Mrfim2o6eiFdm",
	"LFRTFeydNyu6EFmBUKhccuM6GVCmr+MFJCyVhKqEUVPlKSMwFzXTYqOOpqZahQgc8E0MapPcRTovYgxJ",
	"I/StNqU1+a3GH0hUowpk5NciKhHGtHW14qwcU3k/YD3CkHJghi6N8KYNrUybGbiQeIwIw50SCVStyswB",
	"QZZ0WHE+gKAPOMxT5aR5clprNWvN1l3rpN1stpvNf8IMl3lI4Jqc00ayatxgcYFWuML0qJkedu4w/iq3",
	"nRW40j6JM9y7VM4h4py6BAkpYWJW6o0lvLavW2VnPeMEJU79Jd+LJ50cP5Vz6CjyKfJGzC/lywnxS5yA",
	"VfLJnhKdYwxiNa32rpfo0ifJL9HUhpOdjI1WBRK8tdRWRlOCqskdRf5c/liebkEvfypwUttqlA14Ir4v",
	"d6YcRXNsKDLEOqNyCH2TEiPFl420CkkWF1JR3CtTDap5VTGkh/8DKYKdqEw8O8RxSL7GGBAPh4JMCGZr",
	"oN5VVLlAAleCd6h6LhwYR946PPuIC6D7HBXVMfPtAIwG18malJEpCZFvW3wmRMTbjYb5Undp0Ej6N3T/",
	"JzyObEs/IkaQiTvZZVJ7L0k/rXeNaCUilxOxjdj/oKc6lKARdR5IBSZL1IQnNIY3C2InPRMUSaHPCyCi",
	"nCjRk+cojRqX0Sgi4VTRJIwDCdTwj85Anpwuujd33QF04M3t4O4ddGC3o05Uw9uR+vtRHrDuc+ckMzJP",
	"KYMbEkSUac2v4hRwSsQsHiuCEx4LxPBZ60STHLNG9DDVv7ncYordRL/z+vJkkx4mrJufEAECeYTM7JqG",
	"j5hxQsP2v0IAauDi9kN30AZDF0nbkrq9ggKXPmKmPgnEplgAjwQ4lEN5HahzYYSY4CBAc6m3FT6xV0+m",
	"vbnr9G6sE0uwJD+SsGz2G5qSRx/ueR10g0jMAWIYpUtOiO9jT/P2GLkPU0bj0AMu9SkzcLztXV+XAOH7",
	"ZcvfpR3NQh7hgjKhdpdhF4U7yS56s9CBcrk8YyzbXoQ1zMEyq9/ttkhHZoAcXdSPZn+/9btX0IH9myvF",
	"87/2oQM7H3pvoQPfdXsX+Y2a9pfZZWq5MobBvs+YMblPpVFKNzrqX992Lv/sd28ue2qz5kP3U7836F5C",
	"Bw66nct/SAJ3etfdy/zOk7YX2XpqBHNK+XCuSGIy/p4uiR36XV0TbSd720JiC4bsB8LNUYIw1T0vw2ZV",
	"HTDFVE8zHBYJA54QN76Z98KumIYjPYDmnaHNnplxmhoJRtd6aNs4OymX5ai9rROUI9GWqjAnNZVVYn9w",
	"e9EdDnXrD6MfV1m1pzsXFGTq+Fb3gAuur/xPBSphPdUEwjgYa9VgAFxJFGwfRtQAJ0vbGEJH4g4UPN/F",
	"kthkai/5/hnB3z2CT76n/frR0gc75At2jDYcXAa+W95irfVaSWqksy+JZNdQOvlwEL/VmuPYC9U7iIwF",
	"hF1lRhHwQoXftzAswBynbaCcnRw017dfSmldDDkfPjYbK65byWYbK2gx2jtL9GH5bAcxS9CYY5I1AjbA",
	"E8xw6FqC1d+Xx4/GajakliYR+0mN0Z7uYaLO9nMQk4qnl3ARB9iUDmn/eH3m1BQhbow2m2wfS+YuZH0A",
	"Cr1lc8f3lZvGYuwA5Pt2RZYmhtJxKyfHz1WZsHVyis9enf9Sw6/fjGutE++0hs5endfOTs7PW2etX86a",
	"zaZE1svkIXWB6BZZSEniJeZsBVsrrvHEoDYdVo7kOrhDD1g5zy72pMIAKvqbUL6C77xFHqDAjfl8+/FS",
	"97t4F2tz5nt5GT9kIcHWZmEtfo5rHg5ZzrC5mIEvyxi8anUMFUzG0kAfzk85Fsfu4K9kBTeD6vuNOqCT",
	"l3hLYk91AFz2WLdxE856O7q+1jGr37oXK7m75GNJhCr5qCc3c/N6J7e1pe7bIaC1MrWlwvkjEbNORH7H",
	"6syLfP92Atuft9GEcOEUtGo6YRG9nX4PPOC5yhxu5Cn08Ofwtvvp7p/Xpx+ffvn10/zrHx+9y1fvo/5k",
	"3n/7Kvx0N2+d9R+iD28+nT/Oh7d/Be+96Mu7f3z6/eT8cTy7nF5+2chtBtgi59wXkLW3O1fA3D5e3Qrm",
	"XsS7GylJ/LuVEY4ijpk4WBlhCVZ+lgz+LBl8kZJBC/+ZUsAio2kG4VtyiBQwMg2xB0aD6wNyxgwjD6s8",
	"AfI8ovfXz8FrCdBnYe6kw4Cei4NEgaUWRVcwJvc0ctA/w3dUiiOcUFrnp3UUoL9oiJ64NKLQhtrkmtx3",
	"q2IrTUDmaKQ2rzee3FNJyiMFCGIuVCENWla19Ed3IMBiRr06uJhh9wEkqUmPurwuUaKRo9yLjvo5PG34",
	"SEpmI+aYTWPiYRULU1CMmK/Z8Fbhrj4Tga+gCijDwMMCkZWQcZoMNfhvaPj/5wHP/xuN3dbJ6WZPMb3E",
	"qHOZhr+cDNvbrVjRHhQTQBNAPKDyPkll6TL6nsYOjGv6X4CKGWZPhGMHIBDiJ9PxX2HS0zi0ddDxfYC/",
	"ES4kpZLoZEgFIKHrxx72kiN0rMAEPuGZaTysLmLpeqGfV1h+JsB+3p/ZKQ9VVAocs8OkjaR2PGQ0J0Ck",
	"xAaoJoA8j8kja+ny8sv/ZkpODhKeKS6zMycT92ENN5vW8nW/0FnoUSvuohkVdFRqQmVrtpKnOLe1YEcO",
	"48oIJlU6KSVjRmxwMOpvdPQlAw5kv90DNAflPGvCIyGV2VLCnRlMl4Vu7ktkbmBQU9ylXKGwMxN26Vz+",
	"oWpfr0aFiukr6y3VfMxFTsfrA72FvUIsaiZ9g5hjN2ZEzIeSoNlISCfWek1dnU59FHMG+FTr9Hu137uZ",
	"QiYTklg4cIwRwywZr/8l1bfwt493yTVrZWpV63IWybr6LjB9IDgHg/60hGE0VOXGK8vLPZFwQi2+gUYA",
	"uEICP6G5CuooXw+FaKrujCsVzTCnMXN1bZIgwsfFsdCBpm4ctmGz3pIQ0wiHKCKwDU/rzbpU4JIcCqEN",
	"FJHGY6uB5PG6kQ2xTnVhklTeSiVLp12dAZNcnDqRq7mWz2mURLqWXRrZZyMWzsbumfcuFvcrt9hPms2D",
	"3V1PE4yWu+vD9EUFfw4YFozgR1WPmAzJeX22VVKwG/mb94rL4yBAbJ4csJHvg+yLCmjKlXwqZN9LFUy5",
	"hTDF+6jmPQTMxa/Umx8MUeUXXxfFdwaOQKGNBDLaMkHiwaijN54eRtJg2gqBFk6JTDWe0+DKQmsAefAo",
	"UvJSfV+h5HYyln8OpUxu1uDQHIoOjkO9N4DW4M+xK54rLF4AJS/KqAVNkpzqD4buKywKc1tVSmzBeDE0",
	"fRCkH14jlcfQfxCNZHy2o5FZI6ACpSvpJlO13UiLEZT7ZjU6ttqUH5RJ1pXRHJlNTGH7Ji4RjEynmGEP",
	"jJFwZ6nLt3w56GAMkyIDBLEvSOTjTLEJ2sa4raQU1juOK8m//1f+42pis7ryX007HtadLMy+rUtpycId",
	"1bNck/U7spyWJvKrepwruD6O57m6yA5C2nhefTutgkNq54PtZNf6GNwe7umxEJ66qZuRXe6uvjjCjiAE",
	"u6uxo/iyZWts6dMemTLH8nB/FM1Y2d89lngafxdtqQtjMWtMKZ36uGEexiz1VoYCMXGl+g7JNOxtzx/5",
	"JzwLInvaPCnquGSMyjhToNcHEoCagsBk6OXAa6oJWX6XNvc2qAn4qucUKCvOvGSD1Zj1Yk+imRAubH++",
	"z5JQIbgIR0q+WMxwKAy3bqRjw0W+P0buQylB35KQ8Nl6ilpKF2Mxo4z8pVNS6o1HhkXMQumkzxPwzbOr",
	"5q3Vkhc95eC1L5QWkgU2gPSN4BRuSc+I4UccCnAxHLwFSAjkPvAyIJKLytWhqMS3OeE3NRQk1HURGkeH",
	"Yt4lqlVQ/LuwrmalPXhXcQrV5snuectJb2MBt3aMDPLl5IdSthIWOaGiQ3IzXdKj4pbLwp8bonw/A3z7",
	"B/gSODfSIwn56IKhmimRWncqNBVyg+sfNNxT8qTfkf2kZd3gJtYgnMfYK9YGHowzenIBFcspr2pDoQ77",
	"ZFhGP59QmWGeTcHYWonumTX24pPNkZ7sO/4Vupc9531UzWFep6isN3QM8BhaIz/zWgZQGfmGLicpo/GF",
	"NgwjbReOJ2Acsy3QlzVXR8GidYF1djHvVzzn6hE+30u2zVY46C/ZeoPP95I/5bnH7rVeJE/HqB6mjrMN",
	"G4qtDVjJVYJV8ORa+Trq7KfkYZXlaHXEWtwv/i8AAP//2MAWc19jAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
