apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "imageer-gateway.fullname" . }}
  labels:
    {{- include "imageer-gateway.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - create
      - update
