// Code generated by "enumer -type=Format -trimprefix Format -output format_enum.go -transform lower -text"; DO NOT EDIT.

package log

import (
	"fmt"
	"strings"
)

const _FormatName = "jsontextpretty"

var _FormatIndex = [...]uint8{0, 4, 8, 14}

const _FormatLowerName = "jsontextpretty"

func (i Format) String() string {
	if i < 0 || i >= Format(len(_FormatIndex)-1) {
		return fmt.Sprintf("Format(%d)", i)
	}
	return _FormatName[_FormatIndex[i]:_FormatIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _FormatNoOp() {
	var x [1]struct{}
	_ = x[FormatJSON-(0)]
	_ = x[FormatText-(1)]
	_ = x[FormatPretty-(2)]
}

var _FormatValues = []Format{FormatJSON, FormatText, FormatPretty}

var _FormatNameToValueMap = map[string]Format{
	_FormatName[0:4]:       FormatJSON,
	_FormatLowerName[0:4]:  FormatJSON,
	_FormatName[4:8]:       FormatText,
	_FormatLowerName[4:8]:  FormatText,
	_FormatName[8:14]:      FormatPretty,
	_FormatLowerName[8:14]: FormatPretty,
}

var _FormatNames = []string{
	_FormatName[0:4],
	_FormatName[4:8],
	_FormatName[8:14],
}

// FormatString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func FormatString(s string) (Format, error) {
	if val, ok := _FormatNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _FormatNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Format values", s)
}

// FormatValues returns all values of the enum
func FormatValues() []Format {
	return _FormatValues
}

// FormatStrings returns a slice of all String values of the enum
func FormatStrings() []string {
	strs := make([]string, len(_FormatNames))
	copy(strs, _FormatNames)
	return strs
}

// IsAFormat returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Format) IsAFormat() bool {
	for _, v := range _FormatValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Format
func (i Format) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Format
func (i *Format) UnmarshalText(text []byte) error {
	var err error
	*i, err = FormatString(string(text))
	return err
}
