/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all projects */
        get: operations["listProjectsAdmin"];
        put?: never;
        /** Create a new project */
        post: operations["createProjectAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project details */
        get: operations["getProjectAdmin"];
        /** Update project details */
        put: operations["updateProjectAdmin"];
        post?: never;
        /** Delete a project */
        delete: operations["deleteProjectAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/projects/{projectId}/images/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess multiple images in a project */
        post: operations["reprocessImagesAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/service-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List service accounts */
        get: operations["listServiceAccountsAdmin"];
        put?: never;
        /** Create a new service account */
        post: operations["createServiceAccountAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/service-accounts/{serviceAccountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get service account details */
        get: operations["getServiceAccountAdmin"];
        /** Update a service account */
        put: operations["updateServiceAccountAdmin"];
        post?: never;
        /** Delete a service account */
        delete: operations["deleteServiceAccountAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user details */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Google Sign-In */
        get: operations["startGoogleSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/sign-in/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finish Google Sign-In */
        get: operations["finishGoogleSignIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project details */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/images/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a presigned URL for uploading an image */
        post: operations["createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{projectId}/images/{imageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get image details */
        get: operations["getImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The current state of the image.
         * @example READY
         * @enum {string}
         */
        ImageState: "UPLOAD_PENDING" | "UPLOAD_EXPIRED" | "READY" | "FAILED";
        /**
         * @description The current state of the image variant.
         * @example READY
         * @enum {string}
         */
        ImageVariantState: "UPLOAD_PENDING" | "UPLOAD_EXPIRED" | "PROCESSING" | "READY" | "FAILED";
        /**
         * @description The content type of the image.
         * @example WEBP
         * @enum {string}
         */
        ImageFormat: "JPEG" | "PNG" | "WEBP" | "AVIF" | "HEIC";
        /**
         * @description The fit mode for image conversion:
         *       - COVER: Scale the image to cover the target dimensions. Some parts may be cropped.
         *       - CONTAIN: Scale the image to fit within the target dimensions. No cropping occurs. Empty areas may be filled with background color.
         *       - FILL: Scale the image to fill the target dimensions. The image may be distorted.
         * @example CONTAIN
         * @enum {string}
         */
        ImageFit: "COVER" | "CONTAIN" | "FILL";
        /**
         * @description The anchor position for image cropping.
         * @example SMART
         * @enum {string}
         */
        ImageAnchor: "SMART" | "CENTER" | "NORTH" | "EAST" | "SOUTH" | "WEST";
        /**
         * @description The role of the user.
         * @example GUEST
         * @enum {string}
         */
        UserRole: "ADMIN" | "GUEST";
        /**
         * @description The access scope of the service account.
         * @example PROJECT
         * @enum {string}
         */
        ServiceAccountAccessScope: "FULL" | "PROJECT";
        CreateProjectAdminRequest: {
            /**
             * @description The name of the project.
             * @example test-project
             */
            name: string;
            presets?: components["schemas"]["CreatePresetRequest"][];
        };
        UpdateProjectAdminRequest: {
            /**
             * @description The name of the project.
             * @example test-project
             */
            name?: string;
            presets?: components["schemas"]["UpsertPresetRequest"][];
        };
        CreateServiceAccountAdminRequest: {
            /**
             * @description The name of the service account.
             * @example test-service-account
             */
            name: string;
            accessScope: components["schemas"]["ServiceAccountAccessScope"];
            /** @description List of project IDs to associate with the service account. */
            projectIds?: string[];
            /**
             * Format: date-time
             * @description The expiration time of the service account token.
             * @example 2023-10-01T12:00:00Z
             */
            expireAt?: string;
        };
        UpdateServiceAccountAdminRequest: {
            /**
             * @description The name of the service account.
             * @example test-service-account
             */
            name?: string;
            accessScope?: components["schemas"]["ServiceAccountAccessScope"];
            /** @description List of project IDs to associate with the service account. */
            projectIds?: string[];
            /**
             * Format: date-time
             * @description The expiration time of the service account token.
             * @example 2023-10-01T12:00:00Z
             */
            expireAt?: string;
        };
        CreateUploadUrlRequest: {
            /**
             * @description The name of the file to be uploaded.
             * @example image.jpg
             */
            fileName: string;
            format: components["schemas"]["ImageFormat"];
            /** @description List of preset names to apply to the image. If not provided, default presets will be applied. */
            presetNames?: string[];
        };
        ReprocessImagesAdminRequest: {
            /**
             * @description List of image IDs to reprocess. If not provided and reprocessAll is true, all images in the project will be reprocessed.
             * @example [
             *       "426e634f-50dd-41a0-881b-c991441b3cd5",
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            imageIds?: string[];
            /**
             * @description If true, reprocess all images in the project. Takes precedence over imageIds.
             * @default false
             * @example false
             */
            reprocessAll: boolean;
        };
        CreatePresetRequest: {
            /**
             * @description The name of the preset.
             * @example w600h800
             */
            name: string;
            /**
             * @description Indicates if this preset is the default one.
             * @example false
             */
            default: boolean;
            format?: components["schemas"]["ImageFormat"];
            /**
             * Format: int64
             * @description The quality of the image (1-100). Default is 80.
             * @example 90
             */
            quality?: number;
            fit?: components["schemas"]["ImageFit"];
            anchor?: components["schemas"]["ImageAnchor"];
            /**
             * Format: int64
             * @description The width of the image in pixels.
             * @example 600
             */
            width?: number;
            /**
             * Format: int64
             * @description The height of the image in pixels.
             * @example 800
             */
            height?: number;
        };
        /**
         * @description If id is provided, the preset will be updated; otherwise, a new preset
         *     will be created. All existing presets not included in the upsert list
         *     will be deleted.
         */
        UpsertPresetRequest: {
            /**
             * @description The unique identifier of the preset.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            id?: string;
            /**
             * @description The name of the preset.
             * @example w600h800
             */
            name?: string;
            /**
             * @description Indicates if this preset is the default one.
             * @example false
             */
            default?: boolean;
            format?: components["schemas"]["ImageFormat"];
            /**
             * Format: int64
             * @description The quality of the image (1-100). Default is 80.
             * @example 90
             */
            quality?: number;
            fit?: components["schemas"]["ImageFit"];
            anchor?: components["schemas"]["ImageAnchor"];
            /**
             * Format: int64
             * @description The width of the image in pixels.
             * @example 600
             */
            width?: number;
            /**
             * Format: int64
             * @description The height of the image in pixels.
             * @example 800
             */
            height?: number;
        };
        AppError: {
            /**
             * @description Error message
             * @example Some complex error message
             */
            message: string;
            /**
             * Format: int64
             * @description Error code ID for programmatic handling
             * @example 1000
             */
            codeId: number;
            /**
             * @description Error code name for programmatic handling
             * @example BAD_REQUEST
             */
            codeName: string;
        };
        Project: {
            /**
             * @description The unique identifier of the project.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            id: string;
            /**
             * Format: date-time
             * @description The creation time of the project.
             * @example 2023-10-01T12:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The last update time of the project.
             * @example 2023-10-01T12:00:00Z
             */
            updatedAt: string;
            /**
             * @description The name of the project.
             * @example test-project
             */
            name: string;
            /** @description List of presets to apply to images of the project. */
            presets: components["schemas"]["Preset"][];
        };
        Projects: {
            items: components["schemas"]["Project"][];
            /**
             * Format: int64
             * @description The total number of projects.
             * @example 100
             */
            total: number;
        };
        Preset: {
            /**
             * @description The unique identifier of the preset.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            id: string;
            /**
             * Format: date-time
             * @description The creation time of the preset.
             * @example 2023-10-01T12:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The last update time of the preset.
             * @example 2023-10-01T12:00:00Z
             */
            updatedAt: string;
            /**
             * @description The name of the preset.
             * @example w600h800
             */
            name: string;
            /**
             * @description Indicates if this preset is the default one.
             * @example false
             */
            default: boolean;
            format: components["schemas"]["ImageFormat"];
            /**
             * Format: int64
             * @description The quality of the image (1-100).
             * @example 90
             */
            quality: number;
            fit?: components["schemas"]["ImageFit"];
            anchor?: components["schemas"]["ImageAnchor"];
            /**
             * Format: int64
             * @description The width of the image in pixels.
             * @example 600
             */
            width?: number;
            /**
             * Format: int64
             * @description The height of the image in pixels.
             * @example 800
             */
            height?: number;
        };
        UploadUrl: {
            /**
             * @description The unique identifier of the image.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            imageId: string;
            /**
             * @description The presigned URL for uploading the image. It must be called with PUT method. Check https://docs.aws.amazon.com/AmazonS3/latest/userguide/PresignedUrlUploadObject.html for more details.
             * @example https://aws.com/upload?key=abc123
             */
            url: string;
            /**
             * @description Additional headers required for the upload request.
             * @example {
             *       "Host": "foo.s3.amazonaws.com"
             *     }
             */
            header: {
                [key: string]: string;
            };
            /**
             * Format: date-time
             * @description The expiration time of the presigned URL.
             * @example 2023-10-01T12:00:00Z
             */
            expiresAt: string;
        };
        Image: {
            /**
             * @description The unique identifier of the image.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            id: string;
            /**
             * Format: date-time
             * @description The creation time of the image.
             * @example 2023-10-01T12:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The last update time of the image.
             * @example 2023-10-01T12:00:00Z
             */
            updatedAt: string;
            state: components["schemas"]["ImageState"];
            /**
             * @description The URL of the original image.
             * @example https://example.com/original/image.webp
             */
            url: string;
            format: components["schemas"]["ImageFormat"];
            /** @description List of image variants with applied presets. */
            variants?: components["schemas"]["ImageVariant"][];
        };
        Images: {
            items: components["schemas"]["Image"][];
            /**
             * Format: int64
             * @description The total number of images.
             * @example 100
             */
            total: number;
        };
        ImageVariant: {
            /**
             * @description The unique identifier of the image variant.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            id: string;
            /**
             * Format: date-time
             * @description The creation time of the image variant.
             * @example 2023-10-01T12:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The time when the image variant was updated.
             * @example 2023-10-01T12:00:00Z
             */
            updatedAt: string;
            /**
             * @description The unique identifier of the preset.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            presetId: string;
            /**
             * @description The name of the preset.
             * @example w600h800
             */
            presetName: string;
            state: components["schemas"]["ImageVariantState"];
            /**
             * @description The URL of the image with the applied preset.
             * @example https://example.com/presets/w600h800/image.webp
             */
            url: string;
            format: components["schemas"]["ImageFormat"];
        };
        ServiceAccount: {
            /**
             * @description The unique identifier of the service account.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            id: string;
            /**
             * Format: date-time
             * @description The creation time of the service account.
             * @example 2023-10-01T12:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The last update time of the service account.
             * @example 2023-10-01T12:00:00Z
             */
            updatedAt: string;
            /**
             * Format: date-time
             * @description The expiration time of the service account token.
             * @example 2023-10-01T12:00:00Z
             */
            expireAt?: string;
            /**
             * @description The name of the service account.
             * @example test-service-account
             */
            name: string;
            accessScope: components["schemas"]["ServiceAccountAccessScope"];
            /** @description List of projects associated with the service account. */
            projects: components["schemas"]["ProjectReference"][];
        };
        ServiceAccountWithApiKey: components["schemas"]["ServiceAccount"] & {
            /**
             * @description The API key for the service account.
             * @example ak_SOEXTZL3Ww7BXyqMWdD5QpPfyPF5nXTy14PkpV9X6vySOzmQdpjHYXK26vbhDgDj
             */
            apiKey: string;
        };
        ServiceAccounts: {
            items: components["schemas"]["ServiceAccount"][];
            /**
             * Format: int64
             * @description The total number of service accounts.
             * @example 100
             */
            total: number;
        };
        ProjectReference: {
            /**
             * @description The unique identifier of the project.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            id: string;
            /**
             * @description The name of the project.
             * @example test-project
             */
            name: string;
        };
        User: {
            /**
             * @description The unique identifier of the user.
             * @example 426e634f-50dd-41a0-881b-c991441b3cd5
             */
            id: string;
            /**
             * @description The nickname of the user.
             * @example johndoe
             */
            nickname: string;
            role: components["schemas"]["UserRole"];
            /**
             * @description The email address of the user.
             * @example user@example.com
             */
            email: string;
            /**
             * Format: uri
             * @description The photo URL of the user.
             * @example https://example.com/photos/user.webp
             */
            photoUrl: string;
            /**
             * Format: date-time
             * @description The creation time of the user.
             * @example 2023-10-01T12:00:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description The last update time of the user.
             * @example 2023-10-01T12:00:00Z
             */
            updatedAt: string;
        };
    };
    responses: {
        /** @description Error occurred during the request */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AppError"];
            };
        };
    };
    parameters: {
        /** @description The ID of the project to which the image belongs. */
        ProjectIdPath: string;
        /** @description The ID of the service account. */
        ServiceAccountIdPath: string;
        /** @description The ID of the image. */
        ImageIdPath: string;
        /** @description Offset for pagination */
        OffsetQuery: number;
        /** @description Limit for pagination */
        LimitQuery: number;
        /** @description Wait until the image processing is completed */
        WaitUntilProcessedQuery: boolean;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjectsAdmin: {
        parameters: {
            query?: {
                /** @description Offset for pagination */
                offset?: components["parameters"]["OffsetQuery"];
                /** @description Limit for pagination */
                limit?: components["parameters"]["LimitQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Projects"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createProjectAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateProjectAdminRequest"];
            };
        };
        responses: {
            /** @description Successfully created project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getProjectAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project to which the image belongs. */
                projectId: components["parameters"]["ProjectIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateProjectAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project to which the image belongs. */
                projectId: components["parameters"]["ProjectIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProjectAdminRequest"];
            };
        };
        responses: {
            /** @description Successfully updated project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteProjectAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project to which the image belongs. */
                projectId: components["parameters"]["ProjectIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully deleted project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    reprocessImagesAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project to which the image belongs. */
                projectId: components["parameters"]["ProjectIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReprocessImagesAdminRequest"];
            };
        };
        responses: {
            /** @description Successfully triggered batch image reprocessing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Images"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listServiceAccountsAdmin: {
        parameters: {
            query?: {
                /** @description Offset for pagination */
                offset?: components["parameters"]["OffsetQuery"];
                /** @description Limit for pagination */
                limit?: components["parameters"]["LimitQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved service accounts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAccounts"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createServiceAccountAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateServiceAccountAdminRequest"];
            };
        };
        responses: {
            /** @description Successfully created service account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAccountWithApiKey"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getServiceAccountAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the service account. */
                serviceAccountId: components["parameters"]["ServiceAccountIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved service account details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAccount"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateServiceAccountAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the service account. */
                serviceAccountId: components["parameters"]["ServiceAccountIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateServiceAccountAdminRequest"];
            };
        };
        responses: {
            /** @description Successfully updated service account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceAccount"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    deleteServiceAccountAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the service account. */
                serviceAccountId: components["parameters"]["ServiceAccountIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully deleted service account */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved current user details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    startGoogleSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirecting to Google Sign-In */
            302: {
                headers: {
                    /** @description The URL to redirect the user to for Google Sign-In */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    finishGoogleSignIn: {
        parameters: {
            query: {
                /** @description The authorization code returned by Google after sign-in. */
                code: string;
                /** @description The state parameter to prevent CSRF attacks. */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully signed in with Google */
            302: {
                headers: {
                    /** @description The URL to redirect the user to after signing in */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project to which the image belongs. */
                projectId: components["parameters"]["ProjectIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The ID of the project to which the image belongs. */
                projectId: components["parameters"]["ProjectIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateUploadUrlRequest"];
            };
        };
        responses: {
            /** @description Successfully issued the presigned URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadUrl"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getImage: {
        parameters: {
            query?: {
                /** @description Wait until the image processing is completed */
                waitUntilProcessed?: components["parameters"]["WaitUntilProcessedQuery"];
            };
            header?: never;
            path: {
                /** @description The ID of the project to which the image belongs. */
                projectId: components["parameters"]["ProjectIdPath"];
                /** @description The ID of the image. */
                imageId: components["parameters"]["ImageIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully retrieved image details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
