log:
  format: json # pretty, text, json
  level: info # debug, info, warn, error
  add-source: false
  component: imageer-processor

trace:
  enabled: false
  service-name: imageer-processor
  sampling-ratio: 0.1
  otlp-grpc-endpoint: localhost:4317

web:
  port: 9090

kafka:
  addresses: localhost:15420
  username: admin
  password: complex_password
  consumer-group: imageer-processor

  topics:
    image-process-request:
      topic: imageer.image.process.request
      retry-topic: imageer.image.process.request.retry
      handler:
        timeout: 30s
        max-retry-attempt: 3
        retry-base-delay: 100ms

    image-process-result:
      topic: imageer.image.process.result

aws:
  s3:
    bucket: imageer
